LPSiteNotification=function(){var r=!1,C;C=function(a){var b=a.target,c=$('input:not([type]),input[type="text"],input[type="email"],input[type="password"]'),d;a:{d=0;for(var f=c.length;d<f;++d)if("password"===c[d].type&&c[d].value){d=!0;break a}d=!1}if(d){d=b;for(b=[];d&&d.parentElement&&d.parentElement!==document.body;)b.unshift(d.parentElement),d=d.parentElement;d=0;for(f=c.length;d<f;++d){var e=c[d];if(e.value&&s(e))for(var e=e.parentElement,g=null;e;){"FORM"===e.nodeName&&(g=e);var j=b.indexOf(e);
if(-1<j){g?a.form=g:a.genericForm=b[j];m(a);return}e=e.parentElement}}}};var m,D,v=["submit","click","keydown"],p={},w=!1;D=function(a,b){-1<v.indexOf(a)?(p[a]=b,w||(w=!0,setTimeout(function(){for(var a=0;a<v.length;++a){var b=v[a];if(p.hasOwnProperty(b)){p[b]();break}}w=!1;p={}},0))):b()};m=function(a){var b=a.form||a.genericForm;if(b){var c=$(b).find('input:not([type]),input[type="text"],input[type="email"],input[type="password"]').filter(function(){return s(this)});if(a.form){for(var b=a.form,
d=[],f={},e=0;e<b.length;++e){var g=b[e];switch(g.type){case "hidden":case "text":case "email":if(g.value&&!f.hasOwnProperty(g.value)&&("hidden"===g.type||!s(g))){f[g.value]=!0;var j=LPContentScriptTools.findTextParent({searches:g.value,exactMatch:!0});j&&(j.parent&&"OPTION"!==j.parent.nodeName&&s(j.parent))&&d.push(g)}}}c=d.concat(c.toArray())}for(var h=[],k=!1,b=0;b<c.length;++b)if(d=c[b],d.value){for(var f=d,e=f.type,g=f.value,j=f.id,n=f,m=["name","ng-model","data-reactid"],p={},l=0;l<m.length;++l){var q=
n.getAttribute(m[l]);q&&(p[m[l]]=q)}e={type:e,value:g,id:j,attributes:p};"password"!==e.type&&"disc"===$(f).css("text-security")&&(e.type="password");f=e;"password"===f.type&&(k=!0);h.push({input:d,inputData:f})}D(a.type,function(){var b;b=[];for(var d=0;d<h.length;++d){var e=h[d];"password"!==e.inputData.type&&(e.inputData.value=x.getUnmaskedValue({input:e.input,inputValue:e.inputData.value,form:a.form}));b.push(e.inputData)}b={url:document.location.href,top:window===top,fields:b,generatedPassword:a.generatedPassword};
k?(a.type&&(r=!0),bg.LPTabState.processPasswordSubmit({formData:b,callback:a.generatedPassword||LPContentScriptTools.isUnloading()?null:E})):0<c.length&&bg.LPTabState.processTextSubmit(b)})}};var s=function(a){a instanceof $||(a=$(a));if(!a.is(":visible"))return!1;a=a.get(0).getBoundingClientRect();return!(0>a.right||0>a.top||a.left>window.innerWidth||a.bottom>window.innerHeight)},F=function(a){var b;if(a.id)b=$(document.getElementById(a.id));else for(var c in a.attributes)if(b=$("input["+c+'="'+
a.attributes[c]+'"]'),0<b.length)break;return b},G=function(a){for(var b=0;b<a.fields.length;++b){var c=a.fields[b];if("password"===c.type)return b=c,(c=F(b))&&0<c.length&&s(c)?a.passwordChangeForm?c.val()===b.value:!0:!1}return!1},H,N=function(a,b){var c=F(a);c&&c.unbind("input.submissionFailed").bind("input.submissionFailed",function(){b(!0)})};H=function(a,b){for(var c=0;c<a.fields.length;++c){var d=a.fields[c];"password"===d.type&&N(d,b)}};var E=function(a){LPContentScriptTools.isUnloading()||
(Topics.get(Topics.SITE_NOTIFICATION_STATE).publish(a),bg.get("LPContentScriptFeatures").new_save_site&&a.dialogData&&csTop.LPSiteNotification.showSiteNotification(a))},I=function(a){for(;a;){if("FORM"===a.nodeName)return a;a=a.parentElement}return null},y,J=function(a){a=a.toLowerCase();return-1<a.indexOf("submit")||-1<a.indexOf("save")},z=function(a){a=a.attributes;for(var b=0;b<a.length;++b){var c=a[b];if(J(c.name)||J(c.value))return!0}return!1};y=function(a){if("INPUT"===a.nodeName)return"submit"===
a.type?!0:"button"===a.type?z(a):!1;for(;a&&0===a.getElementsByTagName("input").length;){if("BUTTON"===a.nodeName)return"submit"===a.type||z(a);if(z(a))return!0;a=a.parentElement}return!1};var k,n=null,l=[],A=function(){n&&(n.disconnect(),n=null);l=[]},O=function(a){a:{for(var b=0;b<a.length;++b){var c=a[b];switch(c.type){case "attributes":if(c.target.getAttribute(c.attributeName)!==c.oldValue){a=!0;break a}break;default:a=!0;break a}}a=!1}a&&(l.forEach(function(a){a()}),A())};k={reset:A,onChange:function(a){"function"===
typeof MutationObserver&&(n||(n=new MutationObserver(O),n.observe(document.body,{childList:!0,attributes:!0,characterData:!0,subtree:!0,attributeOldValue:!0})),-1===l.indexOf(a)&&l.push(a),setTimeout(function(){A()},0))}};var x,q=!1,h=[];Topics.get(Topics.FILLED_GENERATED_PW).subscribe(function(a){B({target:a.element,generatedPassword:a.password})});Topics.get(Topics.CLEAR_DATA).subscribe(function(){K()});Topics.get(Topics.LOGIN).subscribe(function(){L()});var t=function(a){return function(b){if(!1!==
b.isTrusted)try{a(b)}catch(c){console.log(c)}}},B=function(a){a.form=I(a.target);a.form?m(a):C(a)},M=function(){r=!1;bg.LPTabState.clear()},u={submit:t(function(a){k.reset();m({form:I(a.target),submit:!0,type:a.type})}),click:t(function(a){if(y(a.target))k.reset(),B({target:a.target,type:a.type});else if(r)k.onChange(M)}),keydown:t(function(a){var b=a.target;if(b!==document.body&&13===(a.keyCode||a.which))if("INPUT"===b.nodeName||y(b))k.reset(),B({target:b,type:a.type});else if(r)k.onChange(M)}),
change:t(function(a){a=a.target;if("INPUT"===a.nodeName&&a.value)switch(a.type){case "text":case "email":for(var b=0;b<h.length;++b)if(h[b].input===a){h[b].value=a.value;return}h.push({input:a,value:a.value})}})},L=function(){if(!q){for(var a in u)document.addEventListener(a,u[a],!0);q=!0}},K=function(){if(q){for(var a in u)document.removeEventListener(a,u[a],!0);q=!1}h=[]};x={setup:L,teardown:K,getUnmaskedValue:function(a){if(-1<a.inputValue.indexOf("*")||-1<a.inputValue.indexOf(String.fromCharCode(8226))){var b;
for(b=0;b<h.length;++b){var c=h[b];if(c.input===a.input&&c.value!==a.inputValue)return c.value}if(a.form)for(b=0;b<a.form.length;++b)if(c=a.form[b],c.value&&!(-1<c.value.indexOf("*")||-1<c.value.indexOf(String.fromCharCode(8226)))&&c.value.length===a.inputValue.length&&(c.value[0]===a.inputValue[0]||c.value[c.value.length-1]===a.inputValue[a.inputValue.length-1]))return c.value}return a.inputValue}};Topics.get(Topics.INITIALIZED).subscribe(function(){bg.LPTabState.isFormTrackingEnabled(function(a){a&&
(x.setup(),window===top&&bg.LPTabState.getSiteNotification({callback:E}))})});return{formExists:function(a,b){var c=0,d=null,f=!1,e=function(){g(G(a))},g=function(a){f||(r=!1,f=!0,clearInterval(d),window.removeEventListener("beforeunload",e,!0),b(a))};r?(d=setInterval(function(){++c;var b=G(a);(!b||4<c)&&g(b)},1E3),window.addEventListener("beforeunload",e,!0),H(a,g)):e()},showSiteNotification:function(a){a.postSetup=function(){Topics.get(Topics.SITE_NOTIFICATION).publish(b)};var b=LPFrame.openDialog("contentScriptSite",
a,{css:{top:10,right:10}})}}}();
