var SiteDialog=function(k){DialogWithGroupInput.call(this,k,{confirmOnClose:!1,hideButtons:!0,hideHeader:!0,type:Account,additionalClasses:"lmiDialog",additionalDropdownClasses:"lmiDropdown"});this.tiles=[];this.selectedTile=this.activeTile=null;this.submitted=this.isSelectable=!1};SiteDialog.prototype=Object.create(DialogWithGroupInput.prototype);SiteDialog.prototype.constructor=SiteDialog;
(function(){SiteDialog.prototype.initialize=function(a){DialogWithGroupInput.prototype.initialize.apply(this,arguments);var b=this;a.on("click",".neverSave",function(){bg.handleNeverURL({action:"never",cmd:"neverdomain",url:b.data.defaultData.url,fromsave:!0});bg.IntroTutorial.setState({enabled:!1});b.sendTrackingEvent("never");b.close()});a.on("change",function(){b.data.generatedPasswordSaved&&b.nextButton.text(Strings.translateString("Update"))});b.backButton=a.find("#close").bind("click",function(){b.data.generatedPassword?
b.data.generatedPasswordSaved?(b.dialogContent.css({height:b.dialogContent.css("height")}),b.$element.addClass("removeGeneratedConfirmation"),b.sendTrackingEvent("undo")):(b.sendTrackingEvent("discard"),b.close()):(b.sendTrackingEvent("notnow"),b.close())});b.nextButton=a.find("#submit").bind("click",function(){b.isSelectable?b.selectedTile&&b.submit():b.submit()});a.find("#closeConfirmation").bind("click",function(){b.close()});a.find("#deleteGenerated").bind("click",function(){b.vaultItem.deleteItem({confirm:!1});
b.close()});a.find(".addNewSiteButton").bind("click",function(){var a=b.tiles.slice();b.defaultFields(b.data);b.originalData=b.getData();b.populateFields(b.data.dialogData);b.setupAdd();b.setSelectable(!1);$(this).LP_hide();for(var d=0;d<a.length;++d)a[d].remove()})};SiteDialog.prototype.sendTrackingEvent=function(a){var b=this.clickedEdit?"savesiteedit":"savesiteseen";a={action:a};this.clickedEdit&&$.extend(a,{changedEmail:this.inputFields.unencryptedUsername.getValue()!==this.data.defaultData.unencryptedUsername,
changedPassword:this.inputFields.password.getValue()!==this.data.dialogData.password,showedPassword:this.activeTile?this.activeTile.showedPassword():!1});bg.sendLpImprove(b,a)};SiteDialog.prototype.setupAdd=function(a){a=a||this.data;this.$element.find(".question").text(Strings.translateString("Add to LastPass?"));this.nextButton.text(Strings.translateString("Add"));var b=new this.SiteTile;a.defaultData.unencryptedUsername||b.showDetails({animate:!1,clearErrors:!0})};var k=function(a,b,c){var d=$.extend({},
a.defaultData);b&&$.extend(d,b.getFormData($.extend(c,DialogInput.getProperties(a.dialogData),DialogInput.getProperties(a.defaultData))));return d};SiteDialog.prototype.hasDuplicates=function(){for(var a=0;a<this.tiles.length;++a)if(0<this.tiles[a].getDuplicates().length)return!0;return!1};SiteDialog.prototype.setup=function(a,b){b.saveOptions={saveFromSubmit:b.dialogData.fields?!0:!1,source:"saveSite"};a.find(".addSiteFavicon").append(LPTools.createElement("img",{"class":"favicon",src:b.favicon?
b.favicon:"images/site/world.png"}));for(var c=this,d=a.find(".tileContainer"),f=a.find(".question"),j=a.find(".explanation"),m=a.find(".dialogForm"),n=a.find(".tile.template"),s=a.find(".deleteOverlayContainer.template"),u,g={},h=n.find("[dialogFieldDisplay]"),l=0;l<h.length;++l)g[h[l].getAttribute("dialogFieldDisplay")]=!0;u=g;var v=DialogInput.getProperties(c.inputFields),g=this.SiteTile=function(a){a=a||{};var b=this,e=n.clone().removeClass("template"),f=null,j=c.data,g=!1,h=!1,p=null,l=!1,C=
k(j,a.site,v),q=$.extend(k(j,a.site,v),j.dialogData),r=null,x=function(a){a&&c.clearErrors();c.originalData=C;c.populateFields(q)};this.showedPassword=function(){return l};this.getDialogData=function(){return q};this.getDuplicates=function(){if(null===r&&(r=[],j.defaultData.unencryptedUsername)){var a=bg.hostof(q.url);c.tiles.forEach(function(c){var d=c.getDialogData();c!==b&&bg.hostof(d.url)===a&&r.push(c)})}return r};var y=function(a,b){a=a||{};var c=LPTools.getOption(a,"animate",!0),d="animating";
c&&(a.animationClass&&(d+=" "+a.animationClass),e.addClass(d));var f=function(a){e.removeClass(d);a&&a.transitionEndHandler&&a.transitionEndHandler();b({callback:a&&a.onFrameResizeComplete})};a.change(function(a){var b=LPTools.getOption(a,"tileHeight",e.children().first().outerHeight()),d=e.height();e.css("height",b);if(b!==d&&c){var w=function(b){b.target===this&&(e.unbind("transitionend",w),f(a))};e.bind("transitionend",w)}else f(a);return b})};this.handleHeightChange=function(a){LPTools.getOption(a,
"animate",!0)?c.requestAnimationFrame(function(b){y(a,b)}):y(a,function(a){c.setFrameSize();a&&a.callback&&a.callback()})};this.showDetails=function(a){this.handleHeightChange($.extend(a,{animationClass:"details-animatation",change:function(d){null===p&&(p=e.height());c.activeTile&&c.activeTile!==b&&c.activeTile.hideDetails(a);c.activeTile=b;x(a&&a.clearErrors);e.find(".tileContent").append(m);e.addClass("details");d=d();c.clickedEdit||(c.clickedEdit=!0,c.sendTrackingEvent("edit"),c.adjustView(!0),
c.adjustScrollHeight(d-p))}}))};this.preSubmit=function(){c.activeTile!==this&&(c.activeTile&&(c.activeTile.hideDetails(),c.activeTile=null),x());c.vaultItem=a.site};this.hideDetails=function(a){q=c.getData();var b=m.clone();this.handleHeightChange($.extend(a,{animationClass:"details-animatation",change:function(a){e.find(".tileContent").append(b);e.removeClass("details");a({transitionEndHandler:function(){b.remove()},tileHeight:p})}}))};this.unselect=function(){g&&(c.selectedTile=null,g=!1,e.removeClass("selected"),
c.$element.removeClass("selected"),c.nextButton.prop("disabled",!0))};this.toggleSelect=function(){g?(this.unselect(),this.getDuplicates().forEach(function(a){a.hideDeleteOverlay()})):(this.getDuplicates().forEach(function(a){a.showDeleteOverlay()}),c.tiles.forEach(function(a){a.unselect()}),c.selectedTile=this,g=!0,e.addClass("selected"),c.$element.addClass("selected"),c.nextButton.prop("disabled",!1))};this.remove=function(){e.remove();for(var a=0;a<c.tiles.length;++a)if(c.tiles[a]===this){c.tiles.splice(a,
1);break}};this.showDeleteOverlay=function(){null===f&&(f=s.clone().removeClass("template"),f.find(".cancelDeleteButton").bind("click",this.hideDeleteOverlay),f.find(".deleteButton").bind("click",function(){a.site.deleteItem({confirm:!1,success:function(){b.remove()}});b.hideDeleteOverlay()}));e.append(f);e.addClass("duplicate")};this.hideDeleteOverlay=function(){e.removeClass("duplicate");f.one("animationend",function(){e.hasClass("duplicate")||f.detach()})};this.setSelectable=function(a){h=a;var b=
e.find(".favicon");h?(b.addClass("hoverFadeOut"),e.find(".checkmark").LP_show()):(b.removeClass("hoverFadeOut"),e.find(".checkmark").LP_hide());c.setSelectable(a)};e.find(".tileEdit").bind("click",function(){b.showDetails({clearErrors:!0})});e.find(".checkmark").bind("click",function(){b.toggleSelect()});e.on("click",".showPassword",function(){l=!0});d.append(e);for(var D=a.site?a.site.getFormData(u):j.defaultData,z=e.find("[dialogFieldDisplay]"),t=0;t<z.length;++t){var A=z[t],B=D[A.getAttribute("dialogFieldDisplay")];
B&&(A.textContent=B)}c.tiles.push(this)};if(b.matchingSites)if(0===b.matchingSites.length)b.generatedPasswordSaved?(f.text(Strings.translateString("Nice! We've now added this to LastPass")),this.nextButton.text(Strings.translateString("Got it")),this.backButton.text(Strings.translateString("Undo")),new g({site:b.vaultItem})):this.setupAdd(b);else if(1===b.matchingSites.length)b.generatedPasswordSaved?(f.text(Strings.translateString("Nice! We've updated your password")),this.nextButton.text(Strings.translateString("Got it")),
this.backButton.LP_hide()):(f.text(Strings.translateString("Update password?")),this.nextButton.text(Strings.translateString("Update")),b.defaultData.unencryptedUsername||a.find(".addNewSiteButton").LP_show()),b.vaultItem=LPProxy.getSiteModel(b.matchingSites[0]),new g({site:b.vaultItem});else{for(h=0;h<b.matchingSites.length;++h)(new g({site:LPProxy.getSiteModel(b.matchingSites[h])})).setSelectable(!0);f.text(Strings.translateString("Which account should we update?"));b.defaultData.unencryptedUsername?
this.hasDuplicates()&&j.text(Strings.translateString("Choose one to update and delete the duplicate.")):a.find(".addNewSiteButton").LP_show();this.nextButton.text(Strings.translateString("Update"))}DialogWithGroupInput.prototype.setup.apply(this,arguments);this.inputFields.unencryptedUsername.setValues(LPProxy.getSiteUsernames());this.inputFields.unencryptedUsername.disableClickToggle()};SiteDialog.prototype.setSelectable=function(a){a?(this.$element.addClass("selectable"),this.nextButton.prop("disabled",
!0)):(this.$element.removeClass("selectable"),this.nextButton.prop("disabled",!1))};SiteDialog.prototype.validate=function(a){var b=DialogWithGroupInput.prototype.validate.apply(this,arguments);""===a.unencryptedUsername&&(this.addError("unencryptedUsername",Strings.translateString("Please enter a username.")),b=!1);return b};SiteDialog.prototype.getDialogActions=function(){};SiteDialog.prototype.close=function(a){bg.LPTabState.clear();DialogWithGroupInput.prototype.close.apply(this,arguments)};SiteDialog.prototype.saveGeneratedPassword=
function(a,b){var c;if(a.generatedPassword&&a.formSubmitted&&a.defaultData.unencryptedUsername)if(0===a.matchingSites.length)c=$.extend(k(a,void 0,void 0),a.dialogData),(new Account).addFromDialog(c,this.getGroup(c),{success:function(c){a.vaultItem=c;a.generatedPasswordSaved=!0;b()}});else if(1===a.matchingSites.length){var d=LPProxy.getSiteModel(a.matchingSites[0]);c=$.extend(k(a,d,void 0),a.dialogData);d.saveFromDialog(c,this.getGroup(c),{success:function(c){a.vaultItem=c;a.generatedPasswordSaved=
!0;b()}})}else b();else b()};SiteDialog.prototype.open=function(a){var b=this;this.saveGeneratedPassword(a,function(){var c=function(c){a.favicon=c;DialogWithGroupInput.prototype.open.call(b,a)};bg.LPIcons.get({url:a.defaultData.url,square:!0,callback:function(b){if(b)c(b);else{var f=function(){bg.LPPlatform.getFavicon({url:a.defaultData.url,callback:c})};a.sameDomain?csTop.LPContentScriptTools.getFavicon(function(a){a?c(a):f()}):f()}}})})};SiteDialog.prototype.adjustScrollHeight=function(a){this.scrollHeight&&
(this.scrollHeight+=a,this.tileContainer.css({"max-height":this.scrollHeight}))};SiteDialog.prototype.setInitialScrollHeight=function(){if(3<this.tiles.length){this.tileContainer=this.$element.find(".tileContainer");var a=this.tileContainer.height(),b=this.$element.find(".tile").first().height();this.scrollHeight=3.5*b+3*((a-b*this.tiles.length)/(this.tiles.length-1));this.tileContainer.css({overflow:"auto","max-height":this.scrollHeight})}};SiteDialog.prototype.showInitial=function(){var a=this;
a.requestAnimationFrame(function(b){a.show();a.setInitialScrollHeight();a.$element.addClass("animate-enter").one("animationend",function(){a.$element.removeClass("animate-enter");b()})})};var m=null,n=!1;SiteDialog.prototype.showInProcessOverlay=function(){if(this.submitted){var a=this.$element;a.addClass("inProcess").one("animationend",function(){a.addClass("waiting");setTimeout(function(){n=!0;m&&m()},500)})}};SiteDialog.prototype.hideInProcessOverlay=function(){this.$element.removeClass("inProcess waiting")};
SiteDialog.prototype.closeOnSuccess=function(){if(this.submitted){var a=this;a.$element.addClass("inProcess waiting");var b=function(){a.$element.removeClass("waiting").addClass("success").one("animationend.success",function(){setTimeout(function(){a.close()},500)})};n?b():m=function(){setTimeout(function(){b()},0)}}};SiteDialog.prototype.performValidate=function(a){var b=this;if(b.selectedTile)if(b.selectedTile===b.activeTile)b.activeTile.handleHeightChange({change:function(c){var f=a.callback;a.callback=
function(){var a=arguments;c({onFrameResizeComplete:function(){f&&f.apply(b,a)}})};DialogWithGroupInput.prototype.performValidate.call(b,a)}});else{var c=a.callback;a.callback=function(a){a||b.selectedTile.showDetails();c&&c.apply(this,arguments)};DialogWithGroupInput.prototype.performValidate.call(b,a)}};SiteDialog.prototype.getErrorOptions=function(){return{"static":!0,alignTop:!0,showErrorLabel:!1}};SiteDialog.prototype.submit=function(){1===this.tiles.length&&(this.selectedTile=this.tiles[0]);
this.selectedTile.preSubmit();DialogWithGroupInput.prototype.submit.apply(this,arguments);this.vaultItem?this.sendTrackingEvent("update"):this.sendTrackingEvent("add")};var s=function(a,b){for(var c=0;c<a.length;++c){var d=a[c];if(d.value===b)return d}return null};SiteDialog.prototype.handleSubmit=function(a){this.submitted=!0;if(a.fields&&(a.fields.forEach(function(b){this.data.defaultData.unencryptedUsername&&this.data.defaultData.unencryptedUsername===b.value?b.value=a.unencryptedUsername:this.data.dialogData.password&&
this.data.dialogData.password===b.value&&(b.value=a.password)},this),a.save_all)){var b=this.vaultItem.getFormData({password:!0,unencryptedUsername:!0,fields:!0});b.fields&&b.fields.forEach(function(c){var d;b.unencryptedUsername&&b.unencryptedUsername===c.value?(c.value=a.unencryptedUsername,(d=s(a.fields,a.unencryptedUsername))&&d.name!==c.name&&b.fields.push(d)):b.password&&b.password===c.value&&(c.value=a.password,(d=s(a.fields,a.password))&&d.name!==c.name&&b.fields.push(d))});a.fields=b.fields;
this.data.saveOptions.saveFromSubmit=!1}DialogWithGroupInput.prototype.handleSubmit.apply(this,arguments)}})();
