DialogInput=function(){var v=function(a){var b={},d;for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]instanceof k?v(a[d]):!0);return b},k=function(){};k.prototype.validate=function(){var a=!0,b;for(b in this)this.hasOwnProperty(b)&&(a=this[b].validate()&&a);return a};k.prototype.clear=function(){for(var a in this)this.hasOwnProperty(a)&&this[a].clear()};k.prototype.clearErrors=function(){for(var a in this)this.hasOwnProperty(a)&&this[a].clearErrors()};k.prototype.adjustView=function(){for(var a in this)if(this.hasOwnProperty(a)){var b=
this[a];"function"===typeof b.adjustView&&b.adjustView()}};k.prototype.getValue=function(a){var b={},d;for(d in this)this.hasOwnProperty(d)&&(b[d]=this[d].getValue(a));return b};k.prototype.setValue=function(a){for(var b in this)this.hasOwnProperty(b)&&this[b].setValue(void 0===a[b]?"":a[b])};k.prototype.hasError=function(){for(var a in this)if(this.hasOwnProperty(a)&&this[a].hasError())return!0;return!1};var s=function(a){this.items={};this.groupName=a};s.prototype.getValue=function(){for(var a in this.items)if(this.items[a].prop("checked"))return a};
s.prototype.setValue=function(a){if(a=this.items[a])a.prop("checked",!0);else for(var b in this.items)this.items[b].prop("checked",!1)};s.prototype.addRadioInput=function(a){var b=a.attr("value");if(b){if(a.attr("name")!==this.groupName)throw"RadioGroup member must have the same name attribute as the other radio inputs in the group (based on dialogField)!";this.items[b]=a}else throw"RadioGroup member must have a value!";};var e=function(){this._errors=[];this._errorOptions=this._errorContainer=null;
this._hasError=!1};e.prototype.postValidate=function(){(this._hasError=0<this._errors.length)&&this._errorContainerWrapper.find("input,select,textarea").bind("focus",this.focusHandler).bind("blur",this.blurHandler).bind("change",this.changeHandler)};e.prototype.hasError=function(){return this._hasError};e.prototype.buildError=function(){var a=this.getElement(),b={element:a,alignTop:"SELECT"===this.input.prop("nodeName").toUpperCase()};"checkbox"===a.attr("type")&&(b.element=b.element.add(a.next()),
b.static=!0);return this.buildErrorElement(b)};e.prototype.buildErrorElement=function(a){this._errorOptions=a=$.extend(this.getDialog().getErrorOptions(),a);var b=this._errorContainerWrapper=$(LPTools.createElement("div","relative"));this._errorContainer=$(LPTools.createElement("div","dialogErrorContainer"));a.element.before(b);a.static&&b.addClass("staticError");a.alignTop&&this._errorContainer.addClass("alignTop");a.static&&!a.alignTop?(b.append(a.element),b.append(this._errorContainer)):(b.append(this._errorContainer),
b.append(a.element));var d=this.getDialog();this.focusHandler=function(){b.addClass("focus")};this.blurHandler=function(){b.removeClass("focus")};this.changeHandler=function(){d.performValidate({data:d.getData(),errorsOnly:!0})}};e.prototype.addError=function(a,b){b=this.dialog=this.getDialog()||b;if(!this.disabled&&!LPTools.getOption(b.validateOptions,"errorsOnly",!1)||this.hasError())this._hasError=!0,this._errors.push(a),this.buildErrorMessage()};e.prototype.clearErrors=function(){this._errors=
[];this._errorContainer&&(this._errorContainer.empty(),this._errorContainerWrapper.removeClass("error"),this._errorContainerWrapper.find("input,select,textarea").unbind("focus",this.focusHandler).unbind("blur",this.blurHandler).unbind("change",this.changeHandler))};e.prototype.clear=function(){this._hasError=!1};e.prototype.adjustView=function(){};e.prototype.buildErrorMessage=function(){this._errorContainer||this.buildError();this._errorContainerWrapper.addClass("error");this._errors.forEach(function(a){var b=
LPTools.createElement("div","dialogError");b.appendChild(LPTools.createElement("div","validation-img warning"));LPTools.getOption(this._errorOptions,"showErrorLabel",!0)&&b.appendChild(LPTools.createElement("span","errorLabel",Strings.translateString("ERROR")+": "));b.appendChild(LPTools.createElement("span","",a));this._errorContainer.append(b)},this)};e.prototype.getDialog=function(){return this.dialog};e.prototype.getElement=function(){return this.input};var c=function(a,b){e.call(this);this.setElement(a);
this.disabled=!1;this.dialog=b;this.radioGroup=null};c.prototype=Object.create(e.prototype);c.prototype.constructor=c;c.prototype.getNativeElement=function(){return this.getElement().get(0)};c.prototype.setElement=function(a){this.input=a instanceof $?a:$(a)};c.prototype.default=function(){this.setValue("")};c.prototype.validate=function(){return!0};c.prototype.focus=function(){this.input.focus()};c.prototype.disable=function(){this.disabled||(this.disabled=!0,this.input.prop("disabled",!0))};c.prototype.enable=
function(){this.disabled&&(this.disabled=!1,this.input.prop("disabled",!1))};c.prototype.clear=function(){e.prototype.clear.apply(this,arguments);if(this.input){switch(this.input.attr("type")){case "checkbox":case "radio":this.setValue(!1);break;default:this.setValue("")}this.input.passwordShown&&this.input.hidePassword()}};c.prototype.getValue=function(){switch(this.input.attr("type")){case "radio":if(this.radioGroup)return this.radioGroup.getValue();case "checkbox":return this.input.prop("checked");
default:return this.input.val()||""}};c.prototype.setValue=function(a){var b=this.getValue();switch(this.input.attr("type")){case "radio":if(this.radioGroup)return this.radioGroup.setValue(a);case "checkbox":this.input.prop("checked",a);break;default:this.input.val(a)}b!==a&&this.fireOnChange()};c.prototype.addRadioInput=function(a,b){null===this.radioGroup&&(this.radioGroup=new s(a),this.radioGroup.addRadioInput(this.input));this.radioGroup.addRadioInput(b instanceof $?b:$(b))};c.prototype.fireOnChange=
function(){if(this.onChangeCallback)this.onChangeCallback(this.getValue())};c.prototype.onChange=function(a){this.onChangeCallback=a;var b=this;b.getElement().bind("change",function(){b.fireOnChange()})};var q=function(a,b){c.apply(this,arguments)};q.prototype=Object.create(c.prototype);q.prototype.constructor=q;q.prototype.setOptions=function(a){this.input.empty();for(var b=0,d=a.length;b<d;++b){var c=a[b],e=c.value,f=c.label;"string"===typeof c&&(e=f=c);this.input.append(LPTools.createElement("option",
{value:e},f))}};var f=function(a,b){c.call(this);this.field=a;this.label=void 0===b?a:b?Strings.translateString(b):null};f.prototype=Object.create(c.prototype);f.prototype.constructor=f;f.prototype.build=function(){var a="settingLabel";this.isTopAlign()&&(a+=" topAlign");var b=LPTools.createElement("tr"),d=LPTools.createElement("td");this.label&&b.appendChild(LPTools.createElement("td",a,this.label));b.appendChild(d);d.appendChild(this.buildInput());return b};f.prototype.buildInput=function(){var a=
this.buildInputElement();this.setElement(a);return a};f.prototype.isTopAlign=function(){return!1};var m=function(a,b,d){f.call(this,a,b);this.options=d};m.prototype=Object.create(f.prototype);m.prototype.constructor=m;m.prototype.buildInputElement=function(){return LPTools.createElement("input",{"class":"dialogInput",type:"text"})};m.prototype.buildInput=function(){var a=f.prototype.buildInput.apply(this,arguments),b=LPTools.getOption(this.options,"inputButton",null);if(b){var d=LPTools.createElement("div",
"relative");d.appendChild(a);this.inputButtonElement=LPTools.createElement("button","dialogInputButton",b);var c=LPTools.getOption(this.options,"inputButtonHandler",null);if(c){var e=this;LPPlatform.addEventListener(e.inputButtonElement,"click",function(){c.apply(e)})}d.appendChild(this.inputButtonElement);return d}return a};m.prototype.adjustView=function(){if(this.inputButtonElement){var a=parseInt(this.input.css("padding-right"));this.input.css("padding-right",a+$(this.inputButtonElement).outerWidth())}};
var r=function(a,b){f.call(this,a,b)};r.prototype=Object.create(f.prototype);r.prototype.constructor=r;r.prototype.buildInput=function(){this.setElement(LPTools.createElement("input",{"class":"dialogInput",type:"password"}));this.input.LP_addPasswordEye({includeGenerateButton:!0});var a=this.input.parents();return a[a.length-1]};var p=function(a,b){f.call(this,a,b)};p.prototype=Object.create(f.prototype);p.prototype.constructor=p;p.prototype.buildInputElement=function(){return LPTools.createElement("textarea",
"dialogInput")};p.prototype.isTopAlign=function(){return!0};for(var n="January February March April May June July August September October November December".split(" "),l="01 02 03 04 05 06 07 08 09 10 11 12".split(" "),h=[],g=0,t=n.length;g<t;++g){var u=g+1;h.push((10>u?"0"+u:u)+" - "+Strings.translateString(n[g]))}for(var w=[{value:"",label:""}],g=0,t=n.length;g<t;++g)w.push({value:n[g],label:h[g]});for(var x=[{value:"",label:""}],g=0,n=n.length;g<n;++g)x.push({value:l[g],label:h[g]});var j=function(a,
b){f.call(this,a,LPTools.getOption(b,"label",void 0));this.includeDay=LPTools.getOption(b,"includeDay",!0)};j.prototype=Object.create(f.prototype);j.prototype.constructor=j;j.prototype.buildInputElement=function(){var a="";this.includeDay||(a="monthYearDate");var a=LPTools.createElement("div",a),b=LPTools.createElement("div","dateInputMonth");this.monthInput=LPTools.createSelectElement(this.getMonthOptions());this.dayInput=null;this.includeDay&&(this.dayInput=LPTools.createElement("input",{"class":"dialogInput dateInputDay",
type:"text"}));this.yearInput=LPTools.createElement("input",{"class":"dialogInput dateInputYear",type:"text"});b.appendChild(this.monthInput);a.appendChild(b);null!==this.dayInput&&a.appendChild(this.dayInput);a.appendChild(this.yearInput);return a};j.prototype.clear=function(){this.monthInput&&(this.monthInput.value="");this.dayInput&&(this.dayInput.value="");this.yearInput&&(this.yearInput.value="")};j.prototype.getValue=function(){return this.toString()};j.prototype.setValue=function(a){a=this.parse(a);
var b="",c="",e="";a&&(b=a.shift(),2===a.length&&(c=a.shift()),e=a.shift());this.monthInput.value=b;this.includeDay&&(this.dayInput.value=c);this.yearInput.value=e};l=function(a,b){j.call(this,a,b)};l.prototype=Object.create(j.prototype);l.prototype.constructor=l;l.prototype.toString=function(){var a=this.monthInput.value;this.dayInput&&(a+=","+this.dayInput.value);return a+=","+this.yearInput.value};l.prototype.parse=function(a){return a?a.split(","):null};l.prototype.getMonthOptions=function(){return w};
h=function(a,b){j.call(this,a,b)};h.prototype=Object.create(j.prototype);h.prototype.constructor=h;h.prototype.toString=function(){var a=this.yearInput.value+"-"+this.monthInput.value;this.includeDay&&(a+="-"+this.dayInput.value);if("-"===a||"--"===a)a="";return a};h.prototype.parse=function(a){return a?(a=a.split("-"),a.push(a.shift()),a):null};h.prototype.getMonthOptions=function(){return x};return{ErrorDisplayInput:e,Input:c,TextInput:m,PasswordInput:r,TextArea:p,NumericDateInput:h,AlphaDateInput:l,
NestedFields:k,NativeSelect:q,getProperties:v}}();
