function LP_humanizeClick(a,b,c){!a&&b&&(a=b.ownerDocument);a||(a=LP_derive_doc());if(!a)return!1;c||(c={});b||(b=a.body);var d=0;g_isie&&(init_LPfn()&&LPfn)&&(d=LPfn.getDocumentMode(a));var e=0,e="undefined"!=typeof c.button?c.button:g_isie&&8>=d?1:0;if("undefined"!=typeof c.posx&&"undefined"!=typeof c.posy)d=c.posx,a=c.posy;else if(d=LP_getAbsolutePos(a,b))a=(d.top+d.height)/2,d=(d.left+d.width)/2;else return!1;if(isNaN(d)||isNaN(a))return!1;e={evt_class:"MouseEvent",button:e,posx:d,posy:a};"undefined"!=
typeof c.dofocus&&c.dofocus&&b.focus();LP_fireEvent(b,"mousedown","MouseEvent",e);LP_fireEvent(b,"mouseup","MouseEvent",e);LP_fireEvent(b,"click","MouseEvent",e);return!0}function LP_humanizeMoveTo(){}var g_draggable=!0,g_is_dragging=!1,g_drag_lastX=null,g_drag_lastY=null,g_pos_delx=0,g_pos_dely=0,LP_DRAG_NODRAG=0,LP_DRAG_MOVE=1,LP_DRAG_RESIZE=2,g_drag_type=LP_DRAG_NODRAG;function LP_dropHandler(){}function LP_dragoverHandler(){}function LP_dragHandler(){}function LP_mousemoveHandler(){}
function LP_mousedownHandler(a){a||(a=window.event);if(g_draggable&&g_in_lpframe){var b=LP_getEventTarget(a);a=LP_getMousePos(a);if(b&&a)switch(b.id){case "superbox":case "superbox_savesite_txt":case "superbox_emptymsg_txt_span":case "superbox_savesite_txt_span":case "SB_iconbox":case "SB_titlebox":g_is_dragging=!0;g_drag_type=LP_DRAG_MOVE;a&&(g_drag_lastX=a.x,g_drag_lastY=a.y);break;case "resize_button":g_is_dragging=!0,g_drag_type=LP_DRAG_RESIZE,a&&(g_drag_lastX=a.x,g_drag_lastY=a.y)}}}
function LP_mouseupHandler(a){a||(a=window.event);var b=0,c=0;if(g_draggable&&g_is_dragging&&g_in_lpframe){if((a=LP_getMousePos(a))&&null!==g_drag_lastX&&null!==g_drag_lastY)b=a.x-g_drag_lastX,c=a.y-g_drag_lastY,g_drag_lastX=a.x,g_drag_lastY=a.y;switch(g_drag_type){case LP_DRAG_MOVE:g_isie?ie_moveIframe({delx:b,dely:c}):g_isfirefox||cr_moveIframe({delx:b,dely:c});break;case LP_DRAG_RESIZE:g_isie?ie_resizeIframe({delx:b,dely:c}):g_isfirefox||0!=b&&0!=c&&cr_resizeIframe({delx:b,dely:c});break;default:verbose&&
alert("UNEXPECTED DRAG"+g_drag_type)}g_is_dragging=!1;g_drag_type=LP_DRAG_NODRAG}}function LP_mouseleaveHandler(a){if(g_in_lpframe&&LP_getEventTarget(a)==doc.body){if((a=LP_getMousePos(a))&&null!==g_drag_lastX&&null!==g_drag_lastY)delx=a.x-g_drag_lastX,dely=a.y-g_drag_lastY,g_drag_lastX=a.x,g_drag_lastY=a.y;g_isie?ie_moveIframe({delx:delx,dely:dely}):g_isfirefox||cr_moveIframe({delx:delx,dely:dely});g_is_dragging=!1}}
function LP_addEventHandler(a,b,c){try{if(null==a||null==b||null==c||0>=b.length)return null;if("click"==b||"mousedown"==b||"mouseup"==b||"focus"==b){var d=c;c=function(a){try{if("undefined"!=typeof a.isTrusted&&!a.isTrusted)return!0}catch(b){}return d(a)}}return"undefined"!=typeof a.addEventListener?(a.addEventListener(b,c,!1),c):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+b,c):null}catch(e){return verbose_log("LP_addEventHandler failed, "+e.message),null}}
function LP_stopEventPropagation(a){try{"undefined"!=typeof a.preventDefault?a.preventDefault():typeof window.event&&(window.event.returnValue=!1),"undefined"!=typeof a.stopPropagation?a.stopPropagation():typeof window.event&&(window.event.cancelBubble=!0)}catch(b){verbose_log("LP_stopEventPropagation failed, "+b.message)}}
function LP_getEventTarget(a){a=a?a:window.event;if("undefined"==typeof a)return null;if((a="undefined"!=typeof a.target?a.target:a.srcElement)&&"undefined"!=typeof a.nodeType&&3==a.nodeType)a=a.parentNode;return a}
function LP_getMousePos(a){var b;a=a||window.event;b=LP_getEventTarget(a).ownerDocument;if(!b||null==b.location||0<b.location.href.indexOf(".xul"))return{x:0,y:0};var c=b.documentElement,d=typeof("number"==c.scrollLeft)?c.scrollLeft:b.body.scrollLeft,e=typeof("number"==c.scrollTop)?c.scrollTop:b.body.scrollTop,f=c=0;if(g_bodystyle_relative&&!g_in_lpframe){var h=LP_get_cached_body_rect(b),l=LP_get_cached_body_style(b);h&&(l&&"relative"==l.position)&&(f=h.left,c=h.top)}g_isie&&(g_in_lpframe?verbose&&
alert("TODO"):(h=LP_get_cached_body_rect(b),e="undefined"!=typeof window&&window?window:b.defaultView,"pageXOffset"in e?(d=e.pageXOffset,b=e.pageYOffset):(d=1,"undefined"!=typeof g_isie&&g_isie&&"undefined"!=typeof b.querySelector&&"undefined"==typeof b.addEventListener?h=1:(h&&(d=Math.round(100*((h.right-h.left)/b.body.offsetWidth))/100),h=d),d=Math.round(b.documentElement.scrollLeft/h),b=Math.round(b.documentElement.scrollTop/h)),e=b));b=a.pageX||a.clientX+d;a=a.pageY||a.clientY+e;b=parseInt(b);
a=parseInt(a);g_bodystyle_relative&&(b-=f,a-=c);return{x:b,y:a}}
if("undefined"==typeof KeyEvent)var KeyEvent={DOM_VK_CANCEL:3,DOM_VK_HELP:6,DOM_VK_BACK_SPACE:8,DOM_VK_TAB:9,DOM_VK_CLEAR:12,DOM_VK_RETURN:13,DOM_VK_ENTER:14,DOM_VK_SHIFT:16,DOM_VK_CONTROL:17,DOM_VK_ALT:18,DOM_VK_PAUSE:19,DOM_VK_CAPS_LOCK:20,DOM_VK_ESCAPE:27,DOM_VK_SPACE:32,DOM_VK_PAGE_UP:33,DOM_VK_PAGE_DOWN:34,DOM_VK_END:35,DOM_VK_HOME:36,DOM_VK_LEFT:37,DOM_VK_UP:38,DOM_VK_RIGHT:39,DOM_VK_DOWN:40,DOM_VK_PRINTSCREEN:44,DOM_VK_INSERT:45,DOM_VK_DELETE:46,DOM_VK_0:48,DOM_VK_1:49,DOM_VK_2:50,DOM_VK_3:51,
DOM_VK_4:52,DOM_VK_5:53,DOM_VK_6:54,DOM_VK_7:55,DOM_VK_8:56,DOM_VK_9:57,DOM_VK_SEMICOLON:59,DOM_VK_EQUALS:61,DOM_VK_A:65,DOM_VK_B:66,DOM_VK_C:67,DOM_VK_D:68,DOM_VK_E:69,DOM_VK_F:70,DOM_VK_G:71,DOM_VK_H:72,DOM_VK_I:73,DOM_VK_J:74,DOM_VK_K:75,DOM_VK_L:76,DOM_VK_M:77,DOM_VK_N:78,DOM_VK_O:79,DOM_VK_P:80,DOM_VK_Q:81,DOM_VK_R:82,DOM_VK_S:83,DOM_VK_T:84,DOM_VK_U:85,DOM_VK_V:86,DOM_VK_W:87,DOM_VK_X:88,DOM_VK_Y:89,DOM_VK_Z:90,DOM_VK_WIN:91,DOM_VK_CONTEXT_MENU:93,DOM_VK_NUMPAD0:96,DOM_VK_NUMPAD1:97,DOM_VK_NUMPAD2:98,
DOM_VK_NUMPAD3:99,DOM_VK_NUMPAD4:100,DOM_VK_NUMPAD5:101,DOM_VK_NUMPAD6:102,DOM_VK_NUMPAD7:103,DOM_VK_NUMPAD8:104,DOM_VK_NUMPAD9:105,DOM_VK_MULTIPLY:106,DOM_VK_ADD:107,DOM_VK_SEPARATOR:108,DOM_VK_SUBTRACT:109,DOM_VK_DECIMAL:110,DOM_VK_DIVIDE:111,DOM_VK_F1:112,DOM_VK_F2:113,DOM_VK_F3:114,DOM_VK_F4:115,DOM_VK_F5:116,DOM_VK_F6:117,DOM_VK_F7:118,DOM_VK_F8:119,DOM_VK_F9:120,DOM_VK_F10:121,DOM_VK_F11:122,DOM_VK_F12:123,DOM_VK_F13:124,DOM_VK_F14:125,DOM_VK_F15:126,DOM_VK_F16:127,DOM_VK_F17:128,DOM_VK_F18:129,
DOM_VK_F19:130,DOM_VK_F20:131,DOM_VK_F21:132,DOM_VK_F22:133,DOM_VK_F23:134,DOM_VK_F24:135,DOM_VK_NUM_LOCK:144,DOM_VK_SCROLL_LOCK:145,DOM_VK_COMMA:188,DOM_VK_PERIOD:190,DOM_VK_SLASH:191,DOM_VK_BACK_QUOTE:192,DOM_VK_OPEN_BRACKET:219,DOM_VK_BACK_SLASH:220,DOM_VK_CLOSE_BRACKET:221,DOM_VK_QUOTE:222,DOM_VK_META:224};
function is_modifier_key(a){if("undefined"!=typeof KeyEvent){if(a==KeyEvent.DOM_VK_ALT||a==KeyEvent.DOM_VK_SHIFT||a==KeyEvent.DOM_VK_CONTROL||a==KeyEvent.DOM_VK_WIN||a==KeyEvent.DOM_VK_META)return!0}else if(16==a||17==a||18==a||91==a||92==a||224==a)return!0;return!1}var KEY_ESCAPE=27;
function LP_keypress_handler(a){a||(a=window.event);var b="undefined"!=typeof document?document:a&&a.target?a.target.ownerDocument:null;if(!b||!b.location||!a)return!1;a=a.keyCode;verbose_log("received key "+a);a==KEY_ESCAPE&&is_your_popup_showing(b)&&closepopupfills(b);return!1}var KEY_TAB=9,KEY_UP=38,KEY_DOWN=40,KEY_ENTER=13,KEY_SHIFT=16,KEY_RIGHT=39,KEY_LEFT=37,KEY_PAGEDOWN=34,KEY_PAGEUP=33,KEY_END=35,KEY_HOME=36;
function LP_field_keypress_handler(a,b,c,d){a||(a=window.event);if(LP_getloggedin()){d||(d="undefined"!=typeof document?document:a&&a.target?a.target.ownerDocument:null);if(!d||null==d.location)if(d=b.ownerDocument,g_isfirefox&&void 0!=typeof LP&&(!d||null==d.location))d="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument;if(d){if(null==d.location)return verbose_log("LP_field_keypress_handler given a firefox zombie document?"),
a="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument,closepopupfills(a),!1;reset_lpsaveforminfo_vars(d);c=a.keyCode;if(c==KEY_ESCAPE)is_your_popup_showing(d)&&closepopupfills(d);else if(c==KEY_TAB)a.shiftKey||is_your_popup_showing(d)&&closepopupfills(d);else if(c==KEY_DOWN){if(!is_your_popup_showing(d)){set_active_username_password(d,b.form);"undefined"!=typeof g_isie&&g_isie&&"undefined"!=typeof init_LPfn&&(init_LPfn()&&
LPfn)&&LPfn.ie_set_kbdnav(!0);var e=LP_pickFieldName(d,b);if(e=getIconState(d,e)){var f=!1,h=!1;"generate"==e.fillhint&&(f=!0);"formfills"==e.fillhint&&(h=!0);popuptoggle(d,null,e.idorname,f,FORCE_SHOW_NOHITS,!1,h,e.fillhint,e.fillhintnumber)}else LP_pickFieldName(d,b),popuptoggle(d,null,LP_pickFieldName(d,b),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS)}}else if(c!=KEY_UP&&!(c==KEY_SHIFT||0==c)&&!(c==KEY_RIGHT&&a.altKey)&&!is_modifier_key(c)&&c!=KEY_ENTER){if(g_ischrome&&g_setup_hotkey_handler){if(is_hotkey_event(a))return}else if(g_isie){if(e=
""+(a.ctrlKey?"control ":""),e+=a.metaKey?"meta ":"",e+=a.altKey?"alt ":"",e+=a.shiftKey?"shift ":"",verbose_log("keycode == "+c+" "+e),"undefined"!=typeof a.metaKey&&a.metaKey||"undefined"!=typeof a.altKey&&a.altKey||"undefined"!=typeof a.ctrlKey&&a.ctrlKey)return}else if(g_isfirefox&&(e=""+(a.ctrlKey?"control ":""),e+=a.metaKey?"meta ":"",e+=a.altKey?"alt ":"",e+=a.shiftKey?"shift ":"",verbose_log("keycode == "+c+" "+e),is_hotkey_event(d,a)))return;if("password"==b.type&&formHasUsernameField(b))if(g_clickable_input_on_password)!is_your_popup_showing(d)&&
!chk_form_ask_generate(d,b.form)&&conditional_create_popup(d,b,FORCE_SHOW_NOHITS_NOLOGIN);else return;if(!chk_form_has_password(d,b.form))return;is_your_popup_showing(d)||(g_clickable_input_on_password?(e=getIconState(d,LP_pickFieldName(d,b)))&&(e.fillhint&&"sites"==e.fillhint)&&conditional_create_popup(d,b,FORCE_SHOW_NOHITS_NOLOGIN):(LP_pickFieldName(d,b),popuptoggle(d,null,LP_pickFieldName(d,b),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS)),g_keyboardNav=!0)}if(is_your_popup_showing(d)){c==KEY_UP&&(g_isfirefox?
ff_do_popupfocusdecrement(1):g_isie||sendBG({cmd:"popupfillinputfocusdecrement",count:1}),g_keyboardNav=!0,g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),LP_stopEventPropagation(a));c==KEY_DOWN&&(g_extended_kbd_nav&&a.altKey?is_your_popup_showing(d)&&!g_isfirefox&&(g_isie||sendBG({cmd:"popupfillinputshownavbar"})):(g_isfirefox?ff_do_popupfocusincrement(1):g_isie||sendBG({cmd:"popupfillinputfocusincrement",count:1}),g_keyboardNav=!0),g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),LP_stopEventPropagation(a));
if(c==KEY_ENTER&&(verbose_log("Enter Received, checking field"),(g_isfirefox?d.g_popupfill_parent:g_popupfill_parent)==b&&g_keyboardNav))g_isfirefox?(verbose_log("Enter Received, Choose Action"),ff_do_popupfocuschoose(!0)):g_isie||sendBG({cmd:"popupfillinputfocuschoose"}),g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),g_isfirefox&&is_hotkey_event(d,a),LP_stopEventPropagation(a);c==KEY_PAGEUP&&(g_isfirefox?ff_do_popupfocusdecrement(12):g_isie||sendBG({cmd:"popupfillinputfocusdecrement",count:12}),
g_keyboardNav=!0,g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),g_isfirefox&&is_hotkey_event(d,a),LP_stopEventPropagation(a));c==KEY_PAGEDOWN&&(g_isfirefox?ff_do_popupfocusincrement(12):g_isie||sendBG({cmd:"popupfillinputfocusincrement",count:12}),g_keyboardNav=!0,g_ischrome&&g_setup_hotkey_handler&&handle_hotkey(a),g_isfirefox&&is_hotkey_event(d,a),LP_stopEventPropagation(a));c==KEY_END&&(g_isfirefox?ff_do_popupfocusincrement(1073741824):g_isie||sendBG({cmd:"popupfillinputfocusincrement",count:1073741824}),
g_keyboardNav=!0);c==KEY_HOME&&(g_isfirefox?ff_do_popupfocusdecrement(1073741824):g_isie||sendBG({cmd:"popupfillinputfocusdecrement",count:1073741824}),g_keyboardNav=!0)}return!1}}}function LP_didFieldClickEvent(a,b){return!a||!b?!1:1==(LP_getBits(a,b)&1)}function LP_didFieldMouseEvent(a,b){return!a||!b?!1:2==(LP_getBits(a,b)&2)}function LP_didFieldKeyEvent(a,b){return!a||!b?!1:4==(LP_getBits(a,b)&4)}
function LP_didDocumentEscapeEvent(a){if(!a)return!1;var b=a.body;null==b&&(b=a.documentElement);return 8==(LP_getBits(a,b)&8)}function LP_setFieldClickEvent(a,b){if(!a||!b)return!1;var c=LP_getBits(a,b);LP_setBits(a,b,c|1);return!0}function LP_setFieldMouseEvent(a,b){if(!a||!b)return!1;var c=LP_getBits(a,b);LP_setBits(a,b,c|2);return!0}function LP_setFieldKeyEvent(a,b){if(!a||!b)return!1;var c=LP_getBits(a,b);LP_setBits(a,b,c|4);return!0}
function LP_setBits(a,b,c){if(!a||!b)return!1;if("undefined"==typeof c||null===c)c=0;if(g_isie){if(init_LPfn()&&LPfn)return LPfn.ie_set_lpstates(b,c)}else b=LP_pickFieldName(a,b),verbose_log("lpsetbits "+b+" = "+c),a.lpstates[b]=c;return!0}
function LP_getBits(a,b){if(!a||!b)return 0;var c=0;if(g_isie)init_LPfn()&&LPfn&&(c=LPfn.ie_get_lpstates(b));else{a.lpstates||(a.lpstates={});var c=a.lpstates,d=LP_pickFieldName(a,b);verbose_log("lpstates for "+d+" == "+c[d]);c="undefined"!=typeof c[d]?c[d]:0}return c}function LP_setDocumentEscapeEvent(a){if(!a)return!1;var b=a.body;null==b&&(b=a.documentElement);var c=LP_setBits(a,b);return LP_setBits(a,b,c|8)}
function LP_resetAllBits(a){if(!a)return!1;if(g_isie){if(init_LPfn()&&LPfn)return LPfn.ie_reset_lpstates()}else return a.lpstates={},!0;return!1}
function lp_docinfoFromEvent(a){var b=null,b="undefined"!=typeof LP&&"function"==typeof LP.lpGetCurrentWindow?"undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument:g_isfirefox?top.document:document,c=null,d=LP_getEventTarget(a).ownerDocument;if(d!=b){c=d;try{verbose&&(c&&c.location)&&verbose_log("click inside iframe "+c.location.href)}catch(e){pass}}a=LP_getEventTarget(a);var f=LP_pickFieldName(d,a);return{topdoc:b,
framedoc:c,eventdoc:d,target:a,targetname:f}}
function icon_click_handler(a){var b,c=lp_docinfoFromEvent(a),d=c.topdoc,e=c.framedoc,f=c.eventdoc,h=c.target,l=c.targetname,n=!1,j=LP_getMousePos(a);if(0>=j.x&&0>=j.y){if(f&&f.location&&f.location.href&&0<f.location.href.indexOf(".xul"))return!0}else{try{d&&d.body&&d.body.getAttribute("data-fouc-class-names")&&0<=d.body.getAttribute("data-fouc-class-names").indexOf("swift-loading")&&(0<getAllIconStates().length?refresh_input_all_icon_bg(d):window&&window.setTimeout(function(){g_input_cnt=-1;doc_create_clickable_icons(d,
"",SHOULD_DO_ALWAYS,g_is_specialsite)},50))}catch(q){}b=getAllIconStates();var k;for(k=0;k<b.length;k++){c=null;f=b[k];if(g_isfirefox&&f.inframe)if(e)(c=b[k].IHTMLElement)||(c=LP_getElementByIdOrName(e,f.idorname));else{if(c=b[k].IHTMLElement)e=c.ownerDocument}else if(""!=l&&l==f.idorname){if(h!=b[k].IHTMLElement){for(var g=!1,c=k;c<b.length;c++)if(h==b[c].IHTMLElement){g=!0;break}if(g)continue;else if(h&&b[k].IHTMLElement&&(h.tagName!=b[k].IHTMLElement.tagName||h.type!=b[k].IHTMLElement.type)){verbose_log("page click name/id collision");
continue}}c=h}else(c=b[k].IHTMLElement)?b[k].dofloater?l==LPMAGIC+f.idorname||l==LPMAGIC+f.idorname+"_icon"||l==LPMAGIC+f.idorname+"_numspan"?(c=b[k].IHTMLElement)||(c=LP_getElementByIdOrName(d,f.idorname)):pass:c!==h&&(c=null):(c=LP_getElementByIdOrName(d,f.idorname))&&!popupfill_shoulddofield(d,c,SHOULD_DO_ALWAYS)&&(c=null);if(e){if(c&&checkIsDisplayed(e,c,0))if(g=LP_getAbsolutePos(e,c),!g||0>=g.width&&0>=g.height)verbose_log("skipping field "+f.idorname+" : no valid position");else{var m=!1;if(f.text_direction==
m)var m=g.left,p=g.left+20;else m=g.left+g.width-20,p=g.left+g.width,m<g.left&&(m=g.left);if(m<j.x&&p>j.x&&g.top<j.y&&g.top+g.height>j.y){h=!1;l=!0;j=n=!1;verbose_log("icon_click_handler calling popuptoggle() [iframe]");"generate"==f.fillhint?h=!0:f.no_check_generate||(h=shouldOfferGenerate(e,c));"formfills"==f.fillhint&&(j=!0);d.g_popupfill_parent=c;popuptoggle(d,e,f.idorname,h,l,n,j,f.fillhint,f.fillhintnumber);n=!0;LP_stopEventPropagation(a);break}}}else if(c&&checkIsDisplayed(d,c,0))if("INPUT"==
c.nodeName&&("checkbox"==c.type||"radio"==c.type))verbose_log("skipping field "+f.idorname+" : is not text-like");else if(g=LP_getAbsolutePos(d,c),!g||0>=g.width&&0>=g.height)verbose_log("skipping field "+f.idorname+" : no valid position");else{m=!1;f.text_direction==m?(m=g.left,p=g.left+20):(m=g.left+g.width-20,p=g.left+g.width,m<g.left&&(m=g.left));var r=!1;if(r=LP_getloggedin()&&bg.get("LPContentScriptFeatures").is_infield_enabled&&bg.get("LPContentScriptFeatures").is_infield_autopopup_enabled&&
0<f.fillhintnumber&&1===g_pref_infieldPopupEnabled?"focus"===a.type||m<j.x&&p>j.x&&g.top<j.y&&g.top+g.height>j.y:m<j.x&&p>j.x&&g.top<j.y&&g.top+g.height>j.y){h=!1;l=!0;j=n=!1;"generate"==f.fillhint?(h=!0,f.fillhintnumber||(f.fillhintnumber=1)):f.no_check_generate||(h=shouldOfferGenerate(d,c));"formfills"==f.fillhint&&(j=!0);d.g_popupfill_parent=c;popuptoggle(d,e,f.idorname,h,l,n,j,f.fillhint,f.fillhintnumber,c);n=!0;LP_stopEventPropagation(a);break}}else verbose_log("skipping field "+f.idorname+" : not found/visible")}return n}}
function onresize_handler(a){a="undefined"!=typeof document?document:a.target.document;var b=a.getElementsByTagName("body")[0];a.g_posbodyrect_cache=b.getBoundingClientRect();var c="undefined"!=typeof window&&window?window:a.defaultView;a.g_posbodystyle_cache=c&&"undefined"!=typeof c.getComputedStyle?c.getComputedStyle(b,null):b.currentStyle;popupfill_resize(a);return!1}
function handle_form_text_change(a,b,c,d){if(do_experimental_popupfill){if(!a&&(a=LP_derive_doc(),!a))return null;a&&b&&popupfill_shoulddofield(a,b,SHOULD_DO_ALWAYS)&&should_track_field_onkeyup(b)&&update_preobfuscate_field_value(b);if(!(null==c||null==b||null==d||null==d.keyCode||0==d.keyCode|16==d.keyCode))if((!c||popupfill_shoulddoform(a,c))&&popupfill_shoulddofield(a,b,SHOULD_DO_ALWAYS)){var e=b.value,f=LP_pickFieldName(a,b);if(g_clickable_input_on_password){var h=g_popup_active_username,l=g_popup_active_password;
null==h&&(h="undefined"==typeof b.form||null==b.form?doc_get_orphan_username(a):form_get_username(a,b.form));null==l&&(l="undefined"==typeof b.form||null==b.form?doc_get_orphan_password(a):form_get_password(a,b.form));var n=checkDocumentForLoginOrphans(a)||checkDocumentForLoginOrphansFirstStage(a),j=checkDocumentForCPWOrphans(a),n=n||chk_form_has_password(a,c),j=j||chk_form_is_nonlogin_form(a,c),q=chk_form_ask_generate(a,c);if(h&&l&&(n||q)&&!j){if(b!=h){b==l?(g_isie||(e=h.value,g_isfirefox||sendBG({cmd:"popupfillinputsave",
inputstr:e,inputid:f,inputtype:"password"})),verbose_log("KEYPASS4 username="+e)):(g_isie||(g_isfirefox?d&&(d.keyCode&&d.keyCode!=KEY_TAB&&d.keyCode!=KEY_UP&&d.keyCode!=KEY_DOWN&&d.keyCode!=KEY_SHIFT&&d.keyCode!=KEY_LEFT&&d.keyCode!=KEY_RIGHT)&&ff_do_popupinputupdate(""):sendBG({cmd:"popupfillinputsave",inputstr:"",inputid:f})),verbose_log('KEYPASS5 username=""'));return}}else{g_isie||(verbose_log('KEYPASS6 formfill? username=""'),g_isfirefox?ff_do_popupinputupdate(""):sendBG({cmd:"popupfillinputsave",
inputstr:"",inputid:f}));return}}if(null==e||0==e.length)g_isie||(g_isfirefox?ff_do_popupinputupdate(""):sendBG({cmd:"popupfillinputsave",inputstr:"",inputid:f})),verbose_log("KEYPASS7 empty username");else{d=0;for(var k in g_autofillsites)d++;if(!(0>=d)||g_change_icon_on_input){k=0;d=null;for(var g in g_autofillsites)"undefined"!=typeof g_autofillsites[g].useusername&&0==g_autofillsites[g].useusername.indexOf(e)&&(k++,d=g_autofillsites[g]);if(1==k)do_autofill_if_matched?g_isie||(g_isfirefox?ff_autofill(a,
d.aid):sendBG({cmd:"autofillaid",aid:d.aid})):(g_isie||(g_isfirefox?ff_do_popupinputupdate(e):sendBG({cmd:"popupfillinputsave",inputstr:e,inputid:f,inputtype:b.type,issaveall:issaveall(c)})),verbose_log("KEYPASS8 match>0 username="+e));else if(g_isie||(g_isfirefox?ff_do_popupinputupdate(e):sendBG({cmd:"popupfillinputsave",inputstr:e,inputid:f,inputtype:b.type,issaveall:issaveall(c)})),verbose_log("KEYPASS9 match>1 username="+e),chk_form_has_password(a,c),g_change_icon_on_input&&(b=c.elements,"undefined"!=
typeof Math&&(c=Math.floor(1E4*Math.random()),null!=b)))for(e=0;e<b.length&&!(f=b[e],checkIsDisplayed(a,f,0,null,c)&&isInputFieldPassword(a,f)&&null!=f.value&&0<f.value.length);e++);}}}}};
