var ExtensionCreateAccount=function(h){Dialog.call(this,h,{views:[{selector:"#emailEntry",nextButtonText:Strings.translateString("Create Account")},{selector:"#mpEntry",nextButtonText:Strings.translateString("Unlock my Vault")}],dynamicHeight:!1,responsive:!1,additionalHeaderClasses:["icon"],nextButtonText:Strings.translateString("Create Account"),buttonAlign:this.CENTER_ALIGN,hideBackButton:!0,largeButtons:!0,buttonsInsideContent:!0,title:Strings.translateString("Create Account"),hideHeaderTitle:!0})};
ExtensionCreateAccount.prototype=Object.create(CreateAccountDialog.prototype);ExtensionCreateAccount.prototype.constructor=ExtensionCreateAccount;
(function(){function h(a,d){bg.LPServer.textRequest({type:"GET",url:"create_account.php",CSRFToken:!1,data:{username:a,check:"avail",mistype:1},success:d,error:d})}function g(e,d){return function(b,c){var f=!1;d&&(a.clearError(e),f=d.validate(b,function(f){a.addError(e,f)},c));return f}}var a,j,k;ExtensionCreateAccount.prototype.initialize=function(e){CreateAccountDialog.prototype.initialize.apply(this,arguments);$(".meterContainer").remove();this.inputFields.password.getElement().LP_addPasswordMeter(this.inputFields.email.getElement(),
!0);a=this;var d=this,b=e.find(".buttonContent"),c=e.find(".buttons").detach();b.append(c);new FieldToolTip({parentEl:e});k=new EmailToolTip({toolTipEl:e.find("#mpCurrentEmail"),parentEl:$("body"),emailField:a.inputFields.email,backActionFn:function(){a.showPreviousView()}});e.find("#signInBtn").bind("click",function(a){a.preventDefault();$("[for^=createAccountEmail]")[0].style.display="none";dialogs.loginSimple.open({isPopup:!1});bg.sendLpImprove("viewloginform");d.close(!0)});b=LPTools.createElement("a",
{"class":"pull-right",href:"https://lastpass.com/forgot.php",target:"_blank"},Strings.translateString("Recovery Help"));c=LPTools.createElement("p",null,Strings.translateString("Email address already in use "));c.appendChild(b);b=new FieldValidator({summary:{id:"validatorSummaryEmail",parentEl:$("label[for='createAccountEmail'].error-summary")},validators:[{id:"404",errorMsg:LPTools.createElement("p",null,Strings.translateString("You have made too many attempts.")+"<br>"+Strings.translateString("Please wait 5 minutes then try again.")),
isValid:function(a){return!(a.response.status&&404===a.response.status)}},{id:"emailUsed",errorMsg:c,isValid:function(a){return"no"!==a.response}},{id:"emailInvalid",errorMsg:LPTools.createElement("p",null,Strings.translateString("Make sure to use a real email address")),isValid:function(a){return"ok"===a.response&&0!==a.response.indexOf("mistype:")&&"emailinvalid"!==a.response}}]});a.inputFields.email.validate=g("email",b);a.inputFields.email.fieldValidator=b;b=new FieldValidator({summary:{id:"validatorSummaryTermsAndConditions",
parentEl:$("label[for='termsAndConditions'].error-summary")},validators:[{id:"termsNotChecked",errorMsg:LPTools.createElement("p",null,Strings.translateString("Please agree to the Terms and Conditions")),isValid:function(a){return!0===a.termsAndConditions}}]});a.inputFields.termsAndConditions.validate=g("termsAndConditions",b);a.inputFields.termsAndConditions.fieldValidator=b;a.inputFields.email.onChange(function(f){f&&h(f,function(f){a.inputFields.email.validate({response:f})})});a.inputFields.password.onChange(function(f){f&&
a.inputFields.password.validate({password:a.inputFields.password.getValue(),email:a.inputFields.email.getValue()})});a.inputFields.password.getElement().keyup(function(){a.inputFields.password.validate({password:a.inputFields.password.getValue(),email:a.inputFields.email.getValue()},!0)});a.inputFields.reconfirm.onChange(function(f){f&&a.inputFields.reconfirm.validate({reconfirm:a.inputFields.reconfirm.getValue(),password:a.inputFields.password.getValue()})});a.inputFields.reminder.onChange(function(f){f&&
a.inputFields.reminder.validate({reminder:a.inputFields.reminder.getValue(),password:a.inputFields.password.getValue()})});j=new BackgroundOverlay({parentEl:$("body")});d.data.isPopup||$("body").addClass("login-background")};ExtensionCreateAccount.prototype.setNextView=function(a){Dialog.prototype.setNextView.apply(this,arguments);k.toggle(0<a);bg.sendLpImprove("viewregform",{currentPage:0===this.currentViewIndex?"email":"mpw"})};ExtensionCreateAccount.prototype.close=function(a){if(a)Dialog.prototype.close.apply(this,
arguments);else{var d=this;LPTools.getOption(d.data,"showcloseconfirm",!0)?(j.show(),dialogs.confirmation.open({title:"LastPass",text:Strings.translateString("Do you really want to quit?  You cannot use LastPass without creating an account."),closeHandler:function(){j.hide()},handler:function(){d.close(!0)}})):d.close(!0)}};ExtensionCreateAccount.prototype.clearError=function(a){(a=this.inputFields[a])&&a.clearErrors()};ExtensionCreateAccount.prototype.addError=function(a,d){var b=this.inputFields[a];
b&&(b._errors.push(d),b.clearErrors=function(){this._errors=[];b._errorElement&&b._errorElement.remove();this._errorElement=null})};ExtensionCreateAccount.prototype.validate=function(e,d){if(0===this.currentViewIndex)h(e.email,function(b){(b=a.inputFields.email.validate({response:b}))&&(b&=a.inputFields.termsAndConditions.validate(e));d&&d(b)});else if(this.currentViewIndex===this.views.length-1){var b=a.inputFields.password.validate(e),b=b&a.inputFields.reconfirm.validate(e),b=b&a.inputFields.reminder.validate(e);
d&&d(b)}};ExtensionCreateAccount.prototype.submit=function(){try{var e=this.getData();this.validate(e,function(b){if(b)if(a.getNextViewButton()===a.nextButton&&a.views&&a.currentViewIndex<a.views.length-1){var c=new FieldValidator({summary:{id:"validatorSummaryPassword",parentEl:$("label[for='createAccountDialogPassword'].error-summary"),labelEl:$("label[for='createAccountDialogPassword'].label"),errorMsg:LPTools.createElement("p",null,Strings.translateString("Sorry, your password is invalid"))},
listParentEl:$("#mpValidators"),validators:[{id:"passwordLength",name:LPTools.createElement("p",null,Strings.translateString("At least 8 characters long")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Master Password must be at least 8 characters")),isValid:function(a){return!0===(a.password&&8<=a.password.length)}},{id:"passwordSameAsEmail",name:LPTools.createElement("p",null,Strings.translateString("Not your email")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Master Password shouldn't contain your email")),
isValid:function(a){return!0===(a.password&&a.email&&-1===a.password.toLowerCase().indexOf(a.email.toLowerCase())&&-1===a.email.toLowerCase().indexOf(a.password.toLowerCase()))}},{id:"easyPassword",name:LPTools.createElement("p",null,Strings.translateString("Not easily guessable")),errorMsg:LPTools.createElement("p",null,Strings.translateString("That's in the top 100 most-used passwords")),isValid:function(a){return!0===(a.password&&!a.password.match(/^password\d{0,3}$/i)&&!a.password.match(/^lastpass\d{0,3}$/i)&&
!a.password.match(/^.{0,7}$/)&&"12345678"!==a.password&&"123456789"!==a.password&&"1234567890"!==a.password&&"lastpass.com"!==a.password&&"qwertyuiop"!==a.password&&"abcd1234"!==a.password)}}]});a.inputFields.password.validate=g("password",c);a.inputFields.password.fieldValidator=c;$("#twinsies").hide();c=new FieldValidator({summary:{id:"validatorSummaryReconfirm",parentEl:$("label[for='createAccountDialogConfirmPassword'].error-summary"),labelEl:$("label[for='createAccountDialogConfirmPassword'].label, #twinsies")},
validators:[{id:"reconfirmSameAsPassword",name:LPTools.createElement("p",null,Strings.translateString("Reconfirm same as password")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Make sure this matches your Master Password")),isValid:function(a){return!0===(a.reconfirm&&a.password===a.reconfirm)}}]});a.inputFields.reconfirm.validate=g("reconfirm",c);a.inputFields.reconfirm.fieldValidator=c;c=new FieldValidator({summary:{id:"validatorSummaryReminder",parentEl:$("label[for='createAccountReminder'].error-summary"),
labelEl:$("label[for='createAccountReminder'].label")},validators:[{id:"reminderNotPassword",name:LPTools.createElement("p",null,Strings.translateString("Reminder doesn't contain password")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Reminder shouldn't contain your Master Password")),isValid:function(a){return!(a.password&&-1!==a.reminder.toLowerCase().indexOf(a.password.toLowerCase()))}}]});a.inputFields.reminder.validate=g("reminder",c);a.inputFields.reminder.fieldValidator=
c;a.setNextView(a.currentViewIndex+1)}else bg.sendLpImprove("completedregform"),a.handleSubmit(e,this.data);else{b=[];for(c in a.inputFields)a.inputFields.hasOwnProperty(c)&&a.inputFields[c].fieldValidator&&(b=b.concat(a.inputFields[c].fieldValidator.getValidationList()));c=b.join(",");b={errorlist:c};a.inputFields.reminder&&""!==a.inputFields.reminder.getValue()&&(b.isReminder=!0);0<c.length&&(b.currentPage=0===a.currentViewIndex?"email":"mpw",bg.sendLpImprove("validationregform",b))}})}catch(d){LPPlatform.logException(d)}};
ExtensionCreateAccount.prototype.showInProcessOverlay=function(){j.show(!0)}})();
