ExtensionDropdown=function(d){var m=$(d.body),j=d.getElementById("items"),q=d.getElementById("searchResults"),r=d.getElementById("recentSites"),A=d.getElementById("identitiesMenuItem"),ja=d.getElementById("matchingSitesTopLevel"),ka=d.getElementById("matchingSites"),n=$("#groupLabel"),B=$("#backButton"),M=$("#debugconsole"),N=$("#encryptedExportMenuItem"),O=$("#wifiExportMenuItem"),P=$("#matchingSitesMenuItem"),Q=$("#recentSitesMenuItem"),h=$("#container"),s=$("#searchInput"),Z=$("#applicationsMenuItem"),
aa=null,t=null,u=null,v=null,C=null,D=null,E=null,ba=null,F=!1,G=!1,R=!1,S=!1,T={},f=null,H={},e=[],g={},U=function(a){n.empty();if(a){var b=a.getName(),b=b.replace(/\\/g," \\ "),c=b.indexOf("\\",b.length/2);-1===c&&(c=b.lastIndexOf("\\"));if(0<c){var w=LPTools.createElement("div","textOverflowContainer groupLabel");w.appendChild(LPTools.createElement("span",null,b.substring(0,c)));n.append(LPTools.createElement("span","textTail","\u00a0"+b.substring(c)));n.append(w);LPTools.setupMiddleEllipsis(n)}else n.append(LPTools.createElement("span",
"groupLabel",b));n.find(".groupLabel").attr("title",a.toString())}};g.GroupState=function(a){var b=LPTools.getNavIndex();this.pop=function(){a.rebuildItems();LPTools.setNavIndex(b);U(a._model)}};g.SearchState=function(){var a=new g.CSSState("searchItem",{restoreKeyboardNav:!1});this.pop=function(){ca();a.pop()}};g.TopLevelMatchingSitesState=function(a){var b=new g.CSSState("matchingSites"),c=new g.GroupState(a);this.pop=function(){c.pop();b.pop()}};var x=m.attr("class");g.CSSState=function(a,b){var c=
x;m.removeClass(x);m.addClass(a);x=a;LPTools.getOption(b,"applyKeyboardNav",!0)&&LPTools.addKeyBoardNavigation($(".extensionMenuItem:visible"),{selectFirst:!0});this.pop=function(){U(null);m.removeClass(x);m.addClass(c);x=c;LPTools.getOption(b,"restoreKeyboardNav",!0)&&LPTools.addKeyBoardNavigation($(".extensionMenuItem:visible"));if(b&&"function"===typeof b.onPop)b.onPop()}};var fa=function(){h.addClass("loading");M.LP_removeAttr("style");N.LP_removeAttr("style");O.LP_removeAttr("style");Z.LP_removeAttr("style");
bg.is_user_debug_enabled()&&M.show();bg.have_binary()&&(N.show(),bg.LPPlatform.isWin()&&O.show());LPTools.hasProperties(bg.get("g_applications"))&&Z.show();f=bg.getmatchingsites(!1,!0,!1);for(var a=0,b=f.length;a<b;++a)T[f[a].aid]=!0;(a=LPProxy.getPreference("toplevelmatchingsites",!1))||0===f.length?(P.LP_removeAttr("style"),Q.addClass("divider")):(P.show(),Q.removeClass("divider"));a?k("topLevelMatchingSites",function(){da(ja,{autoExpandSingleItem:!1,moreOptionsElement:d.getElementById("matchingSites"),
moreOptionsState:g.TopLevelMatchingSitesState,addLastClass:!1},!0)})():0<f.length&&$("#matchingSiteCounter").text(f.length);LPTools.parseUserSpecificMenu(d.getElementById("mainMenu"),LPProxy.getAccountClass());$("#username").text(bg.get("g_username"));I();h.addClass("initialized");s.focus();setTimeout(function(){LPProxy.initializeModel();t=LPProxy.getIdentities();LPProxy.enableCurrentIdentity(t);if(0<t.length){var a=aa,a=Strings.translateString("Identities")+" ("+a.getName()+")",b=A.firstChild;3!==
b.nodeType?(b=d.createTextNode(a),A.insertBefore(b,A.firstChild)):b.textContent=a;for(var a=[],b=0,e=t.length;b<e;++b)a.push(t[b].newDisplayObject());(new IdentityContainer(a)).initialize(d.getElementById("identities"))}else $(A).hide();u=ea(LPProxy.getSites());u.setElement(j);v=ea(LPProxy.getNotes());v.setElement(j);C=new Container(LPProxy.getFormFills());C.setElement(j);D=new Container(LPProxy.getApplications());D.setElement(j);ba=new Container(LPProxy.getAllItems(),{moreOptionsState:g.SearchState});
G=!0;h.removeClass("loading");for(var f in H)H[f]();(f=s.val())&&V(f);I()},0)},I,ga=function(){h.LP_removeAttr("style");var a=h.outerHeight();LPPlatform.setDropdownPopoverSize(a,h.outerWidth());h.css("height",a);LPTools.addKeyBoardNavigation($(".extensionMenuItem:visible"))};I=function(){if(0===e.length)ga();else{var a=e[0].pop;e[0].pop=function(){a();ga()}}};var ea=function(a){var b;LPProxy.getPreference("showAcctsInGroups",!0)&&(a=LPProxy.assignItemsToGroups(a,!1),b={separateFavorites:!0});return new Container(a,
b)},da=function(a,b,c){for(var w=[],d=0,e=f.length;d<e;++d)w.push(new MatchingAccountDisplay(LPProxy.getSiteModel(f[d].aid)));b=new Container(w,b);b.setElement(a);b.rebuildItems();c&&I()},ca=function(){LPTools.removeDOMChildren(q);for(var a=0,b=E.length;a<b;++a){var c=E[a],d=c.build();c.postBuild(d);q.appendChild(d)}0===E.length&&(a=LPTools.buildEmptyPlaceholder(Strings.translateString("No Matching Results"),"extensionSearchPlaceholder",q),q.appendChild(a));LPTools.addKeyBoardNavigation(q.children,
{rightArrowSelector:".moreItem",selectFirst:!0})},V,W=null;V=function(a){0<a.length?(G&&(E=ba.getSearchResultItems(a),ca()),F||(e.push(new g.CSSState("search",{applyKeyboardNav:!1,onPop:function(){s.val("")}})),F=!0)):W&&0<W.length&&(y(),F=!1);W=a};var k=function(a,b){return function(){G?b():H[a]=b}},z=function(a){a||(a={});a.saveOptions={source:"icon"};return a},X=function(a){bg.LPPlatform.openTabDialog("formFill",z(a))},ha=function(a){a.appendChild(LPTools.createElement("li","extensionMenuItem none",
"None Available"))},y=function(){var a=e.pop();a&&a.pop()},Y=function(){dialogs.generatePassword.getDialog().close();B.unbind("click",Y)},J=null,K=function(a,b,c){a.isEmpty()&&(a=LPTools.createElement("div","emptyView"),a.appendChild(LPTools.createElement("img",{src:"images/vault_4.0/"+b,"class":"emptyViewIcon"})),a.appendChild(LPTools.createElement("h1","emptyViewText",c)),document.getElementById("items").appendChild(a))};s.LP_addSearchHandlers("inputDialog",function(a){V(a)});B.bind("click",y);
$("[childview]").bind("click",function(a){for(var b=a.target,c=null;null!==b&&!(c=b.getAttribute("childview"),null!==c);)b=b.parentElement;e.push(new g.CSSState(c,void 0));a&&(a.stopPropagation(),a.preventDefault())});$("#addSite").bind("click",function(a){bg.get_selected_tab_data_no_extension(null,function(a){bg.lpevent("m_add");bg.LPPlatform.openTabDialog("site",z({defaultData:{url:a?a.url:""}}));LPPlatform.closePopup()});a.stopPropagation()});$("#saveAllEnteredData").bind("click",function(){bg.lpevent("m_saed");
bg.saveall()});$("#addNote").bind("click",function(){bg.lpevent("m_addn");bg.LPPlatform.openTabDialog("note",z(void 0))});$("#addFormFill").bind("click",function(){bg.lpevent("m_af");X()});$("#addCreditCard").bind("click",function(){bg.lpevent("m_af");X({defaultData:{profiletype:FormFill.prototype.FORM_FILL_TYPE_CREDIT_CARD}})});$("#clearForms").bind("click",function(){bg.lpevent("m_clrf");bg.clearforms("icon")});var L=null;$("#chooseProfile").bind("click",function(){dialogs.chooseProfile.open({preSetup:function(a){if(null===
L){var b=dialogs.chooseProfile.parentElementID,c=a.options.hideHeader;L=function(){dialogs.chooseProfile.parentElementID=b;a.options.hideHeader=c;a.$element.css("min-height","")}}a.$element.css("min-height",0);dialogs.chooseProfile.parentElementID="chooseProfileCreditCard";a.options.hideHeader=!0},onClose:function(){y()},saveOptions:{source:"icon"}})});$("#vaultMenuItem").bind("click",function(){bg.lpevent("m_ov");bg.openvault()});$("#sitesMenuItem").bind("click",k("sites",function(){u.rebuildItems(j);
K(u,"Empty_Site.png",Strings.translateString("Remember every password"))}));$("#formFillsMenuItem").bind("click",k("formFills",function(){C.rebuildItems(j);K(C,"Empty_Form.png",Strings.translateString("Fill Every Form"))}));$("#applicationsMenuItem").bind("click",k("applications",function(){D.rebuildItems(j);K(D,"Empty_Site.png",Strings.translateString("Remember every password"))}));$("#generateMenuItem").bind("click",function(){dialogs.generatePassword.open({preSetup:function(a){if(null===J){var b=
dialogs.generatePassword.parentElementID,c=a.options.hideHeader,d=a.dynamicHeight;J=function(){dialogs.generatePassword.parentElementID=b;a.options.hideHeader=c;a.useDynamicHeignt(d)}}dialogs.generatePassword.parentElementID="extensionDropdownGeneratePassword";a.options.hideHeader=!0;a.useDynamicHeignt(!1)},onClose:function(){y()},onCopy:function(){LPPlatform.closePopup(!0)},saveOptions:{source:"icon"}});B.unbind("click",Y);B.bind("click",Y)});$("#notesMenuItem").bind("click",k("notes",function(){v.rebuildItems(j);
K(v,"Empty_Note.png",Strings.translateString("Store Every Note"))}));$("#clearMostRecent").bind("click",function(){bg.clearrecent();LPTools.removeDOMChildren(r);ha(r)});var p=k("mostRecent",function(){if(!R){var a=bg.getClearRecentTime(),b=bg.Preferences.get("recentUsedCount"),c=u.getItemChildren().concat(v.getItemChildren());c.sort(VaultItemBaseDisplay.prototype.sortByMostRecent);for(var d=[],e=0,f=c.length;e<f&&e<b;++e){var g=c[e];g.getLastTouchValue()>=a&&d.push(g._model.newDisplayObject())}0<
d.length?(new Container(d,{sortFunction:VaultItemBaseDisplay.prototype.sortByMostRecent})).initialize(r):ha(r);R=!0}LPTools.addKeyBoardNavigation(r.children,{rightArrowSelector:".moreItem",selectFirst:!0})});Q.bind("click",p);p=k("matchingSites",function(){S||(da(ka),S=!0);LPTools.addKeyBoardNavigation(d.getElementById("matchingSites").children,{rightArrowSelector:".moreItem",selectFirst:!0})});P.bind("click",p);$("#prefMenuItem").bind("click",function(){bg.lpevent("m_op");bg.openprefs()});$("#helpMenuItem").bind("click",
function(){bg.lpevent("m_oh");bg.openhelp()});$("#adminConsoleMenuItem").bind("click",function(){bg.lpevent("m_oec");bg.openentconsole()});$("#logoutMenuItem").bind("click",function(){bg.lpevent("m_lo");bg.loggedOut(!1,"menu")});$("#challengeMenuItem").bind("click",function(){bg.lpevent("m_sec");bg.openseccheck()});$("#favoritesMenuItem").bind("click",function(){bg.lpevent("m_of");bg.openfavorites()});$("#aboutMenuItem").bind("click",function(){bg.lpevent("m_abt");bg.openabout()});M.bind("click",
function(){bg.lpevent("m_dbgcon");bg.opendebugtab()});$("#csvExportMenuItem").bind("click",function(){bg.lpevent("m_e");bg.openexport()});$("#formFillExportMenuItem").bind("click",function(){bg.lpevent("m_eff");bg.formfillexport()});N.bind("click",function(){bg.lpevent("m_elp");bg.openlastpassexport()});O.bind("click",function(){bg.lpevent("m_ewlan");bg.wlanexport()});$("#printSitesMenuItem").bind("click",function(){bg.lpevent("m_p");bg.openprint(!1)});$("#printNotesMenuItem").bind("click",function(){bg.lpevent("m_pn");
bg.openprint(!0)});$("#refreshMenuItem").bind("click",function(){bg.lpevent("m_ref");LPProxy.refreshSites()});$("#clearCachMenuItem").bind("click",function(){bg.lpevent("m_cl");bg.clearCache(!1,!0,!1)});$("#myAccountMenuItem").bind("click",function(){bg.lpevent("m_mya");bg.openmyaccount()});$("#sessionsMenuItem").bind("click",function(){bg.lpevent("m_ses");bg.opensessions()});LPPlatform.addEventListener(window,"unload",function(){ia()});m.on("click",".extensionMenuItem, .footer",function(){LPPlatform.closePopup()});
LPFeatures.allowGift()&&(p=$("#specialOfferMenuItem"),p.show(),p.bind("click",function(){bg.openURL(LPProxy.getBaseURL()+"gift.php")}));Topics.get(Topics.PUSH_STATE).subscribe(function(a){e.push(a)});Topics.get(Topics.EDIT_SITE).subscribe(function(a){a.vaultItem=a.vaultItem.getID();bg.LPPlatform.openTabDialog("site",z(a))});Topics.get(Topics.EDIT_NOTE).subscribe(function(a){a.vaultItem=a.vaultItem.getID();bg.LPPlatform.openTabDialog("note",z(a))});Topics.get(Topics.EDIT_FORM_FILL).subscribe(function(a){a.vaultItem=
a.vaultItem.getID();X(a)});Topics.get(Topics.EDIT_APPLICATION).subscribe(function(a){a.vaultItem=a.vaultItem.getID();bg.LPPlatform.openTabDialog("application",a)});Topics.get(Topics.IDENTITY_ENABLE).subscribe(function(a){LPProxy.enableIdentity(a);aa=a});Topics.get(Topics.CONFIRM).subscribe(function(a){l("confirmation",a)});Topics.get(Topics.ERROR).subscribe(function(a){l("alert",{title:Strings.Vault.ERROR,text:a})});Topics.get(Topics.REPROMPT).subscribe(function(a){l("reprompt",{successCallback:a})});
Topics.get(Topics.LEFT_ARROW).subscribe(function(){LPTools.disableMouse();y()});Topics.get(Topics.CLEAR_DATA).subscribe(function(){for(var a=e.length-1;-1<a;--a)e[a].pop();e=[];LPTools.setNavIndex(0);s.val("");S=R=G=F=!1;T={};H={};f=null;J&&J();L&&L();h.removeClass("initialized");Dialog.prototype.closeAllDialogs(!0)});Topics.get(Topics.INITIALIZED).subscribe(function(){Strings.translate(d.body);LPFeatures.updateFeatures({"import":!0,noexport:!1,show_notes:!0,hideidentities:!1,show_formfills:!0});
LPPlatform.setupDropdownImportMenu(h)});var l=function(a,b){$("#container").LP_hide();LPTools.removeKeyBoardNavigation();b=$.extend(b,{onResize:function(a,b){LPPlatform.setDropdownPopoverSize(a,b)},onClose:function(){LPPlatform.closePopup()}});LPDialog.openDialog(a,b)},ia=function(){Topics.get(Topics.CLEAR_DATA).publish()};return{setup:fa,State:g,isMatchingSite:function(a){return!0===T[a]},setGroupLabel:U,open:function(){var a=bg.get("g_badgedata");if(a&&"notification"===a.cmd){switch(a.alerttype){case "duplicate":l("duplicatePassword",
{notification:a});break;case "weak":l("weakPassword",{notification:a})}switch(a.type){case "error":l("notification",{notification:bg.get("g_notification_data")})}bg.clear_badge()}else $("#container").LP_show(),fa()},openDialog:l,reset:ia,setBigIcons:function(a){bg.set("g_bigicons",a)}}}(document);
