var GeneratePasswordDialog=function(a){VaultItemDialog.call(this,a,{additionalHeaderClasses:["icon","leftIcon"],dynamicHeight:!0,responsive:!1,title:Strings.translateString("Generate"),nextButtonText:Strings.translateString("Use Password"),confirmOnClose:!1,overlayDialog:!0})};GeneratePasswordDialog.prototype=Object.create(Dialog.prototype);GeneratePasswordDialog.prototype.constructor=GeneratePasswordDialog;
GeneratePasswordDialog.prototype.open=function(a){a=$.extend(a,{defaultData:{length:bg.Preferences.get("generate_length"),uppercase:bg.Preferences.get("generate_upper"),lowercase:bg.Preferences.get("generate_lower"),numeric:bg.Preferences.get("generate_digits"),special:bg.Preferences.get("generate_special"),minNumeric:bg.Preferences.get("generate_mindigits"),avoidAmbiguous:bg.Preferences.get("generate_ambig"),reqevery:bg.Preferences.get("generate_reqevery"),pronounceable:bg.Preferences.get("generate_pronounceable")}});
Dialog.prototype.open.call(this,a)};GeneratePasswordDialog.prototype.makePronounceable=function(){this.inputFields.numeric.setValue(!1);this.inputFields.numeric.disable();this.inputFields.special.setValue(!1);this.inputFields.special.disable();this.inputFields.minNumeric.disable();this.inputFields.minNumeric.disable();this.inputFields.avoidAmbiguous.disable()};
GeneratePasswordDialog.prototype.initialize=function(){Dialog.prototype.initialize.apply(this,arguments);this.inputFields.password.getElement().LP_addPasswordMeter();LPFeatures.allowClipboardCopy()||$("#copyPassword").LP_hide();var a=this;a.nextButton.unbind("click");a.nextButton.bind("click",function(){a.usePassword()});$("#generateButton").bind("click",function(){a.submit()});var b=[];a.minimumLength=4;if(bg.get("g_prefoverrides").sitepwlen){var c=parseInt(bg.get("g_prefoverrides").sitepwlen);c>
a.minimumLength&&(a.minimumLength=c)}for(c=a.minimumLength;101>c;c++)b.push({value:c.toString(),label:c.toString()});a.inputFields.length.setOptions(b);a.inputFields.length.setReadOnly();a.inputFields.length.onChange(function(){a.setupComplete&&a.submit()});LPPlatform.addEventListener(document.getElementById("copyPassword"),"click",function(){bg&&bg.sendLpImprove&&bg.sendLpImprove("copypass",{action:"generatePassword",source:a.data.saveOptions.source});LPProxy.copyToClipboard(a.inputFields.password.getValue());
Topics.get(Topics.SUCCESS).publish("Password Copied");if("function"===typeof a.data.onCopy)a.data.onCopy();a.close()});a.inputFields.reqevery.onChange(function(b){b&&a.setupComplete&&(a.inputFields.uppercase.setValue(!0),a.inputFields.lowercase.setValue(!0),a.inputFields.numeric.enable(),a.inputFields.numeric.setValue(!0),a.inputFields.special.enable(),a.inputFields.special.setValue(!1),a.inputFields.minNumeric.enable(),a.inputFields.avoidAmbiguous.enable())});a.inputFields.pronounceable.onChange(function(b){b&&
a.setupComplete&&a.makePronounceable()});$("input[type='checkbox'],input[type='radio'],input[type='text']").bind("change",function(){a.submit()})};
GeneratePasswordDialog.prototype.saveState=function(){var a=this.getData();bg.Preferences.set({generate_advanced:this.advancedOptionsShown,generate_length:a.length,generate_upper:a.uppercase,generate_lower:a.lowercase,generate_digits:a.numeric,generate_special:a.special,generate_mindigits:a.minNumeric,generate_ambig:a.avoidAmbiguous,generate_reqevery:a.reqevery,generate_pronounceable:a.pronounceable});this.storePassword()};
GeneratePasswordDialog.prototype.close=function(){this.saveState();return Dialog.prototype.close.apply(this,arguments)};
GeneratePasswordDialog.prototype.setup=function(a,b){bg.Preferences.get("generate_advanced")&&this.showAdvancedOptions();b.defaultData.length<this.minimumLength&&(b.defaultData.length=this.minimumLength);Dialog.prototype.setup.apply(this,arguments);LPTools.getOption(this.data,"fillGenerated",!0)?this.nextButton.LP_removeAttr("style"):void 0===b.input&&this.nextButton.hide();this.inputFields.password.setValues(bg.get("g_genpws")||[])};
GeneratePasswordDialog.prototype.postSetup=function(a){Dialog.prototype.postSetup.apply(this,arguments);this.submit()};GeneratePasswordDialog.prototype.storePassword=function(){var a=this.inputFields.password.getValue();if(a&&0<a.length){var b=bg.get("g_genpws")||[];b.unshift(a);20<b.length&&b.splice(20,b.length-20);bg.set("g_genpws",b);this.inputFields.password.setValues(b)}};
GeneratePasswordDialog.prototype.usePassword=function(){var a=this.inputFields.password.getValue();this.data.input?(this.data.input.val(a),this.close()):(bg.fillGeneratedPassword(this.data.tabID,this.data.tabURL,a,$.extend(this.data.saveOptions,{avoidAmbiguous:this.inputFields.avoidAmbiguous.getValue(),length:this.inputFields.length.getValue(),lowercase:this.inputFields.lowercase.getValue(),numeric:this.inputFields.numeric.getValue(),pronounceable:this.inputFields.pronounceable.getValue(),special:this.inputFields.special.getValue(),
uppercase:this.inputFields.uppercase.getValue()})),LPPlatform.closePopup(!0));this.saveState()};GeneratePasswordDialog.prototype.handleSubmit=function(a){this.storePassword();this.inputFields.password.setValue(bg.lpCreatePass(a.length,a.uppercase,a.lowercase,a.numeric,a.special,a.minNumeric,a.avoidAmbiguous,a.reqevery,a.pronounceable))};
