Interfaces=function(){var h=function(a,b){this.type=a;if(this.options=b)this.options.include&&(this.options.include=[].concat(this.options.include)),this.options.exclude&&(this.options.exclude=[].concat(this.options.exclude))};h.prototype.requiredBy=function(a){var b;if(a&&this.options){if(this.options.include){for(b=0;b<this.options.include.length;++b)if(this.options.include[b]===a)return!0;return!1}if(this.options.exclude)for(b=0;b<this.options.exclude.length;++b)if(this.options.exclude[b]===a)return!1}return!0};
h.prototype.isSyncronized=function(){return this.options&&!0===this.options.sync};h.prototype.isSyncronousFunction=function(){return this.type===Interfaces.TYPE_SYNC_FUNCTION};h.prototype.isFunction=function(){return this.type===Interfaces.TYPE_FUNCTION||this.type===Interfaces.TYPE_SYNC_FUNCTION};h.prototype.isConstructor=function(){return this.type===Interfaces.TYPE_CONSTRUCTOR};h.prototype.isPrimitive=function(){return!this.isFunction()&&!this.isConstructor()};h.prototype.shouldSendIndirect=function(){return this.isPrimitive()?
this.options&&"undefined"!==typeof this.options.sendIndirect?this.options.sendIndirect:!0:this.options&&!0===this.options.sendIndirect};h.prototype.allowWrite=function(){return this.options&&!0===this.options.write};h.prototype.addIncludes=function(a){this.options=this.options||{};this.options.include=this.options.include.concat(a)};var s=function(a,b){return function(){return b.apply(a,arguments)}},n=function(a,b,d){if("function"===typeof d.requestFunction)return function(){for(var e=[],f=0,c=arguments.length;f<
c;++f)e.push(arguments[f]);return d.requestFunction({cmd:0<a.length?a.concat(b):b,args:e})};throw"requestFunction must be specified for this interface since it is not direct access.";},t=function(a,b,d){return function(){"function"===typeof b&&b.apply(a,arguments);"function"===typeof d&&d.apply(a,arguments)}},p=function(a,b,d,e,f,c){var m=!1,j=[],g;for(g in e){var k=e[g];if(k instanceof h)if(k.isFunction()){if(k.requiredBy(c.context)&&(!k.isSyncronousFunction()||!c.asyncOnly))c.direct||k.isSyncronousFunction()?
b&&"function"===typeof b[g]?(a[g]=s(b,b[g]),!c.direct&&k.shouldSendIndirect()&&(a[g]=t(a,a[g],n(f,g,c)))):j.push(k.type+": "+f.concat(g).join(".")):a[g]=n(f,g,c)}else k.isConstructor()?k.requiredBy(c.context)&&!c.asyncOnly&&(b&&"function"===typeof b[g]?a[g]=b[g]:j.push(k.type+": "+f.concat(g).join("."))):m=!0;else a.hasOwnProperty(g)||(a[g]={}),p(a[g],b?b[g]:b,d?d[g]:d,e[g],f.concat(g),c)}if(m){a.get=function(a){if(e.hasOwnProperty(a))return d[a];throw a+" is not defined in the interface.";};var l=
function(a,b,c){if(!a.allowWrite())throw f.concat(b)+" is not writeable.";if(a&&typeof c===a.type)d[b]=c;else throw b+" is not defined in the interface.";};a.set=c.direct?function(a,b){l(e[a],a,b)}:function(a,b){var d=e[a];l(d,a,b);d.shouldSendIndirect()&&c.requestFunction({cmd:"LPData.setValue",args:[f.concat(a),b]})}}if(0<j.length)throw"Background instance does not support the following:\n"+j.join("\n");return a},q={},r={},l=function(a,b,d,e){var f=[],c;for(c in a){var m=e?e.concat(c):[c],j=a[c];
j instanceof h?j.isPrimitive()&&(j.requiredBy(b)&&(!d||j.isSyncronized()))&&f.push({sourceFunction:j.options&&j.options.sourceFunction,path:m}):f=f.concat(l(j,b,d,m))}return f};return{TYPE_CONSTRUCTOR:"contsructor",TYPE_SYNC_FUNCTION:"synchronous function",TYPE_FUNCTION:"function",TYPE_STRING:"string",TYPE_BOOLEAN:"boolean",TYPE_NUMBER:"number",TYPE_OBJECT:"object",Definition:h,extend:function(a,b){for(var d in b){var e=b[d];switch(typeof e){case "object":a.hasOwnProperty(d)?Interfaces.extend(a[d],
e):a[d]=e;break;default:a[d]=e}}},createInstance:function(a,b){return p(b.instance||{},b.source||b.sourceFunctions,b.source||b.sourceData,a,[],b)},getPrimitives:function(a){var b={};if(a.context){var d;d=a.context;var e;d=[].concat(d);for(var f=0;f<d.length;++f){var c=d[f];a.syncronizedOnly?(e=r[c],"undefined"===typeof e&&(e=r[c]=l(a.interface,c,!0))):(e=q[c],"undefined"===typeof e&&(e=q[c]=l(a.interface,c,!1)))}d=e;e=0;for(f=d.length;e<f;++e){var c=d[e],h;h=c.sourceFunction?"function"===typeof c.sourceFunction?
c.sourceFunction():LPReflection.callFunction(null,c.sourceFunction,[],{context:a.source}):LPReflection.getValue(a.interface,c.path,{context:a.source});LPReflection.setValue(null,c.path,h,{context:b})}}return b},getName:function(a){for(var b in this)if(a===this[b])return b;throw Error("Could not find interface name.");}}}();
