function sendRequest(a){if(null!=a)if(a.cmd&&"popupfillinputget"!=a.cmd&&"popupfilliconnumber"!=a.cmd&&L("IF -> BG : cmd="+a.cmd),g_ischrome)try{chrome_runtime_sendMessage(a,function(){})}catch(b){}else g_issafari?safari.self.tab?safari.self.tab.dispatchMessage(a.cmd,a):safari.extension&&(safari.extension.globalPage&&safari.extension.globalPage.contentWindow)&&safari.extension.globalPage.contentWindow.message_handler({name:a.cmd,message:a,target:window}):g_isfirefoxsdk?(a.messagetype=a.cmd,send_message(a)):
g_iscasper&&"function"==typeof t_sendmsg&&t_sendmsg(a)}
var g_reference_url="",InfieldIcons={globe:"/images/Globe.png",profile:"/images/Profile.png",other:"/images/Other.png",mastercard:"/images/Mastercard.png",visa:"/images/Visa.png",amex:"/images/Amex.png"},InfieldCommands=function(){function a(a){csTop.LPInfieldFrame.close(a)}return{closePopup:a,copyToClipboard:function(a,c){sendRequest({cmd:"copytoclipboard",g_data:a,action:c,source:"formv2"})},editSite:function(a){sendRequest({cmd:"editaid",aid:a,fromiframe:1})},fillUsernamePass:function(b){sendRequest({cmd:"autofillaid",
aid:b,from_iframe:!0,no_manualfill_on_saveall:!0,fromiframe:1});a("action")},copyUrl:function(a){sendRequest({cmd:"copyurl",aid:a,fromiframe:1})},copyUserName:function(a){sendRequest({cmd:"copyusername",aid:a,fromiframe:1})},copyPassword:function(a){sendRequest({cmd:"copypassword",aid:a,fromiframe:1,source:"formv2"})},editFormFill:function(b){sendRequest({cmd:"editprofile",ffid:b,fromiframe:1,source:"formv2"});a("action")},fillForm:function(b){sendRequest({cmd:"fillformffid",ffid:b,fromiframe:1,source:"formv2"});
a("action")},getGeneratePrefs:function(a){chrome_runtime_sendMessage({cmd:"popupfillgetgenerateprefs"},a)},writeAllPrefs:function(a,c){chrome_runtime_sendMessage({cmd:"popupfillsetgenerateprefs",prefstr:a,genpwstr:c})},fillGeneratedPassword:function(b,c){sendRequest({cmd:"fillgenpassword",password:b,saveOptions:c,nofill:1});a("action")},searchVault:function(a,c,e){chrome_runtime_sendMessage({cmd:"searchvault",searchQuery:a,searchType:c},e)},getInitialData:function(a){chrome_runtime_sendMessage({cmd:"getpopupfilldata"},
a)}}}();
(function(a){var b=function(c,e,b){var d=this;d._onResizeCallback=b;c&&(d._triggerElement=c instanceof jQuery?c:a("#"+c),e?(d._triggerElement.click(function(a){d.show();d._setPosition(a)}),d._triggerElement.keypress(function(c){d.show();a(d._menuElement[0]).children().children()[0].focus();d._setPosition(c)})):(d._triggerElement.children().click(function(){d.show()}),d._triggerElement.children().keypress(function(){d.show();a(d._menuElement[0]).children().children()[0].focus()})))};b.prototype._setPosition=function(c){c=
a(c.currentTarget).offset();c.top+=20;c.left+=20;this._menuElement.offset(c)};b.prototype.show=function(){a(".dropdown").hide();a(".menuTriggered").removeClass("menuTriggered");var c=this;c._triggerElement.closest(".tile").addClass("menuTriggered");c._triggerElement.addClass("menuTriggered");this._menuElement&&this._menuElement.show(0,function(){c._onResizeCallback&&c._onResizeCallback(c._menuElement.height(),90)})};b.prototype.hide=function(a){this._triggerElement.closest(".tile").removeClass("menuTriggered");
this._triggerElement.removeClass("menuTriggered");this._triggerElement.blur();this._menuElement&&(this._menuElement.hide(a),this._onResizeCallback())};b.prototype.resetTimer=function(a){var e=this;e._menuElement&&(e._menuTimer=setTimeout(function(){e.hide()},a||1E3))};b.prototype.createMenu=function(c,e,b){var d=this;d._menuElement=a("<div></div>").attr("id",c+"Menu").addClass("dropdown").addClass(e).hide().hover(function(){d._triggerElement.closest(".tile");clearTimeout(d._menuTimer)},function(){d.resetTimer(300)}).append(d._createMenuItems(b));
return d._menuElement};b.prototype._createMenuItems=function(c){var e=this;e._menuItems=c;c=a("<ul></ul>").addClass("menuList");for(var b=0;b<e._menuItems.length;b++){var d=a("<li></li>").attr("data-viewId",e._menuItems[b].id).attr("tabindex","1").click(function(a){e.hide();e.select(a.currentTarget.getAttribute("data-viewId"),!0)}).focus(function(){clearTimeout(e._menuTimer)}).keypress(function(a){e.hide();e.select(a.currentTarget.getAttribute("data-viewId"),!0)}).append(a("<p></p>").text(e._menuItems[b].text));
c.append(d)}return c};b.prototype._findMenu=function(c){var b=a.grep(this._menuItems,function(a){return a.id===c});return b&&0<b.length?b[0]:null};b.prototype.select=function(a,b){var f=this._findMenu(a);f&&this._triggerElement&&this._triggerElement.find("p").text(f.selectedText);!0===b&&(f&&f.action)&&f.action()};return window.InfieldMenu=b})(jQuery);
var InfieldView=function(a){function b(){a.each(c,function(b,c){a("#"+c).hide()})}var c=[];return{init:function(a){Array.isArray(a)&&0<a.length&&(c=a,b())},show:function(e){-1!=c.indexOf(e)&&(b(),a("#"+e).show())}}}(jQuery),InfieldGeneratePassword=function(a){function b(){var b=lpCreatePass(a("#length").val(),a("#upper").prop("checked"),a("#lower").prop("checked"),a("#digits").prop("checked"),a("#special").prop("checked"),2,a("#ambig").prop("checked"),!0,a("#pronounceable").prop("checked"));a("#password").val(b).change()}
function c(){a("#generatedPasswordLength").text(a("#length").val());a("#sliderFill").width(a("#length").val()+"%")}var e={};return{init:function(f,d,g){a("#moreOptions, #hideOptions").click(function(){a("#advancedView").toggle();a("#generateAndFillView").toggle();a("#generateBtnContainer").toggle();a("#moreOptions").toggle();g&&g()});a("#length").on("input",function(){InfieldSearch.debounce(c(),500)});a(".pwgen").change(b);a("#generateBtn").click(b);a("#pronounceable").click(function(){a("#pronounceable").prop("checked")?
(a("#digits").prop("checked",!1),a("#digits").prop("disabled",!0),a("#special").prop("checked",!1),a("#special").prop("disabled",!0),a("#ambig").prop("checked",!1),a("#upper").prop("checked",!0),a("#lower").prop("checked",!0)):(a("#digits").prop("checked",!0),a("#digits").prop("disabled",!1),a("#special").prop("checked",!0),a("#special").prop("disabled",!1))});a("#ambig").click(function(){a("#ambig").prop("checked")&&(a("#pronounceable").prop("checked",!1),a("#digits").prop("disabled",!1),a("#special").prop("disabled",
!1))});a("#password").LP_addGeneratePasswordMeter();a("#btnCopy").click(function(){f.copyToClipboard(a("#password").val(),"generatepassword")});d=function(){f.fillGeneratedPassword(a("#password").val(),{pronounceable:a("#pronounceable").prop("checked"),length:a("#password").val().length,expand:a("#moreOptions").is(":hidden"),uppercase:a("#upper").prop("checked"),lowercase:a("#lower").prop("checked"),numeric:a("#digits").prop("checked"),special:a("#special").prop("checked"),avoidAmbiguous:a("#ambig").prop("checked"),
source:"formv2"});e[Object.keys(e).length]=a("#password").val();f.writeAllPrefs(JSON.stringify({generate_pronounceable:a("#pronounceable").prop("checked")?1:0,generate_length:a("#length").val(),generate_upper:a("#upper").prop("checked")?1:0,generate_lower:a("#lower").prop("checked")?1:0,generate_digits:a("#digits").prop("checked")?1:0,generate_special:a("#special").prop("checked")?1:0,generate_ambig:a("#ambig").prop("checked")?1:0,generate_mindigits:2,generate_reqevery:0}),LPJSON.stringify(e))};a("#fillPasswordBtn").click(d);
a("#generateAndFillBtn").click(d);a("#generateAndFillBtn").keypress(d);a("#advancedView").hide();a("#generateBtnContainer").hide()},setup:function(b){e=LPJSON.parse(b.genpwstr);b=JSON.parse(b.prefstr);a("#length").val(parseInt(b.generate_length));c();a("#upper").prop("checked",parseInt(b.generate_upper)?!0:!1);a("#lower").prop("checked",parseInt(b.generate_lower)?!0:!1);a("#digits").prop("checked",parseInt(b.generate_digits)?!0:!1);a("#special").prop("checked",parseInt(b.generate_special)?!0:!1);
a("#ambig").prop("checked",parseInt(b.generate_ambig)?!0:!1);a("#advancedView").hide();a("#generateAndFillView").show();parseInt(b.generate_pronounceable)?a("#pronounceable").click():a("#pronounceable").prop("pronounceable",!1);a("#password").val(lpCreatePass(a("#length").val(),a("#upper").prop("checked"),a("#lower").prop("checked"),a("#digits").prop("checked"),a("#special").prop("checked"),2,a("#ambig").prop("checked"),!0,a("#pronounceable").prop("checked"))).change()},show:function(){a("#moreOptions").show();
a("#generateBtnContainer").hide()},hide:function(){a("#moreOptions").hide();a("#generateBtnContainer").hide()}}}(jQuery),InfieldTiles=function(a,b,c,e){var f;return{setup:function(d,g,m,h,j,n){f=j;var q=[];a("#menuContainer").empty();a("#"+d).empty().append(a('<p class="italic"></p>').text(n));if(m){var r=a.map(m,function(a){return a});r.sort(function(a){return a});a.each(r,function(d,k){var p=!1;d+1===r.length&&(p=!0);var s="sites"===g?k.aid:k.ffid,j="sites"===g?k.name:k.decprofilename,m="sites"===
g?k.unencryptedUsername:1==k.profiletype?k.formattedCCNum:null,l="",n="";if("formfills"===g)if(0==k.profiletype)l=InfieldIcons.profile;else switch(k.ccType){case "VISA":l=InfieldIcons.visa;break;case "AMEX":l=InfieldIcons.amex;break;case "MC":l=InfieldIcons.mastercard;break;default:l=InfieldIcons.other}else n="siteIcon",l=h&&k.aid&&h[k.aid]?h[k.aid]:InfieldIcons.globe;var n=a("<img/>").attr("src",l).addClass("defaultIcon "+n),u="sites"===g?e.translateString("More"):e.translateString("Edit"),x="sites"===
g?null:function(){b.editFormFill(k.ffid)},l="sites"===g?function(){b.fillUsernamePass(k.aid)}:function(){b.fillForm(k.ffid)},y=null,v=a("<div></div>").addClass("col-8 text full-height"),u=a("<button></button>").attr("id",s+"btn").attr("tabindex","1").text(u);switch(g){case "formfills":v.append(a("<span></span>").text(j));m&&v.removeClass("full-height").append(a("<br/>")).append(a("<span></span>").addClass("small").text(m));break;case "sites":v.append(a("<span></span>").addClass("small").text(j)),
m&&v.removeClass("full-height").append(a("<br/>")).append(a("<span></span>").text(m)),y=new c(u,!0,f),a("#menuContainer").append(y.createMenu(s+"btn","tileDropdown",[{id:"copyPassword",text:"Copy password",action:function(){b.copyPassword(s)}},{id:"copyUsername",text:"Copy username",action:function(){b.copyUserName(s)}},{id:"copyURL",text:"Copy URL",action:function(){b.copyUrl(s)}},{id:"editSite",text:"Edit",action:function(){b.editSite(s)}}]))}x&&u.click(x);j=a("<div></div>").addClass("col-2 no-right-gutter no-left-gutter pull-right more").append(u);
m=a("<div></div>").addClass("col-2 no-left-gutter no-right-gutter").append(a("<div></div>").addClass("icon").append([n]));m.click(l);v.click(l);var t=a("<div></div>").addClass("tile col-12").attr("id",s).attr("tabindex","1").append(a("<div></div>").addClass("row").append(m,v,j)).hover(function(){},function(){t.removeClass("triggered")});p&&t.addClass("lastTile");u.focus(function(){t.addClass("triggered")}).blur(function(){t.removeClass("triggered")}).click(function(){t.addClass("menuTriggered");t.removeClass("triggered")});
j=t;j&&q.push(j)});0<q.length&&a("#"+d).empty().append(q)}return q.length}}}(jQuery,InfieldCommands,InfieldMenu,Strings),InfieldSearch=function(a){function b(a,b){var c;return function(){var e=this,d=arguments;clearTimeout(c);c=setTimeout(function(){c=null;a.apply(e,d)},b)}}function c(){m.fadeOut();g.show();g.animate({width:"360px"},250,function(){n.show();j.fadeIn().focus()});q.addClass("searchBtnActive")}function e(){j.val("");j.hide();n.fadeOut();g.show();g.animate({width:"16px"},250,function(){h.fadeOut();
m.fadeIn()});q.removeClass("searchBtnActive")}function f(){g.show()}function d(){j.hide();h.hide();n.hide();g.hide()}var g,m,h,j,n,q;return{init:function(d){g=a("#searchContainer");m=a("#currentTab");h=a("#searchBtnContainer");j=a("#inlineSearch");n=a("#searchCloseBtn");q=a("#searchBtn");j.hide();n.hide();g.show().css({width:"16px"});h.hide();m.show();q.removeClass("searchBtnActive");a("#searchBtn").click(function(){c()}).keypress(function(){c()});a("#searchCloseBtn").click(function(){e();d("")}).keypress(function(){e();
d("")});if(d){var f=b(function(b){d(a(b.currentTarget).val())},500);j.keyup(f)}},debounce:b,showIcon:f,hideIcon:d,display:function(a){a&&!0===a?f():d()}}}(jQuery);
(function(a){var b=function(b){this.options=a.extend({$parentEl:null,$arrowEl:null,arrowClass:"arrow-box"},b);this.setup();return this};b.prototype.setup=function(){this.options.$parentEl&&(this.options.$arrowEl=a("<div></div>").addClass(this.options.arrowClass),this.options.$parentEl.append(this.options.$arrowEl))};b.prototype.setPosition=function(a,b){this.options.$arrowEl&&(a?(this.options.$arrowEl.css("left",b),this.options.$arrowEl.css("top","")):(this.options.$arrowEl.css("left",""),this.options.$arrowEl.css("top",
b)))};b.prototype.show=function(a,b){if(this.options.$arrowEl)if(a&&b){this.options.$arrowEl.removeClass("a-top a-bottom a-left a-right");switch(a){case "top":this.options.$arrowEl.addClass("a-top");this.setPosition(!0,b);break;case "bottom":this.options.$arrowEl.addClass("a-bottom");this.setPosition(!0,b);break;case "left":this.options.$arrowEl.addClass("a-left");this.setPosition(!1,b);break;case "right":this.options.$arrowEl.addClass("a-right"),this.setPosition(!1,b)}this.options.$arrowEl.show()}else this.options.$arrowEl.hide()};
b.prototype.hide=function(){this.options.$parentEl&&this.options.$parentEl.removeClass(this.options.arrowClass)};return window.lpArrow=b})(jQuery);
var lpInfield=function(a,b,c,e,f,d,g,m,h){function j(b){s&&(b&&b.position&&a.isNumeric(b.position)&&10<b.position&&370>b.position)&&s.show("top",b.position+"px")}function n(a){b.searchVault(a,p.start_type,q)}function q(a){var b=p.start_type;if(a&&(a=JSON.parse(a)))switch(b){case "sites":f.setup("sitesView",b,a.sites,a.bigicons,r,A);break;case "formfills":f.setup("formFillView",b,a.formfills,null,r,B)}}function r(b,c){var d=a(".infield-dialog").outerHeight()+20,e=a(".infield-dialog").outerWidth()+
10;b&&a.isNumeric(b)&&(d+=b);c&&a.isNumeric(c)&&(e+=c);csTop.LPInfieldFrame.resizeFrame(d,e)}function w(c){if(c){p=c;if(c.start_type)switch(c.start_type){case "sites":if(c.sites){var h=JSON.parse(c.sites),j=c.bigicons?JSON.parse(c.bigicons):null;c=f.setup("sitesView",c.start_type,h,j,r,z);k.select("sitesView");e.show("sitesView");d.display(2<c);g.hide()}break;case "formfills":c.formfills&&(h=JSON.parse(c.formfills),c=f.setup("formFillView",c.start_type,h,null,r,l),k.select("formFillView"),e.show("formFillView"),
d.display(2<c),g.hide());break;case "generate":b.getGeneratePrefs(g.setup),k.select("generatePassView"),e.show("generatePassView"),d.display(!1),g.show()}csTop.LPInfieldFrame.positionFrame();csTop.LPInfieldFrame.show();a(".infield-dialog").show()}else b.closePopup("close")}var k,p,s,z=h.translateString("No sites found for this web address. You can log in to this website to save your credentials"),A=h.translateString("No sites found matching your search."),l=h.translateString("No Form Fills saved. You can add one in your Vault."),
B=h.translateString("No Form Fills found matching your search.");return{init:function(){document.addEventListener("DOMContentLoaded",function(){var f=function(){h.translate(document.body);s=new m({$parentEl:a(".infield-dialog")});j({position:360});a("#btnClose").click(function(){b.closePopup("close")});a("#btnClose").keypress(function(){b.closePopup("close")});e.init(["sitesView","formFillView","generatePassView"]);k=new c("currentTab",null,r);var f=k.createMenu("navigation",null,[{id:"sitesView",
text:h.translateString("Log inlower"),selectedText:h.translateString("Log in as"),action:function(){p.start_type="sites";w(p)}},{id:"formFillView",text:h.translateString("Fill form"),selectedText:h.translateString("Fill form with"),action:function(){p.start_type="formfills";w(p)}},{id:"generatePassView",text:h.translateString("Generate password"),selectedText:h.translateString("Generate password"),action:function(){p.start_type="generate";w(p)}}]);a("#navigationPlaceholder").append(f);d.init(n);g.init(b,
k,r);(new MutationObserver(function(){r()})).observe(a(".infield-dialog")[0],{subtree:!0,childList:!0});b.getInitialData(w);a("#currentTabText").focus()},l=document.createElement("iframe");l.setAttribute("class","backgroundFrame");l.src="backgroundFrame.html";l.style.display="none";l.addEventListener("load",function(){l.contentWindow.LPPlatform.getBackgroundInterface({mainRequestFramework:!1,interfaceDefinition:Interfaces.InfieldPopupInterface,context:"infieldPopup",callback:function(a){window.bg=
a;f&&f()}});l.contentWindow.Topics.get(l.contentWindow.Topics.REQUEST_FRAMEWORK_INITIALIZED).subscribe(function(a,b){var c=parseInt(a.topFrameID);window.csTop=Interfaces.createInstance(Interfaces.ContentScriptInterface,{direct:!1,context:"infieldPopup",requestFunction:function(a){b.sendRequest({type:"contentScriptRequest",data:a,frameID:c})}});window.csTop.LPFrame.initializeRequestFramework(LPTools.getURLParams().dialogID)})});document.body.appendChild(l)})},setArrowPosition:j}}(jQuery,InfieldCommands,
InfieldMenu,InfieldView,InfieldTiles,InfieldSearch,InfieldGeneratePassword,lpArrow,Strings);lpInfield&&lpInfield.init();
