LPPlatform={};
(function(){LPPlatform.lpIsExtension=function(){return!0};LPPlatform.openURL=function(a){bg.openURL(a)};LPPlatform.getBaseURL=function(){return bg.get("base_url")};LPPlatform.doAjax=function(a){$.ajax(a)};LPPlatform.ajax=function(a){bg.isOffline()?a.error&&a.error(null,null,"offline"):LPPlatform.doAjax(a)};LPPlatform.getOpenGroups=function(){var a=bg.localStorage_getItem(bg.db_prepend(bg.get("g_username_hash")+".savedtree"));if(null!==a){for(var b={},a=LPProxy.decrypt(a).split(","),c=0,e=a.length;c<
e;++c){var d=a[c];0===d.indexOf("_")&&(d=d.substring(1));b[d]=!0}return b}return null};LPPlatform.setOpenGroups=function(a){for(var b=0,c=a.length;b<c;++b)a[b]="_"+a[b];a=LPProxy.encrypt(a.join(","));bg.localStorage_setItem(bg.db_prepend(bg.get("g_username_hash")+".savedtree"),a)};LPPlatform.initialized=function(){return!0};LPPlatform.getHTML=function(a,b){$.ajax({url:a,success:b,dataType:"text"})};LPPlatform.loadedPreferences=function(){return LPTools.hasProperties(bg.get("g_userprefs"))};LPPlatform.openAttachment=
function(a){bg.openAttach(a._parentNote.getID(),a.getID())};LPPlatform.saveAttachment=function(a){bg.exportAttachment(a._parentNote.getID(),a.getID())};LPPlatform.logException=function(a){var b="string"===typeof a?a:a.message;a.stack&&(b+="\n"+a.stack);LPPlatform.logError(b)};LPPlatform.logError=function(a){a="Page: "+window.location.href+" Error: "+a;try{console.error(a),bg.lpReportError("VAULT_4_0: "+a)}catch(b){}};LPPlatform.addEventListener=function(a){for(var b=[],c=1;c<arguments.length;++c)b.push(arguments[c]);
a.addEventListener.apply(a,b)};LPPlatform.removeEventListener=function(a){for(var b=[],c=1;c<arguments.length;++c)b.push(arguments[c]);a.removeEventListener.apply(a,b)};LPPlatform.handleAcctsIFrameLoaded=function(){};LPPlatform.canBackgroundOpenPopover=function(){return!0};LPPlatform.generateSharingKeys=function(a){bg.generateSharingKeys(a)};LPPlatform.getResourcePath=function(a){return a};LPPlatform.canPreventBlur=function(){return!0};LPPlatform.getBackgroundData=function(a){return a};LPPlatform.showIntroTutorial=
function(){return!1};LPPlatform.supportsBinary=function(){return!0};LPPlatform.openKeyboard=function(){bg.LPPlatform.openTabDialog("login",{virtualKeyboard:!0})};LPPlatform.getImportHandler=function(){return"importerHandler"};LPPlatform.showDownloader=function(){return!1}})();
(function(a){a.closePopup=function(b){(b||0===Dialog.prototype.getDialogCount()&&0===LPDialog.getPendingCount())&&a.doClosePopup()};a.doClosePopup=function(){window.close()};a.closeTab=function(){window.close()};a.checkBrowserPasswordManager=function(){};a.setupDropdownImportMenu=function(a){a.addClass("singleImportOption");a=$("#importMenuItemMain");a.unbind("click");a.bind("click",function(){bg.lpevent("m_i");bg.openimport()})};a.getUnavailablePreferences=function(){return{clearClipboardSecsVal:!bg.can_clear_clipboard(),
openpopoverHk:!a.canBackgroundOpenPopover(),pollServerVal:bg.get("g_nopoll"),storeLostOTP:"0"===bg.get("g_prefoverrides").account_recovery,showvault:bg.get("g_hidevault")||bg.get("g_hideshowvault"),homeHk:bg.get("g_hidevault")||bg.get("g_hideshowvault"),saveallHk:bg.get("g_hidesaedhotkey"),searchHk:bg.get("g_hidesearch"),usepopupfill:!bg.get("g_offer_popupfill"),recentUsedCount:bg.get("g_hiderecentlyusedlistsize"),searchNotes:bg.get("g_hidenotes"),idleLogoffVal:!(bg.get("g_is_win")||bg.get("g_is_mac")||
bg.get("g_is_linux")),enablenamedpipes:bg.get("lppassusernamehash")||!(bg.get("g_is_win")||bg.get("g_is_mac")||bg.get("g_is_linux"))||bg.is_chrome_portable(),enablenewlogin:!0}};a.getPreferencesRequiringBinary=function(){return{enablenamedpipes:!0}};a.handlePreferenceChanges=function(a){!1===a.storeLostOTP&&bg.DeleteOTP()};a.resizeTo=function(a,c){window.resizeTo(a,c)};a.openCreateAccount=function(){bg.LPPlatform.openTabDialog("createAccount")};a.showIntroTutorial=function(){var a=LPProxy.getModelCount();
if("US"!==bg.get("countryfromip"))return LPVault.openTour(),!1;var c=LPProxy.getPreference("ShowIntroTutorial",!0);c&&0===a?dialogs.introTutorialWelcome.open():c&&1===a?bg.IntroTutorial.getState(function(a){a.enabled?(Topics.get(Topics.EXPAND_ALL).publish(),dialogs.introTutorialComplete.open({tutorialState:a})):LPVault.openTour()}):LPVault.openTour()}})(LPPlatform);
