(function(a){var k=null;a.getBackgroundInterface=function(a){null===k&&(a=a||{},a.source=window,a.direct=!0,k=Interfaces.createInstance(Interfaces.BackgroundInterface,a));return k}})(LPPlatform);
(function(a,k){a.getFavicon=function(b){b.callback&&b.callback(null)};a.getBigIcons=function(b,j){var c=(j||"big")+"icons",a=opendb();createDataTable(a);if(a){var d=function(c,a){b(0<a.rows.length&&null!==a.rows.item(0).data?a.rows.item(0).data:"")};if(g_indexeddb){var g={rows:{item:function(b){return this[b]},length:0}};a.transaction("LastPassData","readonly").objectStore("LastPassData").openCursor(IDBKeyRange.only(db_prepend(g_username_hash)+"_"+c)).onsuccess=function(b){(b=b.target.result)?(g.rows[g.rows.length]=
b.value,g.rows.length++,b["continue"]()):d(null,g)}}else a.transaction(function(b){b.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),c],d,function(b,c){console_log(c)})})}};a.saveBigIcons=function(b,a){var c=(a||"big")+"icons",e=opendb();createDataTable(e);e&&(g_indexeddb?e.transaction("LastPassData","readwrite").objectStore("LastPassData").put({username_hash:db_prepend(g_username_hash),type:c,data:b,usertype:db_prepend(g_username_hash)+"_"+c}):
e.transaction(function(a){a.executeSql("REPLACE INTO LastPassData (username_hash, type, data) VALUES (?, ?, ?)",[db_prepend(g_username_hash),c,b],function(){console_log("server.js : inserted")},function(b,c){console_log(c)})}))};a.updateBigIcons=function(){};var m=function(b,a){for(var c in b){var e=a[c];e&&(e.group=b[c])}};a.refreshGroupNames=function(b){b&&(m(b.sites,g_sites),m(b.notes,g_securenotes),m(b.applications,g_applications))};a.useDialogWindows=function(){return Preferences.get("htmlindialog")};
var l={};a.openTabDialog=function(b,j){var c={createAccountSimple:!0,siteTutorial:!0},e=b+(j?"-"+JSON.stringify(j):""),d=l[e];if(d)d.activate();else{var g={dialogWindow:a.useDialogWindows()&&!(j&&j.virtualKeyboard)},d={url:getchromeurl("tabDialog.html?dialog="+b),loadHandler:function(c){c.getTop().LPTabDialog.openDialog(b,j,g);l[e]=c},closeHandler:function(){delete l[e]},tabId:j&&j.tabId?j.tabId:void 0};if(d.tabId)a.navigateTab(d);else if(g.dialogWindow&&!c[b]){var h=Preferences.get("dialogSizePrefs"),
c=h[b];d.features={height:c?c.height:600,width:c?c.width:800,left:c?c.left:0,top:c?c.top:0};d.features.width>window.screen.availWidth&&(d.features.width=window.screen.availWidth,d.features.left=0);d.features.height>window.screen.availHeight&&(d.features.height=window.screen.availHeight,d.features.top=0);var k=d.closeHandler,f=function(c){h[b]={height:c.outerHeight,width:c.outerWidth,left:c.screenLeft||c.screenX,top:c.screenTop||c.screenY};Preferences.set("dialogSizePrefs",h);delete l[e]};d.closeHandler=
function(){k.apply(this,arguments);f.apply(this,arguments)};a.openDialogWindow(d)}else if(c[b])a.openTab(d);else switch(Preferences.get("openpref")){case "tabs":a.openTab(d);break;case "windows":a.openWindow(d);break;case "same":a.openSame(d)}}};a.stringifyFeatures=function(b){var a=[],c;for(c in b)a.push(c+"="+b[c]);return a.join(",")};a.doAjax=function(b){LPServer.ajax(b)};a.ajax=function(b){isOffline()?b.error&&b.error(null,null,"offline"):a.doAjax(b)};a.isEdge=function(){return is_edge()};a.copyDataIfEdge=
function(b){return a.isEdge()&&"undefined"!==typeof b?JSON.parse(JSON.stringify(b)):b};var t=a.setUserPreference;a.setUserPreference=function(b,a){t(b,a);g_userprefs_changed[b]=a};var u=a.setGlobalPreference;a.setGlobalPreference=function(b,a){u(b,a);g_gblprefs_changed[b]=a};a.writePreferences=function(){lpWriteAllPrefs()};a.closePopovers=function(){};var p={},r={},q={},h={};k.LPTabs={get:function(b){if(b.interface){var a=[],c;for(c in h)h[c].tabDetails.interfaceName===b.interface&&a.push(h[c]);return a}if("undefined"!==
typeof b.tabID){if(a=h[b.tabID])return b.callback&&b.callback(a),a;b.callback&&((a=q[b.tabID])||(a=q[b.tabID]=[]),a.push(b.callback))}}};a.initializeRequestFramework=function(b){var a=h[b.tabID],c={tabURL:b.tabURL,tabID:b.tabID,windowID:b.windowID},e=LPMessaging.getNewMessageSourceID(),d=!1,g=function(a){try{return a.frameID=e,b.sendContentScript(a)}catch(c){return!1}},k=function(a){return g({type:"backgroundResponse",data:a})},l=function(){delete p[e];var a=h[c.tabID];a&&(a.removeFrame(e),a.isEmpty()&&
(delete h[c.tabID],delete r[c.tabID]))};return{frameID:e,requestHandler:function(f){switch(f.type){case "backgroundRequest":LPMessaging.handleRequest(Interfaces.BackgroundInterface,f.data,k,{additionalArguments:{tabURL:c.tabURL,tabID:c.tabID,windowID:c.windowID,frameID:e,top:d}});break;case "contentScriptRequest":case "contentScriptResponse":if(0===f.frameID)LPMessaging.handleResponse(f.data);else if(f.frameID){var n=p[f.frameID];n&&n(f)}break;case "initialize":f=f.data;(d=f.top)&&"undefined"!==typeof c.tabID&&
(r[c.tabID]=e);g({type:"initialization",data:{tabID:c.tabID,frameID:e,topFrameID:r[c.tabID],request:f}});if(f.extendFrame){var m=p[e];p[f.extendFrame]=function(a){contentScriptSender(a);m(a)}}else p[e]=g;if(f.interfaceName&&Interfaces.hasOwnProperty(f.interfaceName)){c.interfaceName||(c.interfaceName=f.interfaceName);var n=function(a){return LPMessaging.makeRequest(g,{type:"contentScriptRequest",sourceFrameID:0,data:a})},s=Interfaces.createInstance(Interfaces[f.interfaceName],{instance:f.extendFrame?
a.getTop():null,direct:!1,context:b.context||"background",requestFunction:n});if(("number"===typeof c.tabID||c.tabID)&&f.interfaceName===c.interfaceName&&!f.extendFrame)a||(a=h[c.tabID]=new LPTab(c)),a.addFrame(s,{topWindow:d,frameID:e,contentScriptRequester:n});b.callback&&b.callback(s)}break;case "disconnect":l();break;case "initialized":d&&q[c.tabID]&&(q[c.tabID].forEach(function(b){b(a)}),delete q[c.tabID])}},disconnectHandler:l}}})(LPPlatform,this);
