LPServer.sharing=LPServer.sharing||{};
LPServer.sharing.folder=function(){var h=function(a,b){b.success(a,{sharedFolder:b.params.sharedFolder,shareInfo:b.params.shareInfo})},n=function(a,b,c){if(0<b.length){a.adminuidcnt=b.length;for(var d=0,k=b.length;d<k;++d){var g=b[d],e=new LPServer.ext.RSAKey;LPServer.ext.parsePublicKey(e,g.key);a["adminsharekey"+d]=e.encrypt(LPServer.ext.bin2hex(c));a["adminuid"+d]=g.uid}}},l,q=function(a,b){if(a.success){for(var c={},d=0;void 0!==a["pubkey"+d];)c[a["username"+d]]={uid:a["uid"+d],cgid:a["cgid"+d],
pubkey:a["pubkey"+d]},++d;d=[];if(a.groupname)for(var k=a.groupname.split(","),g=0,e=k.length;g<e;++g)d.push(k[g]);0<d.length&&LPServer.callback(b,"emptyGroups",d);b.success(c)}else b.error()},s={nouser:function(a,b){b.error&&b.error("");LPServer.callback(b,"invite",{emails:a.unknownusers.split(",")})},"default":q,emptygroup:q,noshareerr:function(a,b){b.error(LPServer.ext.translate("Sorry, company policy prohibits use of this feature."))}};l=function(a){LPServer.jsonRequest({url:"share.php",data:{getpubkey:1,
uid:"string"===typeof a.params.userInfo?a.params.userInfo:JSON.stringify(a.params.userInfo),jsonr:1},callbacks:s,userSupplied:a})};var t={ok:function(a,b){var c=LPServer.getAttr(a,"id");b.params.sharedFolder.aid=c;b.params.shareInfo.id=c;b.params.shareInfo.shareid=c;b.params.shareInfo.uid=LPServer.getAttr(a,"uid");h(LPServer.ext.translate("Shared Folder %1 created.",b.params.sharedFolder.group),b)},exceededlimit:function(a,b){b.error(LPServer.ext.translate("Sorry, as a LastPass Premium user, you are limited to one Shared Folder. Please consider using LastPass Enterprise if you would like more."))},
premiumrequired:function(a,b){b.error(LPServer.ext.translate("Sorry, LastPass Premium is required to create a Shared Family Folder"))},alreadyexists:function(a,b){b.error(LPServer.ext.translate("That group already exists."))}},u=function(a,b){var c={};c[b.params.username]={uid:b.params.uid,type:"companyuser"};b.params.superusers=a;l(LPServer.extend({},b,{params:{userInfo:c},success:function(a){if(a=a[b.params.username].pubkey){var c=b.params.sharedFolder,g=b.params.shareInfo=b.params.shareInfo||{},
e={id:0,update:1,newusername:b.params.username+"-"+c.group,name:0===c.group.indexOf("Shared-")?c.group.substring(7):c.group,xmlr:1},j=LPServer.ext.makeRandomPassword(),f=g.key=LPServer.ext.makeKey(e.newusername,j,5E3);e.newhash=LPServer.ext.makeHash(f,j,5E3);j=new LPServer.ext.RSAKey;LPServer.ext.parsePublicKey(j,a);e.sharekey=g.sharekey=j.encrypt(LPServer.ext.bin2hex(f));e.sharename=g.sharename=LPServer.ext.encryptCBC(c.group,f);n(e,b.params.superusers,f);LPServer.xmlRequest({url:"share.php",data:e,
callbacks:t,userSupplied:b})}else LPServer.callback(b,"sharingkeyrequired"),b.error&&b.error("")}}))},v={ok:function(a,b){h(LPServer.ext.translate("Shared Folder %1 was renamed.",b.params.shareInfo.name),b)}},w=function(a,b){b.params.shareInfo.deleted="1";h(LPServer.ext.translate("Shared Folder deleted."),b)},x=function(a,b){b.success(LPServer.ext.translate("Member removed."))},y=function(a,b){b.success(LPServer.ext.translate("Permissions saved."))},r=function(a,b,c){var d={id:b.params.shareInfo.id,
xmlr:1};d[a]=1;LPServer.xmlRequest({url:"share.php",data:d,callbacks:c,userSupplied:b})},z=function(a,b){b.params.shareInfo.download="1";h(LPServer.ext.translate("Shared Folder will now be downloaded."),b)},A=function(a,b){b.params.shareInfo.download="0";h(LPServer.ext.translate("Shared Folder will no longer be downloaded."),b)},B={undeleted:function(a,b){b.params.shareInfo.deleted="0";h(LPServer.ext.translate("Shared Folder restored."),b)}},C={purged:function(a,b){b.success(LPServer.ext.translate("Shared Folder purged."))}},
D=function(a,b){b.success(a.folders)},E={success:function(a,b){b.params.shareInfo.accepted="1";h(LPServer.ext.translate("Shared Folder accepted."),b)}},F={success:function(a,b){b.success(LPServer.ext.translate("Shared Folder rejected."))}},G={success:function(a,b){b.success(LPServer.ext.translate("Shared Folder member reinvited."))}},H={success:function(a,b){b.params.shareInfo.cid=LPServer.getAttr(a,"cid");b.params.shareInfo.outside_enterprise=LPServer.getAttr(a,"outside_enterprise");h(LPServer.ext.translate("Personal Shared Folder moved into Enterprise. You can now adminster the folder."),
b)}},I=function(a,b){var c={id:b.params.shareInfo.id,moveintoenterprise:1,xmlr:1};n(c,a,b.params.shareInfo.key);LPServer.xmlRequest({url:"share.php",data:c,callbacks:H,userSupplied:b})};return{SHARED_FOLDER_NAME_PREFIX:"Shared-",getFolders:function(a){LPServer.jsonRequest({url:"getSharedFolderInfo.php",success:D,userSupplied:a})},getPublicKeys:l,create:function(a){LPServer.jsonRequest({url:"getSuperUserInfo.php",success:u,userSupplied:a})},rename:function(a){a.params.shareInfo.name=a.params.sharedFolder.group.substring(7);
a.params.shareInfo.sharename=LPServer.ext.encryptCBC(a.params.sharedFolder.group,a.params.shareInfo.key);LPServer.xmlRequest({url:"share.php",data:{update:1,rename:1,id:a.params.shareInfo.id,name:a.params.shareInfo.name,sharename:a.params.shareInfo.sharename,xmlr:1},callbacks:v,userSupplied:a})},remove:function(a){LPServer.xmlRequest({url:"share.php",data:{id:a.params.shareInfo.id,"delete":1,xmlr:1},callbacks:{deleted:w},userSupplied:a})},accept:function(a){LPServer.jsonRequest({url:"share.php",data:{folder:a.params.shareInfo.id,
acceptfolder:1,jsonr:1},callbacks:E,userSupplied:a})},reject:function(a){LPServer.jsonRequest({url:"share.php",data:{id:a.params.shareInfo.id,rejectfolder:1,jsonr:1},callbacks:F,userSupplied:a})},addMembers:function(a){l(LPServer.extend({},a,{params:{userInfo:a.params.newMembers},success:function(b){var c={id:a.params.shareInfo.id,update:1,add:1,sharename:a.params.shareInfo.sharename,name:a.params.shareInfo.name,readonly:a.params.readonly?1:0,give:!a.params.hidePasswords?1:0,notify:a.params.notify?
1:0,canadminister:a.params.can_administer?1:0,xmlr:1},d=0,k=0,g=[],e={},j;for(j in b){var f=b[j];if(f.pubkey){var h=c,l="sharekey"+d,m;m=a.params.shareInfo.key;var p=f.pubkey,n=new LPServer.ext.RSAKey;LPServer.ext.parsePublicKey(n,p);m=n.encrypt(LPServer.ext.bin2hex(m));h[l]=m;c["uid"+d]=f.uid;c["cgid"+d]=f.cgid;++d}else c["msfuser"+k]=f.uid,c["msfcgid"+k]=f.cgid,g.push(j),++k;h=e;a:{l=a.params.newMembers;m=void 0;for(m in l)if(p=l[m],"group"===p.type&&f.cgid===p.uid){f=m;break a}f=null}h[f||j]=!0}0<
d+k?LPServer.xmlRequest({url:"share.php",data:c,callbacks:{useradded:function(a,b){0<g.length&&LPServer.callback(b,"noSharingKeyUsers",g);b.success(LPServer.ext.translate("%1 users/groups were invited.",Object.keys(e).length),e)}},userSupplied:a}):a.error()}}))},getMembers:function(a){LPServer.jsonRequest({url:"getSharedFolderMembers.php",data:{shareid:a.params.shareid},userSupplied:a})},removeMember:function(a){var b={id:a.params.shareid,xmlr:1};a.params.msfuser?(b.msfdelete=1,b.msfuser=a.params.uid):
(b.update=1,b.delete=1,b.uid=a.params.uid);LPServer.xmlRequest({url:"share.php",data:b,callbacks:{ok:x},userSupplied:a})},reinviteMember:function(a){var b={reinvite:1,invitee:a.params.uid,folder:a.params.shareid,jsonr:1};"1"===a.params.ent&&(b.ent="on");LPServer.jsonRequest({url:"share.php",data:b,callbacks:G,userSupplied:a})},updateMemberPermissions:function(a){LPServer.xmlRequest({url:"editSharedFolderUsers.php",data:{cmd:"edit",xml:1,shareid:a.params.shareInfo.id,request:JSON.stringify(a.params.updatedPermissions)},
callbacks:{ok:y},userSupplied:a})},getRestrictions:function(a){LPServer.jsonRequest({url:"getSharedFolderRestrictions.php",data:a.params,userSupplied:a})},updateRestrictions:function(a){LPServer.textRequest({url:"share.php",data:{id:a.params.shareid,edit:1,limit:1,aids:a.params.aids,numaids:0<a.params.aids.length?a.params.aids.split(",").length:0,additionaluids:a.params.additionaluids,hidebydefault:a.params.hidebydefault?1:0,uid:a.params.uid,xmlr:1},success:function(){a.success(LPServer.ext.translate("Access restrictions updated."))},
userSupplied:a})},startDownloading:function(a){r("startdownloading",a,{ok:z})},stopDownloading:function(a){r("stopdownloading",a,{ok:A})},restoreDeleted:function(a){LPServer.xmlRequest({url:"share.php",data:{id:a.params.shareInfo.id,undelete:1,xmlr:1},callbacks:B,userSupplied:a})},purgeDeleted:function(a){LPServer.xmlRequest({url:"share.php",data:{id:a.params.shareInfo.id,purge:1,xmlr:1},callbacks:C,userSupplied:a})},convertToEnterprise:function(a){LPServer.jsonRequest({url:"getSuperUserInfo.php",
success:I,userSupplied:a})}}}();
