function postacctsload(){var a,b={};for(a=0;a<g_sites.length;a++)g_sites[a].url=AES.hex2url(g_sites[a].url),"undefined"!=typeof g_sites[a].username&&(g_sites[a].unencryptedUsername=lpmdec_acct(g_sites[a].username,!0,g_sites[a],g_shares)),g_SUPPORTSINGLE||(g_sites[a].pwch=!1),b[g_sites[a].aid]=g_sites[a];g_sites=b;b={};for(a=0;a<g_securenotes.length;a++)b[g_securenotes[a].aid]=g_securenotes[a];g_securenotes=b;b={};for(a=0;a<g_applications.length;a++)g_applications[a].appname=AES.hex2url(g_applications[a].appname),
b[g_applications[a].appaid]=g_applications[a];g_applications=b;for(a=0;a<g_identities.length;a++)g_identities[a].deciname=lpdec(g_identities[a].iname);"function"==typeof get_data_handler&&get_data_handler()}lploggedin=!0;g_server_accts_version=g_local_accts_version=-1;g_identities=[];g_formfills=[];g_pendings=[];base_url="";g_sites={};g_securenotes={};g_premium_exp=g_iscompanyadmin=g_enterpriseuser=0;g_applications={};g_shares=[];g_username_hash=lp_username=g_username=null;g_prompts={};g_maxid=[];
g_groups={};g_prefoverrides={};lp_attaches=[];g_attachversion=[];g_emer_sharers=[];g_emer_sharees=[];g_note_templates=[];g_reminders=[];lpversion="4.0";g_uid=null;g_icons=[];g_bigicons=[];g_identity="undefined"!==typeof iid&&iid?iid:Preferences.get("identity");
function get_accts(){$.ajax({type:"POST",url:base_url+"getaccts.php",data:"mobile=1&b64=1&shap=1&includependingsharedfolders=1&includesharedfolderformfillprofiles=1&includeemergencyaccess=1&requestsrc=newvault&hasplugin="+encodeURIComponent(lpversion)+"&u="+encodeURIComponent(g_username_hash),dataType:"text",success:function(a){a=atob(a);g_sites=[];g_securenotes=[];g_prompts=[];g_formfills=[];g_identities=[];g_pendings=[];g_maxid=[];g_groups=[];g_prefoverrides=[];g_shares=[];g_applications=[];lp_attaches=
[];g_attachversion=[];g_emer_sharers=[];g_emer_sharees=[];g_note_templates=[];g_reminders=[];g_pending_shares=[];parsemobile(a,a.length,100,0,postacctsload,g_sites,g_securenotes,g_prompts,g_formfills,g_identities,null,null,!0,!1,null,g_pendings,null,g_maxid,null,g_groups,g_prefoverrides,lp_rsaprivatekeyhex,g_shares,null,null,null,g_applications,lp_attaches,g_attachversion,null,null,null,g_emer_sharers,g_emer_sharees,null,g_note_templates,g_pending_shares,g_reminders)}})}
function process_icons(a,b){if(a&&(a=a.split(":"),a.length))for(var e=a[0],d=0,f=a.length;d+1<f;d+=2){var c=parseInt(a[d+1]);if(0===e.indexOf("lp")&&0<c){var e=e.substring(2),h=a[d+2].substring(0,c);b?g_bigicons[AES.hex2bin(e)]=h:g_icons[e]=h;e=a[d+2].substring(c)}}}
function get_icons(a){$.ajax({type:"POST",url:base_url+"geticon.php",data:"big=1&versionchrome=1&username="+encodeURIComponent(g_username)+"&domain=all",dataType:"text",success:function(b){"latest"!=b&&"nodata"!=b&&process_icons(b,!0);a&&a()}})}get_personal_linked=function(){for(var a=0;a<g_shares.length;a++)if("undefined"!=typeof g_shares[a].associative&&1==g_shares[a].associative)return g_shares[a].id;return""};get_securityChallengeScore=function(a){a(null)};
getbigicon=function(a){a=lp_gettld_url(a);return"undefined"!=typeof g_bigicons[a]?"data:image/png;base64,"+g_bigicons[a]:null};geticonurlfromrecord=function(a){return is_application(a)?"lps lpapp"+a.fiid:"lps lp"+a.aid};unlock_plug2web=function(){g_plug2web_last_initiated=parseInt((new Date).getTime()/1E3)};get_last_reprompt_time=function(){"undefined"==typeof last_reprompt_time&&(last_reprompt_time=Preferences.get("lastreprompttime"));return last_reprompt_time};
set_last_reprompt_time=function(){last_reprompt_time=(new Date).getTime();Preferences.set("lastreprompttime",last_reprompt_time)};get_key_iterations=function(){return 5E3};(function(){var a={};lpevent=function(b){b="w"+b;a[b]=a.hasOwnProperty(b)?a[b]+1:1};setInterval(function(){if(g_prompts.improve){var b=!1,e;for(e in a){b=!0;break}b&&LPServer.xmlRequest({url:"poll_server.php",data:a});a={}}},1E4)})();
processCS=function(a,b){if("ipcgetdata"==b.cmd&&"undefined"!=typeof g_plug2web_last_initiated&&g_plug2web_last_initiated>=parseInt((new Date).getTime()/1E3)-20){var e=lpParseUri(b.url),d=e.directory.replace(/^\/~[^/]*/,""),e=e.file.replace(/#/,"");"/"==d&&"acctsiframe.php"==e&&(d={cmd:"ipcgotdata",username:g_username,key:btoa(g_local_key),version:lpversion,identity:g_identity,iterations:get_key_iterations(g_username)},b.callback(d))}};openimport=function(){window.open(base_url+"import.php")};
openexport=function(){window.open(base_url+"export.php")};openseccheck=function(){window.open(base_url+"?securitychallenge=1&lpnorefresh=1")};openentconsole=function(){window.open(base_url+"enterprise_home.php")};loggedOut=function(){send_website_event("logoff");setTimeout(function(){top.location.href=base_url+"logout.php?token="+g_token},500)};get_saved_logins=function(){};have_binary=function(){return canopensaveattach};install_binary=function(){window.open(base_url+"installer/")};
addAttach=function(a){addattach_callback=a;attachkey=SHA256(get_random_password());send_website_event("getattach",attachkey)};
openAttach=function(a,b,e){for(var d=0;d<lp_attaches.length;d++)if(lp_attaches[d].id==b){if("undefined"===typeof lp_attaches[d].data||""===lp_attaches[d].data){var f={getattach:lp_attaches[d].storagekey};"undefined"!=typeof g_securenotes[a].sharefolderid&&(f.sharedfolderid=g_securenotes[a].sharefolderid);$.ajax({global:!1,type:"POST",cache:!1,dataType:"json",url:"show_website.php",data:f,success:function(c){""!=c&&(lp_attaches[d].data=c,openAttach(a,b,e))},failure:function(){alert("error")}});break}send_website_event("openattach",
lpdec_acct(g_securenotes[a].attachkey,g_securenotes[a],g_shares),lp_attaches[d].data,lp_attaches[d].mimetype)}};
exportAttachment=function(a,b,e){for(var d=0;d<lp_attaches.length;d++)if(lp_attaches[d].id==b){if("undefined"===typeof lp_attaches[d].data||""===lp_attaches[d].data){var f={getattach:lp_attaches[d].storagekey};"undefined"!=typeof g_securenotes[a].sharefolderid&&(f.sharedfolderid=g_securenotes[a].sharefolderid);$.ajax({global:!1,type:"POST",cache:!1,dataType:"json",url:"show_website.php",data:f,success:function(c){""!=c&&(lp_attaches[d].data=c,exportAttachment(a,b,e))},failure:function(){alert("error")}});
break}send_website_event("saveattach",lpdec_acct(g_securenotes[a].attachkey,g_securenotes[a],g_shares),lp_attaches[d].data,lp_attaches[d].mimetype)}};can_copy_to_clipboard=function(){return!1};fastEncryptAttachments=function(a,b,e){var d=[],f;for(f in b)b.hasOwnProperty(f)&&"undefined"!=typeof b[f]&&d.push({id:b[f].id,data:enccbc(b[f].bytes,a)});e(d)};gotourl=function(a){g_sites[a].url&&(a=g_sites[a].url,a.match(/^[a-z]+?\:\/\//i)||(a="http://"+a),window.open(a))};increment_local_accts_version=function(){g_local_accts_version++};
refreshsites=function(){get_accts()};request_native_messaging=function(){send_website_event("request_native_messaging")};rewritelocalfile=function(){};editAid=function(a,b,e,d){d&&send_website_event("auto_pwchg",a,"0")};switch_identity=function(a){send_website_event("switchidentity",a);g_identity=""+a;Preferences.set("identity",g_identity);document.cookie="iid="+encodeURIComponent(g_identity)};
launch=function(a){g_hasplugin?(document[g_manualformname].aid.value=a,document[g_manualformname].submitbtn.click()):pa(function(){window.open(base_url+"launch.php?id="+encodeURIComponent(a)+"&shareid="+encodeURIComponent("undefined"!=typeof g_sites[a].sharefolderid?g_sites[a].sharefolderid:0)+"&method=web&token="+g_token)},g_prompts.login_site_prompt||g_sites[a].pwprotect)};launchApp=function(a){launch("app"+a)};
check_ident_aid=function(a){if(""===g_identity)return!0;for(var b=0;b<g_identities.length&&g_identities[b].iid!=g_identity;b++);if(b>=g_identities.length)return!1;b=g_identities[b];"undefined"==typeof b.aidarr&&(b.aidarr=b.aids.split(","));return lp_in_array(a,b.aidarr)};
check_ident_appaid=function(a){if(""===g_identity)return!0;for(var b=0;b<g_identities.length&&g_identities[b].iid!=g_identity;b++);if(b>=g_identities.length)return!1;b=g_identities[b];"undefined"==typeof b.appaidarr&&(b.appaidarr=b.appaids.split(","));return lp_in_array(a,b.appaidarr)};
openall=function(a,b){var e=[],d=!1,f;for(f in g_sites)if(check_ident_aid(f)){var c=g_sites[f];c.group==a&&"http://group"!=c.url&&(e.push(c),d=d||c.pwprotect)}if(0!==e.length)if(!b&&(d||g_prompts.login_site_prompt))pa(function(){openall(a,!0)},!0);else for(d=0;d<e.length;d++)window.open(e[d].url)};openAllSites=function(a){for(var b=0;b<a.length;b++)window.open(a[b].url)};
openfavorites=function(){var a=[],b=!1,e;for(e in g_sites){var d=g_sites[e];check_ident_aid(e)&&"1"==d.fav&&(a.push(d),b=b||d.pwprotect)}if(0===a.length)alert(StringUtils.translate("You do not have any Favorites yet."));else if(!skip_reprompt&&(b||g_prompts.login_site_prompt))pa(function(){openfavorites(!0)},!0);else for(b=0;b<a.length;b++)window.open(a[b].url)};
createNewAcct=function(){return{aid:"",name:"",group:"",url:"",tld:"",extra:"",fav:"0",sharedfromuid:"",username:"",unencryptedUsername:"",password:"",pwprotect:0,genpw:0,sn:0,last_touch:lp_get_gmt_timestamp(),autologin:0,never_autofill:0,realm_data:"",fiid:"",custom_js:"",submit_id:"",captcha_id:"",urid:"0",basic_auth:"0",method:"",action:"",individualshare:!1,fields:[]}};
addEmptyGroup=function(a,b,e){var d=issharedfolder(g_shares,a);if(checkreadonly(d)){var f=!1===d?g_local_key:d.sharekey,c=a;if(d){if(!checkreadonly(d))return;c=a.substr(d.decsharename.length+1)}var h=createNewAcct();h.url="http://group";h.group=a;h.aid="0";a="ajax=1&extjs=1&name=&url="+encodeURIComponent(AES.url2hex(h.url))+"&grouping="+encodeURIComponent(lpenc(c,f))+"&username=&password=&extra=&aid=0&openid_url=&isbookmark=0";a+=!1===d?"":"&sharedfolderid="+en(d.id);a+=get_identity_param();a+="&token="+
g_token;$.ajax({type:"POST",url:base_url+"show_website.php",data:a,dataType:"text",success:function(a){a=$(jQuery.parseXML(a)).find("result");a.length&&(h.aid=a.attr("aid"),add_ident_aid(h.aid),b(h),g_sites[h.aid]=h)},failure:e})}};
checkmultiplefolders=function(a){for(var b=!1,e=null,d=!0,f=0;f<a.length;f++){var c=get_record(a[f]);if(c)if(c=issharedfolder(g_shares,c.group))if(b){d=!1;break}else if(null===e)e=c.decsharename;else{if(e!=c.decsharename){d=!1;break}}else if(null!==e){d=!1;break}else b=!0}d||alert(StringUtils.translate("Sorry, you cannot perform this operation on a mix of shared and non-shared folders, or multiple shared folders at once."));return d};
get_record=function(a){return"undefined"==typeof a?null:is_application(a)?g_applications[a.substring(3)]:"undefined"!==typeof g_sites&&"undefined"!==typeof g_sites[a]?g_sites[a]:"undefined"!==typeof g_securenotes&&"undefined"!==typeof g_securenotes[a]?g_securenotes[a]:null};
deleteAid=function(a,b,e,d,f){b=a.split(",");if(!checkmultiplefolders(b))return!1;e="";for(d=a=0;d<b.length;d++){var c=b[d];if(is_application(id)){if(!check_ident_appaid(c))continue}else if(!check_ident_aid(c))continue;var h=get_record(c);if(h){e+=(""===e?"":",")+c;if("undefined"!=typeof h.sharefolderid){a=h.sharefolderid;var g=issharedfolder(g_shares,h.group);if(!checkreadonly(g))return!1}is_application(h)&&"undefined"!=typeof g_applications[h.appaid]?delete g_applications[h.appaid]:"undefined"!=
typeof g_sites[c]?delete g_sites[c]:"undefined"!=typeof g_securenotes[c]&&delete g_securenotes[c]}}if(""===e)return!1;b="ajax=1&extjs=1&delete=1&aid="+en(e);b+=get_identity_param();0!==a&&(b+="&sharedfolderid="+en(a));b+="&token="+g_token;$.ajax({type:"POST",url:base_url+"show_website.php",data:b,dataType:"text"});f&&f();return!0};get_identity_param=function(){return"&iid="+encodeURIComponent(g_identity)};
deleteGroup=function(a,b,e){var d=[],f;for(f in g_sites)g_sites[i].group===a&&d.push(f);for(f in g_securenotes)g_securenotes[i].group===a&&d.push(f);for(f in g_applications)g_applications[i].group===a&&d.push(f);return deleteAid(d.join(","),b,!1,!0,e)};
deleteformfill=function(a,b,e,d,f,c,h){b=!1;for(e=0;e<g_formfills.length;e++)if(g_formfills[e].ffid==a){b=issharedfolder(g_shares,"undefined"!=typeof g_formfills[e].group?g_formfills[e].group:"");g_formfills.splice(e,1);break}a="deleteext=1&ffid="+encodeURIComponent(a);a+=!1===b?"":"&sharedfolderid="+encodeURIComponent(b.id);a+=get_identity_param();a+="&method="+encodeURIComponent(getBG().get_method());h&&(a+="&source="+encodeURIComponent(h));$.ajax({type:"POST",url:base_url+"formfill.php",data:a,
dataType:"text",success:f,failure:c});return!0};
moveSelectedToGroup=function(a,b,e,d,f){e=e||{};e.successCallback=d;e.errorCallback=f;var c=void 0!==e.skipConfirm?e.skipConfirm:!1;b=b.split(",");d=issharedfolder(g_shares,a);var h=null;if(checkreadonly(d)){var g=!1;for(f=0;f<b.length;f++){h=get_record(b[f]);h=issharedfolder(g_shares,h.group);if(!checkreadonly(h)||!checkmove(d,h))return;if((d||h)&&(!d||!(h&&d.id===h.id)))g=!0}if(g){g=[];for(f=0;f<b.length;f++)g[b[f]]=a;moveIntoSharedFolder(d,h,b,g,!1,!1,c,e)}else{c=[];h=[];if(a===StringUtils.translate("favorites"))for(f=
0;f<b.length;f++)(g=get_record(b[f]))&&"0"==g.fav&&(c[c.length]=b[f]);(0<b.length||0<c.length||0<h.length)&&changeGroupAndFavorites(b,c,h,a,d,e)}}};
changeGroupAndFavorites=function(a,b,e,d,f,c){for(var h=e="",g="",j=0;j<a.length;j++){var k=a[j],m=get_record(k);m&&d!=StringUtils.translate("favorites")&&(m.group=d,e+=g+k,g=",")}g="";for(j=0;j<b.length;j++)if(k=b[j],m=get_record(k))m.fav="1",h+=g+k,g=",";g_local_accts_version++;g_server_accts_version++;rewritelocalfile();c&&c.successCallback&&c.successCallback();a=!1===f?g_local_key:f.sharekey;b=d;f&&(b=d.substr(f.decsharename.length+1));d="aids="+encodeURIComponent(e)+"&newfavaids="+encodeURIComponent(h)+
"&oldfavaids="+encodeURIComponent("")+"&newgrp="+encodeURIComponent(lpenc(b,a))+"&xml=1";d+=!1==f?"":"&sharedfolderid="+en(f.id);$.ajax({type:"POST",url:base_url+"groups.php",data:d,dataType:"text"})};
renameGroup=function(a,b){if(a!=StringUtils.translate("favorites")){var e=issharedfolder(g_shares,a);if(!1!=e&&e.decsharename==a)alertfrombg("You cannot rename a top level Shared folder");else{var d=issharedfolder(g_shares,b);if(checkmove(d,e)&&checkreadonly(d)&&checkreadonly(e)){var f=!1==d?g_local_key:d.sharekey,c=b;d&&b.substr(d.decsharename.length+1);if(d||e){var f=[],h=[],g=[g_sites,g_securenotes,g_applications];d&&b.substr(d.decsharename.length+1);for(var j in g){var k=g[j],m;for(m in k)if(k.hasOwnProperty(m)&&
(c=k[m],c.group==a||0==c.group.indexOf(a+"\\\\"))){f[f.length]=get_record_id(c);var l=b;c.group!=a&&0<c.group.indexOf("\\\\")&&(l=b+c.group.substr(c.group.indexOf("\\\\")));h[get_record_id(c)]=l}}moveIntoSharedFolder(d,e,f,h,!1,!1,!1)}else{g=[g_sites,g_securenotes,g_applications];e=[];h=[];l=[];for(j in g)for(m in k=g[j],k)if(k.hasOwnProperty(m))if(c=k[m],c.group==a)c.group=b,"undefined"==typeof e[a]?(l[l.length]=a,h[a]=get_record_id(c)):h[a]+=","+get_record_id(c),c=b,d&&(c=c.substr(d.decsharename.length+
1)),e[a]=c;else if(0==c.group.indexOf(a+"\\\\")){var n=c.group;c.group=c.group.replace(a+"\\\\",b+"\\\\");"undefined"==typeof e[n]?(l[l.length]=n,h[n]=get_record_id(c)):h[n]+=","+get_record_id(c);c=c.group;d&&(c=c.substr(d.decsharename.length+1));e[n]=c}g_local_accts_version++;rewritelocalfile();g="xml=1";for(j=0;j<l.length;j++)g+="&ids"+j+"="+encodeURIComponent(h[l[j]])+"&newgrp"+j+"="+encodeURIComponent(lpenc(e[l[j]],f));g+=!1==d?"":"&sharedfolderid="+en(d.id);$.ajax({type:"POST",url:base_url+"groups.php",
data:g,dataType:"text"})}}}}};get_record_id=function(a){return is_application(a)?"app"+a.appaid:a.aid};is_application=function(a){return"string"==typeof a?0===a.indexOf("app"):a&&"undefined"!=typeof a.appaid};moveIntoSharedFolder_orig=moveIntoSharedFolder;
moveIntoSharedFolder=function(a,b,e,d,f,c,h,g){f=Object.prototype.toString.call(e);if("[object Array]"===f)if("object"===typeof e[0]&&"string"===typeof e[0].aid){f="A,";for(var j in e)e.hasOwnProperty(j)&&"string"==typeof e[j].aid&&(f+=(""==f?"":",")+e[j].aid);e=f}else e="B,"+e.join(",");else if("[object Object]"===f){f="C,";for(j in e)e.hasOwnProperty(j)&&(f+=(""==f?"":",")+j);e=f}else e="[object String]"===f?"D,"+e:"E,"+e;g||(g={});var k=g.successCallback?g.successCallback:function(){};g.successCallback=
function(){k();get_accts()};h&&(g.skipConfirm=!0);h="";for(j in d)if(d.hasOwnProperty(j)){h=d[j];break}return moveIntoSharedFolder_orig(b?b.id:"",a?a.id:"",h,e,"",g,"newvault")};getBG=function(){return this};
saveSite=function(a,b,e,d){a+="&method="+encodeURIComponent(getBG().get_method());a+="&auto=1"+get_identity_param();a+="&token="+g_token;b.postdata=a;b.posturl=base_url+(is_application(b)?"addapp.php":"show_website.php");$.ajax({type:"POST",url:b.posturl,data:a,dataType:"text",success:function(a){a=$(jQuery.parseXML(a));var c=a.find("result");if(c.length){0==b.aid&&(b.aid=c.attr("aid"),add_ident_aid(b.aid));(a=c.attr("attacherror"))&&""!=a&&alert(a);for(var h=0,g=[];null!=c.attr("att_"+h);)g[c.attr("att_"+
h)]=[],g[c.attr("att_"+h)].key=c.attr("attstorekey_"+h),g[c.attr("att_"+h)].size=c.attr("attsize_"+h),h++;if("undefined"!=typeof b.attacharraychanges&&(!a||""==a)){if("undefined"!=typeof b.attacharraychanges.add)for(var j in b.attacharraychanges.add)b.attacharraychanges.add.hasOwnProperty(j);applyattacharraychanges(b.attacharraychanges)}b.sn?g_securenotes[b.aid]=b:g_sites[b.aid]=b;e(b)}else c=a.find("error"),c.length&&d(c.attr("response"))},failure:d})};
saveFields=function(a,b,e,d,f){b+="&method="+encodeURIComponent(getBG().get_method());$.ajax({type:"POST",url:base_url+"fields.php?"+a,data:b,dataType:"text",success:d,failure:f})};
changePassword=function(a,b,e,d,f){for(var c=[],h=0,g=0;g<b.length;g++)if(g_sites[b[g]]){var j=lpmdec_acct(g_sites[b[g]].password,!0,g_sites[b[g]],g_shares);if(j!=a&&(c[c.length]=b[g],g_sites[b[g]].password=lpmenc_acct(a,!0,g_sites[b[g]],g_shares),g_sites[b[g]].fields))for(var k=0;k<g_sites[b[g]].fields.length;k++)"password"==g_sites[b[g]].fields[k].type&&lpmdec_acct(g_sites[b[g]].fields[k].value,!0,g_sites[b[g]],g_shares)==j&&(g_sites[b[g]].fields[k].value=g_sites[b[g]].password);"undefined"!=typeof g_sites[b[g]].sharefolderid&&
(h=g_sites[b[g]].sharefolderid)}b=c;if(0!==b.length){c="xml=1";j=[];for(g=0;g<b.length;g++){k=0<g?g:"";c+="&username"+k+"=dummy";c+="&password"+k+"="+encodeURIComponent(lpenc_acct(a,g_sites[b[g]],g_shares));c+="&id"+k+"="+encodeURIComponent(b[g]);try{lp_in_array(g_sites[b[g]].tld,j)||(j[j.length]=g_sites[b[g]].tld)}catch(m){}}try{for(g in g_sites)if(g_sites[g].genpw&&lp_in_array(g_sites[g].tld,j)&&lpmdec_acct(g_sites[g].password,!0,g_sites[g],g_shares)==a){c+="&delgenpwaid="+encodeURIComponent(g);
break}}catch(l){}0!=h&&(c+="&sharedfolderid="+en(h));"undefined"!=typeof e&&e&&(c+="&autochange=1");a={aid:0};a.postdata=c;a.url=base_url+"change_pw.php";a.handler=d;a.param={aid:a.aid,postdata:a.postdata,url:a.url,handler:a.handler};a.successCallback=d;$.ajax({type:"POST",url:a.url,data:a.postdata,dataType:"text",success:function(a){a=$(jQuery.parseXML(a)).find("ok");if(a.length)for(var b="";a.attr("id"+b);){var e=g_sites[a.attr("id"+b)],c=crypto_atob(a.attr("newpassword"+b)),f=crypto_atob(a.attr("oldpassword"+
b));e.password=c;if(e.fields)for(var g=0;g<e.fields.length;++g){var h=e.fields[g];if("password"==h.type&&(h.value==f||lpmdec_acct(h.value,!0,e,g_shares)==lpmdec_acct(f,!0,e,g_shares)))h.value=c}b=""===b?1:++b}d()},failure:f})}};
addeditformfill=function(a,b,e,d){var f;f="&method="+encodeURIComponent(getBG().get_method());for(var c in a)f+=(""==f?"":"&")+c+"="+en(a[c]);a=!1;"undefined"!=typeof b.group&&""!=b.group&&(a=issharedfolder(g_shares,b.group));f+=!1==a?"":"&sharedfolderid="+en(a.id);f+=get_identity_param();$.ajax({type:"POST",url:base_url+"formfill.php",data:f,dataType:"text",success:function(a){var d=$(jQuery.parseXML(a)).find("result");if(d.length){d.attr("msg");a=d.attr("ffid");add_ident_ffid(a);var c=d.attr("cfids");
d.attr("accts_version");for(var d=[],f=""==c?[]:c.split(","),m=0,c=1;"undefined"!=typeof b["customfield"+c+"cfid"];++c){var l={};l.cfid=0!=b["customfield"+c+"cfid"]?b["customfield"+c+"cfid"]:m<f.length?f[m++]:0;l.text=b["customfield"+c+"text"];l.value=b["customfield"+c+"value"];l.alttext=b["customfield"+c+"alttext"];(""!=l.text||""!=l.value||""!=l.alttext)&&d.push(l)}f=b.cmd;delete b.cmd;delete b.deleteext;for(c=1;"undefined"!=typeof b["customfield"+c+"cfid"];++c)delete b["customfield"+c+"cfid"],
delete b["customfield"+c+"text"],delete b["customfield"+c+"value"],delete b["customfield"+c+"alttext"];b.custom_fields=d;if("add"==f)b.ffid=a,g_formfills.push(b);else for(c=0;c<g_formfills.length;++c)if(a==g_formfills[c].ffid){g_formfills[c]=b;break}e&&e(b)}},failure:d});return!0};add_ident_aid=function(a){if(g_identity){for(var b=null,e=0;e<g_identities.length;e++)if(g_identities[e].iid===g_identity){b=g_identities[e];break}b&&(b.aids&&(b.aids+=","),b.aids+=a,b.aidarr=b.aids.split(","))}};
add_ident_ffid=function(a){if(g_identity){for(var b=null,e=0;e<g_identities.length;e++)if(g_identities[e].iid==g_identity){b=g_identities[e];break}b&&(b.ffids&&(b.ffids+=","),b.ffids+=a,b.ffidarr=b.ffids.split(","))}};db_prepend=function(a){return a};localStorage_setItem=function(a,b){try{return localStorage.setItem(a,b),!0}catch(e){return!1}};localStorage_getItem=function(a){try{return localStorage.getItem(a)}catch(b){return null}};openURL=function(a){window.open(a)};canLaunchApplication=function(){return!1};
singlefactor_reprompt=function(a){a()};isOffline=function(){return!1};get_method=function(){return"web"};lpReportError=function(){errorCount=0;return function(a){!0===g_prompts.improve&&(++errorCount,100<errorCount||$.ajax({url:base_url+"error.php",type:"POST",data:{msg:"error: website("+lpversion+") errors("+errorCount+"): "+a}}))}}();loglogin=function(){};function refreshGroupNames(){}VaultToggle={toggleVault3_0:function(){}};
