LPDialog=function(d){var g="",m=[],h={},n=["newvaultGlobal","dialog","buttons"],p=["dialog","dialogFields"],j,f=null,s=function(a,c){for(var b=0,t=a.length;b<t;++b){var r=a[b].getAttribute(c);r&&(f[r]=!0)}};j={loadFile:function(a,c){null===f&&j.initialize();var b=g+LPPlatform.getResourcePath(a.name);void 0===f[b]?(f[b]=!0,h[b]=[c],a.load(function(){var a=h[b];delete h[b];for(var c=0,d=a.length;c<d;++c)a[c]()})):h[b]?h[b].push(c):c()},initialize:function(){null===f&&(f={},s(d.getElementsByTagName("link"),
"href"),s(d.getElementsByTagName("script"),"src"))}};var e=function(){this.files=[];this.addedFiles={}};e.prototype.load=function(a){var c=0,b=this.files,d=function(){++c;c===b.length?a&&a():j.loadFile(b[c],d)};0===c&&0<b.length&&j.loadFile(b[0],d)};e.prototype.addFile=function(a){void 0===this.addedFiles[a.name]&&(this.files.push(a),this.addedFiles[a.name]=!0)};e.prototype.addFiles=function(a){if(a){a=[].concat(a);for(var c=0,b=a.length;c<b;++c)this.addFile(a[c])}};var u=function(a){a.indexOf(".js")!==
a.length-3&&(a=a+=".js");this.name=a;this.load=function(c){var b=d.createElement("script");b.setAttribute("type","text/javascript");b.setAttribute("src",g+LPPlatform.getResourcePath(a));LPPlatform.addEventListener(b,"load",c);d.body.appendChild(b)}},v=function(a){a.indexOf(".css")!==a.length-4&&(a=a+=".css");this.name=a;this.load=function(c){var b=d.createElement("link");b.setAttribute("type","text/css");b.setAttribute("rel","stylesheet");b.setAttribute("href",g+LPPlatform.getResourcePath(a));LPPlatform.addEventListener(b,
"load",c);d.body.appendChild(b)}},k=function(a){e.call(this);a=a?n.concat(a):n;for(var c=0,b=a.length;c<b;++c)this.addFile(a[c])};k.prototype=Object.create(e.prototype);k.prototype.constructor=k;k.prototype.addFile=function(a){a&&e.prototype.addFile.call(this,new v(a))};k.prototype.load=function(a){for(var c=0,b=this.files,d=function(){++c===b.length&&a()},e=0,g=b.length;e<g;++e)j.loadFile(b[e],d)};var l=function(a){e.call(this);a=a?p.concat(a):p;for(var c=0,b=a.length;c<b;++c)this.addFile(a[c])};
l.prototype=Object.create(e.prototype);l.prototype.constructor=l;l.prototype.addFile=function(a){a&&e.prototype.addFile.call(this,new u(a))};return{DialogLoader:function(a){var c=!1,b=null,d=new l(a.js),e=new k(a.css);this.parentElementID=a.parentElementID;this.type=a.type;var f=function(a,b){var c,d,e={},q=a?[].concat(a):[];b=b?[].concat(b):[];c=0;for(d=q.length;c<d;++c)e[q[c]]=!0;c=0;for(d=b.length;c<d;++c)e.hasOwnProperty(b[c])||q.push(b[c]);return q};this.extend=function(b){return new LPDialog.DialogLoader({id:b.id||
a.id,htmlSource:f(a.htmlSource,b.htmlSource),css:f(a.css,b.css),js:f(a.js,b.js),type:b.type||a.type,parentElementID:b.parentElementID||a.parentElementID})};this.loadedJS=function(){return c};this.getID=function(){return a.id};var h,j=this;h=function(d){b=new window[a.type](j);c=!0;d(b)};this.loadJS=function(a){d?(Topics.get(Topics.DIALOG_LOADING).publish(),d.load(function(){h(a)})):h(a)};var n=function(b,c,d,e){d<c.length?LPPlatform.getHTML(g+a.htmlSource[d],function(a){a=$(a);a.find("[dialogsection]").addBack("[dialogsection]").each(function(){var a=
this.getAttribute("dialogsection"),a=b.find("[dialogsection="+a+"]");a.before(this);a.remove()});a.find("[dialogsectionbefore]").addBack("[dialogsectionbefore]").each(function(){var a=this.getAttribute("dialogsectionbefore");b.find("[dialogsection="+a+"]").before(this)});a.find("[dialogsectionafter]").addBack("[dialogsectionafter]").each(function(){var a=this.getAttribute("dialogsectionafter");b.find("[dialogsection="+a+"]").after(this)});a.find("[dialogsectionappend]").addBack("[dialogsectionappend]").each(function(){var a=
this.getAttribute("dialogsectionappend");b.find("[dialogsection="+a+"]").append(this)});a.find("[dialogsectionprepend]").addBack("[dialogsectionprepend]").each(function(){var a=this.getAttribute("dialogsectionprepend");b.find("[dialogsection="+a+"]").prepend(this)});n(b,c,++d,e)}):e()},p=function(b,c){var d=function(){var a=b.find("img");if(0<a.length){var d,e=0;d=function(){++e;e===a.length&&c()};for(var f=0,g=a.length;f<g;++f)$(a[f]).bind("load",d)}else c()};a.htmlSource instanceof Array?LPPlatform.getHTML(g+
a.htmlSource[0],function(c){b.html(c);n(b,a.htmlSource,1,d)}):LPPlatform.getHTML(g+a.htmlSource,function(a){b.html(a);d()})};this.load=function(a,b){e?e.load(function(){p(a,b)}):p(a,b)};this.open=function(){this.loadedJS()?b.open.apply(b,arguments):(m.push(this),this.loadJS(function(a,c){return function(){b.open.apply(b,c);for(var d=0,e=m.length;d<e;++d)m[d]===a&&m.splice(d,1)}}(this,arguments)))};this.close=function(){b&&b.close.apply(b,arguments)};this.getDialog=function(){return b}},JSFileSet:l,
CSSFileSet:k,getPendingCount:function(){return m.length},getDialogs:function(){var a=[],c;for(c in dialogs)a.push(dialogs[c]);return a},setBaseURL:function(a){g=a}}}(document);
dialogs={site:new LPDialog.DialogLoader({id:"siteDialog",htmlSource:"siteDialog.html",css:["buttons","dialog","siteDialog","passwordMeter"],js:"selectDropdown typeaheadDropdown dialog dialogWithGroupInput editableFieldsDialog siteDialog passwordMeter bloodhound bloodhoundDropdown".split(" "),type:"SiteDialog"}),note:new LPDialog.DialogLoader({id:"noteDialog",htmlSource:"noteDialog.html",css:["buttons","dialog","noteDialog"],js:["selectDropdown","typeaheadDropdown","dialog","dialogWithGroupInput",
"noteDialog"],type:"NoteDialog"}),customNoteTemplate:new LPDialog.DialogLoader({id:"customNoteTemplateDialog",htmlSource:"customNoteTemplateDialog.html",css:["buttons","dialog","customNoteTemplateDialog"],js:["selectDropdown","typeaheadDropdown","dialog","customNoteTemplateDialog"],type:"CustomNoteTemplateDialog"}),formFill:new LPDialog.DialogLoader({id:"formFillDialog",htmlSource:"formFillDialog.html",css:["buttons","dialog","formFillDialog"],js:["selectDropdown","typeaheadDropdown","dialog","formFillDialog",
"phoneFormatDropdown"],type:"FormFillDialog"}),acceptShare:new LPDialog.DialogLoader({id:"acceptShareDialog",htmlSource:"acceptRejectShareDialog.html",css:["buttons","dialog","acceptRejectShareDialog"],js:["selectDropdown","typeaheadDropdown","dialog","dialogWithGroupInput","acceptRejectShareDialog"],type:"AcceptShareDialog"}),share:new LPDialog.DialogLoader({id:"shareDialog",htmlSource:"shareDialog.html",css:["buttons","dialog","shareDialog","containerSelectionDialog","vaultItem"],js:"selectDropdown typeaheadDropdown dialog shareDialog bloodhound bloodhoundDropdown vaultItemTypeahead sharingModel".split(" "),
type:"ShareDialog"}),identity:new LPDialog.DialogLoader({id:"identityDialog",htmlSource:"identityDialog.html",css:["buttons","dialog","containerSelectionDialog","identityDialog"],js:["dialog","containerSelectionDialog","identityDialog"],type:"IdentityDialog"}),sharedfolderAccess:new LPDialog.DialogLoader({id:"sharedFolderAccessDialog",htmlSource:"sharedFolderAccessDialog.html",css:["buttons","dialog","containerSelectionDialog","sharedFolderAccessDialog"],js:["dialog","containerSelectionDialog","sharedFolderAccessDialog"],
type:"SharedFolderAccessDialog"}),sharedFolder:new LPDialog.DialogLoader({id:"sharedFolderDialog",htmlSource:"sharedFolderDialog.html",css:["buttons","dialog","sharedFolderDialog"],js:"dialog sharedFolderDialog bloodhound selectDropdown typeaheadDropdown bloodhoundDropdown".split(" "),type:"SharedFolderDialog"}),createSharedFolder:new LPDialog.DialogLoader({id:"createSharedFolderDialog",htmlSource:"createSharedFolderDialog.html",css:["buttons","dialog"],js:["dialog","dialogWithGroupInput","folderDialog"],
type:"CreateSharedFolderDialog"}),createCreditMonitoring:new LPDialog.DialogLoader({id:"createCreditMonitoringDialog",htmlSource:"createCreditMonitoringDialog.html",css:["buttons","dialog","createCreditMonitoringDialog"],js:["dialog","createCreditMonitoringDialog"],type:"CreateCreditMonitoringDialog"}),generatePassword:new LPDialog.DialogLoader({id:"generatePasswordDialog",htmlSource:"generatePasswordDialog.html",css:["buttons","dialog","generatePasswordDialog","passwordMeter"],js:["dialog","generatePasswordDialog",
"selectDropdown","passwordMeter"],type:"GeneratePasswordDialog"}),login:new LPDialog.DialogLoader({id:"loginDialog",htmlSource:"loginDialog.html",css:["loginDialog"],js:["loginDialog","capslockstate"],type:"LoginDialog"}),reprompt:new LPDialog.DialogLoader({id:"repromptDialog",htmlSource:"repromptDialog.html",css:["repromptDialog"],js:["repromptDialog"],type:"RepromptDialog"}),createAccount:new LPDialog.DialogLoader({id:"createAccountDialog",htmlSource:"createAccountDialog.html",css:["buttons","dialog",
"createAccountDialog","passwordMeter"],js:["dialog","createAccountDialog","selectDropdown","passwordMeter"],type:"CreateAccountDialog"}),folder:new LPDialog.DialogLoader({id:"folderDialog",type:"FolderDialog",css:["buttons","dialog"],js:["dialog","selectDropdown","typeaheadDropdown","dialogWithGroupInput","folderDialog"],htmlSource:"folderDialog.html"}),fieldHistory:new LPDialog.DialogLoader({id:"fieldHistoryDialog",htmlSource:"fieldHistoryDialog.html",css:["buttons","dialog","fieldHistoryDialog"],
js:["dialog","fieldHistoryDialog"],type:"FieldHistoryDialog"}),linkAccount:new LPDialog.DialogLoader({id:"linkAccountDialog",htmlSource:"linkAccountDialog.html",css:["buttons","dialog","linkAccountDialog"],js:["dialog","linkAccountDialog"],type:"LinkAccountDialog"}),confirmation:new LPDialog.DialogLoader({id:"confirmationDialog",htmlSource:"confirmationDialog.html",css:["buttons","dialog"],js:["dialog","confirmationDialog"],type:"ConfirmationDialog"}),alert:new LPDialog.DialogLoader({id:"alertDialog",
htmlSource:"alertDialog.html",css:["buttons","dialog"],js:["dialog","confirmationDialog"],type:"AlertDialog"}),enterpriseTrial:new LPDialog.DialogLoader({id:"enterpriseTrialDialog",htmlSource:"enterpriseTrialDialog.html",css:["buttons","dialog"],js:["dialog","enterpriseTrialDialog"],type:"EnterpriseTrialDialog"}),denyEmergencyAccess:new LPDialog.DialogLoader({id:"denyEmergencyAccessDialog",htmlSource:"denyEmergencyAccessDialog.html",css:["buttons","dialog"],js:["dialog","denyEmergencyAccessDialog"],
type:"DenyEmergencyAccessDialog"}),verifyEmail:new LPDialog.DialogLoader({id:"verifyEmailDialog",htmlSource:"verifyEmailDialog.html",css:["buttons","dialog"],js:["dialog","verifyEmailDialog"],type:"VerifyEmailDialog"}),application:new LPDialog.DialogLoader({id:"applicationDialog",htmlSource:"applicationDialog.html",css:["buttons","dialog","passwordMeter"],js:"dialog dialogWithGroupInput editableFieldsDialog passwordMeter applicationDialog selectDropdown typeaheadDropdown".split(" "),type:"ApplicationDialog"}),
chooseProfile:new LPDialog.DialogLoader({id:"chooseProfileDialog",htmlSource:"chooseProfileDialog.html",css:["buttons","dialog","chooseProfileDialog"],js:["dialog","chooseProfileDialog"],type:"ChooseProfileDialog"}),vaultItemSelect:new LPDialog.DialogLoader({id:"vaultItemSelectDialog",htmlSource:"vaultItemSelectDialog.html",css:["buttons","dialog","vaultItem"],js:["dialog","vaultItemSelectDialog"],type:"VaultItemSelectDialog"}),inviteFriends:new LPDialog.DialogLoader({id:"inviteFriendsDialog",htmlSource:"inviteFriendsDialog.html",
css:["buttons","dialog"],js:["dialog","inviteFriendsDialog"],type:"InviteFriendsDialog"}),addEmergencyAccess:new LPDialog.DialogLoader({id:"addEmergencyAccessDialog",htmlSource:"addEmergencyAccessDialog.html",css:["buttons","dialog"],js:["dialog","addEmergencyAccessDialog"],type:"AddEmergencyAccessDialog"}),upgradePremium:new LPDialog.DialogLoader({id:"upgradePremiumDialog",htmlSource:"upgradePremiumDialog.html",css:["buttons","dialog"],js:["dialog","upgradePremiumDialog"],type:"UpgradePremiumDialog"}),
sharingKey:new LPDialog.DialogLoader({id:"sharingKeyDialog",htmlSource:"sharingKeyDialog.html",css:["buttons","dialog"],js:["dialog","sharingKeyDialog"],type:"SharingKeyDialog"}),addFormField:new LPDialog.DialogLoader({id:"addFormFieldDialog",htmlSource:"addFormFieldDialog.html",js:["dialog","dialogWithGroupInput","editableFieldsDialog"],type:"AddFormFieldDialog"})};dialogs.changePassword=dialogs.vaultItemSelect.extend({id:"changePasswordDialog",js:"changePasswordDialog",type:"ChangePasswordDialog"});
$.extend(dialogs,{notification:new LPDialog.DialogLoader({id:"notificationDialog",htmlSource:"notificationDialog.html",css:["buttons","dialog","notificationDialog"],js:["dialog","notificationDialog"],type:"NotificationDialog"}),duplicatePassword:new LPDialog.DialogLoader({id:"duplicatePasswordDialog",htmlSource:"duplicatePasswordDialog.html",css:["buttons","dialog","duplicatePasswordDialog"],js:["dialog","duplicatePasswordDialog"],type:"DuplicatePasswordDialog"}),weakPassword:new LPDialog.DialogLoader({id:"weakPasswordDialog",
htmlSource:"weakPasswordDialog.html",css:["buttons","dialog","weakPasswordDialog"],js:["dialog","weakPasswordDialog"],type:"WeakPasswordDialog"}),preferences:new LPDialog.DialogLoader({id:"preferencesDialog",htmlSource:"preferencesDialog.html",css:["buttons","dialog","preferencesDialog"],js:["dialog","preferencesDialog"],type:"PreferencesDialog"}),introTutorialWelcome:new LPDialog.DialogLoader({id:"introTutorialWelcomeDialog",htmlSource:"IntroTutorial/introTutorialWelcomeDialog.html",css:["buttons",
"dialog","lpGrid","IntroTutorial/introTutorialHelpDialog","IntroTutorial/introTutorial"],js:["dialog","IntroTutorial/introTutorialHelpDialog","IntroTutorial/introTutorialWelcomeDialog"],type:"IntroTutorialWelcomeDialog"}),introTutorialSelectSite:new LPDialog.DialogLoader({id:"introTutorialSelectSiteDialog",htmlSource:"IntroTutorial/introTutorialSelectSiteDialog.html",css:["buttons","dialog","lpGrid","IntroTutorial/introTutorialHelpDialog","IntroTutorial/introTutorial"],js:["dialog","IntroTutorial/introTutorialHelpDialog",
"IntroTutorial/introTutorialSelectSiteDialog"],type:"IntroTutorialSelectSiteDialog"}),introTutorialComplete:new LPDialog.DialogLoader({id:"introTutorialCompleteDialog",htmlSource:"IntroTutorial/introTutorialCompleteDialog.html",css:["buttons","dialog","lpGrid","IntroTutorial/introTutorialHelpDialog","IntroTutorial/introTutorial"],js:["dialog","IntroTutorial/introTutorialHelpDialog","IntroTutorial/introTutorialCompleteDialog"],type:"IntroTutorialCompleteDialog"}),createAccountSimple:new LPDialog.DialogLoader({id:"createAccountDialog",
htmlSource:"extensionCreateAccountDialog.html",css:"extensionDialogSimple buttons dialog lpGrid extensionCreateAccount passwordMeter backgroundOverlay".split(" "),js:"createAccountDialog dialog extensionCreateAccount selectDropdown passwordMeter fieldValidator backgroundOverlay fieldToolTip emailToolTip".split(" "),type:"ExtensionCreateAccount"})});
dialogs.login=dialogs.login.extend({htmlSource:"extensionLoginDialog.html",css:"extensionLoginDialog",js:["extensionLoginDialog","selectDropdown","typeaheadDropdown"],type:"ExtensionLoginDialog"});dialogs.siteTutorial=dialogs.site.extend({css:"IntroTutorial/introTutorialHelpDialog",js:["IntroTutorial/introTutorialHelpDialog","extensionSiteTutorialDialog"],type:"ExtensionSiteTutorialDialog"});
(function(){var d=new LPDialog.DialogLoader({id:"loginDialog",htmlSource:"extensionLoginDialogSimple.html",css:["loginDialog","extensionDialogSimple","extensionLoginDialogBase","lpGrid","backgroundOverlay"],js:"loginDialog extensionLoginDialog capslockstate extensionLoginDialogSimple selectDropdown typeaheadDropdown fieldValidator backgroundOverlay".split(" "),type:"ExtensionLoginDialogSimple"});dialogs.loginSimple=d.extend({css:["extensionLoginDialogSimple"]});dialogs.loginTab=d.extend({css:["extensionLoginDialogTab"]})})();
