DialogInput=function(){var v=function(a){var b={},g;for(g in a)a.hasOwnProperty(g)&&(b[g]=a[g]instanceof k?v(a[g]):!0);return b},k=function(){};k.prototype.validate=function(){var a=!0,b;for(b in this)this.hasOwnProperty(b)&&(a=this[b].validate()&&a);return a};k.prototype.clear=function(){for(var a in this)this.hasOwnProperty(a)&&this[a].clear()};k.prototype.clearErrors=function(){for(var a in this)this.hasOwnProperty(a)&&this[a].clearErrors()};k.prototype.adjustView=function(){for(var a in this)if(this.hasOwnProperty(a)){var b=
this[a];"function"===typeof b.adjustView&&b.adjustView()}};k.prototype.getValue=function(a){var b={},g;for(g in this)this.hasOwnProperty(g)&&(b[g]=this[g].getValue(a));return b};k.prototype.setValue=function(a){for(var b in this)this.hasOwnProperty(b)&&this[b].setValue(void 0===a[b]?"":a[b])};k.prototype.hasError=function(){for(var a in this)if(this.hasOwnProperty(a)&&this[a].hasError())return!0;return!1};var s=function(a){this.items={};this.groupName=a};s.prototype.getValue=function(){for(var a in this.items)if(this.items[a].prop("checked"))return a};
s.prototype.setValue=function(a){if(a=this.items[a])a.prop("checked",!0);else for(var b in this.items)this.items[b].prop("checked",!1)};s.prototype.addRadioInput=function(a){var b=a.attr("value");if(b){if(a.attr("name")!==this.groupName)throw"RadioGroup member must have the same name attribute as the other radio inputs in the group (based on dialogField)!";this.items[b]=a}else throw"RadioGroup member must have a value!";};var j=function(){this._errors=[];this._errorElement=null;this._hasError=!1};
j.prototype.postValidate=function(){this._hasError=0<this._errors.length};j.prototype.hasError=function(){return this._hasError};j.prototype.buildError=function(a){a={collection:this.input,dialog:a,alignTop:"SELECT"===this.input.prop("nodeName").toUpperCase()};"checkbox"===this.input.attr("type")&&(a.collection=a.collection.add(this.input.next()),a.static=!0);return LPTools.buildErrorElement(a)};j.prototype.addError=function(a,b){b=b||this.dialog;if(!LPTools.getOption(b.validateOptions,"errorsOnly",
!1)||this.hasError())this._hasError=!0,this._errors.push(a),this._errorElement||(this._errorElement=this.buildError(b)),LPTools.buildErrorMessage(this._errorElement,this._errors)};j.prototype.clearErrors=function(){this._errors=[];LPTools.removeErrorElements(this._errorElement);this._errorElement=null};j.prototype.clear=function(){this._hasError=!1};var c=function(a,b){j.call(this);this.setElement(a);this.disabled=!1;this.dialog=b;this.radioGroup=null};c.prototype=Object.create(j.prototype);c.prototype.constructor=
c;c.prototype.getNativeElement=function(){return this.getElement().get(0)};c.prototype.getElement=function(){return this.input};c.prototype.setElement=function(a){this.input=a instanceof $?a:$(a)};c.prototype.default=function(){this.setValue("")};c.prototype.validate=function(){return!0};c.prototype.focus=function(){this.input.focus()};c.prototype.disable=function(){this.disabled||(this.disabled=!0,this.input.prop("disabled",!0))};c.prototype.enable=function(){this.disabled&&(this.disabled=!1,this.input.prop("disabled",
!1))};c.prototype.clear=function(){j.prototype.clear.apply(this,arguments);if(this.input){switch(this.input.attr("type")){case "checkbox":case "radio":this.setValue(!1);break;default:this.setValue("")}this.input.passwordShown&&this.input.hidePassword()}};c.prototype.getValue=function(){switch(this.input.attr("type")){case "radio":if(this.radioGroup)return this.radioGroup.getValue();case "checkbox":return this.input.prop("checked");default:return this.input.val()||""}};c.prototype.setValue=function(a){var b=
this.getValue();switch(this.input.attr("type")){case "radio":if(this.radioGroup)return this.radioGroup.setValue(a);case "checkbox":this.input.prop("checked",a);break;default:this.input.val(a)}b!==a&&this.fireOnChange()};c.prototype.addRadioInput=function(a,b){null===this.radioGroup&&(this.radioGroup=new s(a),this.radioGroup.addRadioInput(this.input));this.radioGroup.addRadioInput(b instanceof $?b:$(b))};c.prototype.fireOnChange=function(){if(this.onChangeCallback)this.onChangeCallback(this.getValue())};
c.prototype.onChange=function(a){this.onChangeCallback=a;var b=this;b.getElement().bind("change",function(){b.fireOnChange()})};c.prototype.adjustView=function(){};var q=function(a,b){c.apply(this,arguments)};q.prototype=Object.create(c.prototype);q.prototype.constructor=q;q.prototype.setOptions=function(a){this.input.empty();for(var b=0,g=a.length;b<g;++b){var c=a[b],e=c.value,d=c.label;"string"===typeof c&&(e=d=c);this.input.append(LPTools.createElement("option",{value:e},d))}};var e=function(a,
b){c.call(this);this.field=a;this.label=void 0===b?a:b?Strings.translateString(b):null};e.prototype=Object.create(c.prototype);e.prototype.constructor=e;e.prototype.build=function(){var a="settingLabel";this.isTopAlign()&&(a+=" topAlign");var b=LPTools.createElement("tr"),c=LPTools.createElement("td");this.label&&b.appendChild(LPTools.createElement("td",a,this.label));b.appendChild(c);c.appendChild(this.buildInput());return b};e.prototype.buildInput=function(){var a=this.buildInputElement();this.setElement(a);
return a};e.prototype.isTopAlign=function(){return!1};var m=function(a,b,c){e.call(this,a,b);this.options=c;this.adjusted=!1};m.prototype=Object.create(e.prototype);m.prototype.constructor=m;m.prototype.buildInputElement=function(){return LPTools.createElement("input",{"class":"dialogInput",type:"text"})};m.prototype.buildInput=function(){var a=e.prototype.buildInput.apply(this,arguments),b=LPTools.getOption(this.options,"inputButton",null);if(b){var c=LPTools.createElement("div","relative");c.appendChild(a);
this.inputButtonElement=LPTools.createElement("button","dialogInputButton",b);var d=LPTools.getOption(this.options,"inputButtonHandler",null);if(d){var f=this;LPPlatform.addEventListener(f.inputButtonElement,"click",function(){d.apply(f)})}c.appendChild(this.inputButtonElement);return c}return a};m.prototype.adjustView=function(){if(!this.adjusted){var a=parseInt(this.input.css("padding-right"));this.input.css("padding-right",a+$(this.inputButtonElement).outerWidth());this.adjusted=!0}};var r=function(a,
b){e.call(this,a,b)};r.prototype=Object.create(e.prototype);r.prototype.constructor=r;r.prototype.buildInput=function(){this.setElement(LPTools.createElement("input",{"class":"dialogInput",type:"password"}));this.input.LP_addPasswordEye({includeGenerateButton:!0});var a=this.input.parents();return a[a.length-1]};var p=function(a,b){e.call(this,a,b)};p.prototype=Object.create(e.prototype);p.prototype.constructor=p;p.prototype.buildInputElement=function(){return LPTools.createElement("textarea","dialogInput")};
p.prototype.isTopAlign=function(){return!0};for(var n="January February March April May June July August September October November December".split(" "),l="01 02 03 04 05 06 07 08 09 10 11 12".split(" "),f=[],d=0,t=n.length;d<t;++d){var u=d+1;f.push((10>u?"0"+u:u)+" - "+Strings.translateString(n[d]))}for(var w=[{value:"",label:""}],d=0,t=n.length;d<t;++d)w.push({value:n[d],label:f[d]});for(var x=[{value:"",label:""}],d=0,n=n.length;d<n;++d)x.push({value:l[d],label:f[d]});var h=function(a,b){e.call(this,
a,LPTools.getOption(b,"label",void 0));this.includeDay=LPTools.getOption(b,"includeDay",!0)};h.prototype=Object.create(e.prototype);h.prototype.constructor=h;h.prototype.buildInputElement=function(){var a="";this.includeDay||(a="monthYearDate");var a=LPTools.createElement("div",a),b=LPTools.createElement("div","dateInputMonth");this.monthInput=LPTools.createSelectElement(this.getMonthOptions());this.dayInput=null;this.includeDay&&(this.dayInput=LPTools.createElement("input",{"class":"dialogInput dateInputDay",
type:"text"}));this.yearInput=LPTools.createElement("input",{"class":"dialogInput dateInputYear",type:"text"});b.appendChild(this.monthInput);a.appendChild(b);null!==this.dayInput&&a.appendChild(this.dayInput);a.appendChild(this.yearInput);return a};h.prototype.clear=function(){this.monthInput&&(this.monthInput.value="");this.dayInput&&(this.dayInput.value="");this.yearInput&&(this.yearInput.value="")};h.prototype.getValue=function(){return this.toString()};h.prototype.setValue=function(a){a=this.parse(a);
var b="",c="",d="";a&&(b=a.shift(),2===a.length&&(c=a.shift()),d=a.shift());this.monthInput.value=b;this.includeDay&&(this.dayInput.value=c);this.yearInput.value=d};l=function(a,b){h.call(this,a,b)};l.prototype=Object.create(h.prototype);l.prototype.constructor=l;l.prototype.toString=function(){var a=this.monthInput.value;this.dayInput&&(a+=","+this.dayInput.value);return a+=","+this.yearInput.value};l.prototype.parse=function(a){return a?a.split(","):null};l.prototype.getMonthOptions=function(){return w};
f=function(a,b){h.call(this,a,b)};f.prototype=Object.create(h.prototype);f.prototype.constructor=f;f.prototype.toString=function(){var a=this.yearInput.value+"-"+this.monthInput.value;this.includeDay&&(a+="-"+this.dayInput.value);if("-"===a||"--"===a)a="";return a};f.prototype.parse=function(a){return a?(a=a.split("-"),a.push(a.shift()),a):null};f.prototype.getMonthOptions=function(){return x};return{ErrorDisplayInput:j,Input:c,TextInput:m,PasswordInput:r,TextArea:p,NumericDateInput:f,AlphaDateInput:l,
NestedFields:k,NativeSelect:q,getProperties:v}}();
