LPServer=function(){var m=null,d=null,v,w=function(a,b){var c=a,e={},p;for(p in c){var d=c[p];if(null===d||void 0===d)d="";if("object"===typeof d)for(var g in d)d.hasOwnProperty(g)&&(e[p+"["+g+"]"]=d[g]);else e[p]=d}a=e;b=b||"";var c=[],f;for(f in a)e=a[f],"object"===typeof e?c=c.concat(w(e,f)):(b&&(f=b+"["+f+"]"),c.push(f+"="+encodeURIComponent(e)));return c};v=function(a){return w(a).join("&")};var x=function(a){var b=new XMLHttpRequest,c=a.contentType||"application/x-www-form-urlencoded";a.success&&
(b.onload=function(){if(4===b.readyState)if(200===b.status)switch(a.dataType){case "xml":a.success(b.responseXML,b.responseText);break;case "json":var c=null;try{c=JSON.parse(b.responseText)}catch(e){}a.success(c,b.responseText);break;default:a.success(b.responseText)}else a.error&&a.error(b,b.statusText)});a.error&&(b.onerror=function(){a.error(b,b.statusText)});var e=function(){return"application/json"===c?JSON.stringify(a.data):v(a.data)},d=a.url;"GET"===a.type&&(d=e(),d=a.url+(0<d.length?"?"+
d:""));b.open(a.type||"GET",d,!0);"POST"===a.type?(b.setRequestHeader("Content-Type",c),a.beforeSend&&a.beforeSend(b,a),b.send(e())):(a.beforeSend&&a.beforeSend(b,a),b.send())},y=function(a){return function(){a()}},f=function(a,b,c,e){g(a,b,c,e)||b.error(c)},g,z=function(a,b,c,e){return a&&(a=a[c],"function"===typeof a)?(a(e,b),!0):!1};g=function(a,b,c,e){a=z(a,b,c,e);return a=z(b.callbacks,b,c,e)||a};var A=function(a,b){try{h.logException(a)}catch(c){}a instanceof k?b.error(a.message):b.error();
if(LPServer.throwExceptions)throw a;},E=function(a,b){return function(c,e){try{if(!g(a,b,e)){if(null===c&&e&&"undefined"!==typeof DOMParser)try{c=(new DOMParser).parseFromString(e,"application/xml")}catch(d){}null===c?b.error("invalidxml"):D(c,a,b)}}catch(f){A(f,b)}}},l=function(a,b){var c=a.getElementsByTagName(b);return 0<c.length?c[0]:null},r=function(a,b){var c=l(a,b);return c?c.textContent:""},D=function(a,b,c){var e=l(a,"result"),d=l(a,"ok"),j=l(a,"error"),h=l(a,"failed");if(e){var d=e.getAttribute("rc"),
j=e.getAttribute("msg"),h=e.getAttribute("success"),k=e.getAttribute("ok");if(d){f(b,c,d,e);return}if(j){f(b,c,j,e);return}if(h){f(b,c,h,e);return}if(k){f(b,c,"ok");return}e=e.textContent.trim();if("ok"===e){if(!g(b,c,"ok")){f(b,c,r(a,"status"));return}}else if("bad"===e){c.error(r(a,"message"));return}}else{if(d){f(b,c,"ok",d);return}if(j){g(b,c,j.getAttribute("cause"),j)||f(b,c,j.getAttribute("message"),j);return}if(h){f(b,c,h.getAttribute("reason"),h);return}}"function"===typeof c.error&&c.error()},
F=function(a,b){return function(c,e){try{if(null===c&&e)b.error("invalidjson");else{if(c.error){g(a,b,c.error,c)||b.error&&b.error(c.errortxt||c.error);return}if(c.hasOwnProperty("success")){if(c.success&&g(a,b,"success",c))return;if(!c.success){b.error&&b.error();return}}else if(c.res)if("success"===c.res){if(g(a,b,c.res,c))return}else{f(a,b,c.res,c);return}else if(g(a,b,c.reason,c)||g(a,b,c.status,c)||g(a,b,c.cmd,c))return}if(a&&"function"===typeof a["default"])a["default"](c,b);else"function"===
typeof b.success&&b.success(c)}catch(d){A(d,b)}}},G=function(a,b){return function(c){var e;try{e=JSON.parse(c.responseText)}catch(d){b.error("invalidjson");return}g(a,b,e.code,e)||b.error(e.message)}},q=function(a){a.userSupplied=a.userSupplied||{};a.type=void 0===a.type?"POST":a.type;a.url=h.getBaseURL()+a.url;a.data=B(a.data,a.userSupplied.requestArgs);"undefined"===typeof a.error&&a.userSupplied.error&&(a.error=y(a.userSupplied.error));if(a.data&&(void 0===a.data.token&&(void 0===a.CSRFToken||
a.CSRFToken))&&null===m){var b=a.userSupplied.error;h.ajax({type:"POST",url:h.getBaseURL()+"getCSRFToken.php",success:function(b){m=b;h.ajax(a)},error:y(b)})}else h.ajax(a)},s=function(a,b){var c={},e=b.userSupplied;"object"!==typeof e&&(e=b.userSupplied={});switch(typeof b.success){case "string":return c[b.success]=e.success,a(c,e);case "function":return c["default"]=b.success,a(c,e);default:if(b.callbacks||e.success||e.callbacks)return a(b.callbacks,e)}return null},t=function(a,b){if(b.data&&void 0===
b.data.token&&(void 0===b.CSRFToken||b.CSRFToken))b.data.token=m},C=function(a,b,c){c=c||[];for(var e in b){var d=a[e],f=b[e];if("object"===typeof f)C(d,f,c.concat(e));else if(typeof d!==f)throw c.push(e),"Extension is missing the following property: "+c.join(".")+" ("+f+")";}},u=function(a,b,c){a=a.getAttribute(b);return void 0===a?c:a},B=function(a){a=a||{};for(var b=1,c=arguments.length;b<c;++b){var e=arguments[b],d;for(d in e)a[d]=e[d]}return a},n=function(a,b){return a?function(){var c=b.apply(window,
arguments);a.apply(window,c||arguments)}:b},H={StringUtils:{translate:"function"},AES:{Encrypt:"function",Decrypt:"function",hex2bin:"function",bin2hex:"function"},enc:"function",dec:"function",RSAKey:"function",createRandomHexString:"function",parse_public_key:"function",parse_private_key:"function",enccbc:"function",make_lp_key_iterations:"function",make_lp_hash_iterations:"function",get_random_password:"function"},I={RSAKey:!0},h={ajax:x,translate:function(){return d.StringUtils.translate.apply(d.StringUtils,
arguments)},logException:function(){},hex2bin:function(){return d.AES.hex2bin.apply(d.AES,arguments)},bin2hex:function(){return d.AES.bin2hex.apply(d.AES,arguments)},encryptAES:function(a,b){return 0<a.length?d.AES.Encrypt({pass:b,data:a,b64:!0,bits:256}):a},decryptAES:function(a,b){return d.AES.Decrypt({pass:b,data:a,b64:!0,bits:256})},encrypt:function(a,b){return d.enc(a,b)},decrypt:function(a,b){try{return d.dec(a,b)}catch(c){return""}},createRandomHexString:function(){return d.createRandomHexString.apply(d,
arguments)},parsePublicKey:function(){return d.parse_public_key.apply(d,arguments)},parsePrivateKey:function(a,b){b=b||d.rsaprivatekeyhex;if(!b)throw"rsaprivatekeyhex required for this action.";return d.parse_private_key(a,b)},extractPrivateKey:function(a,b){return d.rsa_extract_privatekey(a,b)},encryptCBC:function(){return d.enccbc.apply(d,arguments)},makeKey:function(){return d.make_lp_key_iterations.apply(d,arguments)},makeHash:function(){return d.make_lp_hash_iterations.apply(d,arguments)},makeRandomPassword:function(){return d.get_random_password.apply(d,
arguments)},getBaseURL:function(){return d.base_url||""},getLocalKey:function(){return d.g_local_key},setLocalKey:function(a){d.g_local_key=a}},k=function(a){this.message=a;this.stack=Error().stack};k.prototype=Object.create(Error.prototype);k.prototype.name="ClientException";k.prototype.constructor=k;var J=function(a){a.setRequestHeader("X-CSRF-TOKEN",m)};return{ajax:x,getRecordsFromResponse:function(a,b,c){for(var e=[],d=0;d<c;++d)e.push(u(a,b+d));return e},jsonRequest:function(a){a.dataType="json";
a.beforeSend=n(a.beforeSend,t);a.success=s(F,a);q(a)},xmlRequest:function(a){a.dataType="xml";a.beforeSend=n(a.beforeSend,t);a.success=s(E,a);q(a)},textRequest:function(a){a.dataType="text";a.beforeSend=n(a.beforeSend,t);q(a)},initialize:function(a,b){C(a,H);for(var c in b)h[c]=b[c];for(var e in I)h[e]=a[e];d=a},ext:h,getNodes:function(a,b){return a.getElementsByTagName(b)},getNode:l,getNodeText:r,getAttr:u,getAttrInt:function(a,b,c){a=parseInt(u(a,b,c));return isNaN(a)?c:a},extend:B,extendCallback:n,
ClientException:k,clearCSRFToken:function(){m=null},callback:function(a,b){a.callbacks&&"function"===typeof a.callbacks[b]&&a.callbacks[b].apply(window,Array.prototype.slice.call(arguments,2))},lmiapi:{jsonRequest:function(a){a.dataType="json";a.contentType="application/json";a.beforeSend=n(a.beforeSend,J);a.error=s(G,a);q(a)}}}}();
