var LPCFG={do_popup_actions:!0,popup_show_sitename_suffix:!0,popup_show_menu_expand_visual_cue:!0,g_do_icon_number_hint:!0,g_creditcard_profile_annotate:!0,g_visual_cue_on_hover:!0,RETRY_TIMEOUT_QUANTUM:30,__FINAL:0},LPIFRAMEVARS={g_genpws:[],g_myprefs:{},g_should_set_prefs:!0,g_sites:null,g_formfills:null,g_favicons:null,g_bigicons:null,g_genpwpattern:"",g_do_40fieldicon:!1,_FINAL:0},LPpop={create_popup_obj:function(b,d){function j(b){var a=0,c;for(c in b)a++;return a}if(do_experimental_popupfill){var c=
"undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"",a=null,e=null,l=null,p=null,p=b.createElement(c+"div");p.style.display="block";p.style.border="0";if(!p)return null;var g=e=null,m=e=null,h,r,f,q=0,l=0;LPCFG.popup_show_menu_expand_visual_cue&&(l=24);r="undefined"!=typeof measureText?measureText:LP_measureText;var t={};"undefined"!=typeof d.favicons&&(t=LPJSON.parse(d.favicons));e=b.createElement(c+"div");if(!e)return null;e.setAttribute("id","popupcontainer");p.appendChild(e);g=b.createElement(c+
"table");if(!g)return null;g.setAttribute("id","lptabpopup");e.appendChild(g);e=b.createElement(c+"div");if(!e)return null;e.setAttribute("id","popupcontainerff");p.appendChild(e);m=b.createElement(c+"table");if(!m)return null;m.setAttribute("id","lptabpopupformfills");m.style.display="none";e.appendChild(m);tbodyff=b.createElement(c+"tbody");tbodyff.setAttribute("id","lptbodyff");m.appendChild(tbodyff);if("undefined"==typeof d.sites)m=0;else for(f in h=LPpop.getAutoFillArray(b,LPJSON.parse(d.sites),
!0),m=j(h),h)if(h.hasOwnProperty(f)&&null!=h[f]&&null!=h[f].useusername){var n=h[f].useusername;0>=n.length&&(n=h[f].name);var s=n,a=b.createElement(c+"tr");if(!a)return null;a.setAttribute("id","trpopuprow"+lp_ofa(f));a.setAttribute("aid",h[f].aid);a.setAttribute("sitename",h[f].name);a.setAttribute("username",h[f].useusername);a.className="popuprow";LPIFRAMEVARS.g_do_40fieldicon&&(a.style.height="39px");g.appendChild(a);e=b.createElement(c+"td");if(!e)return null;e.setAttribute("id","tdpopuprow"+
lp_ofa(f));e.setAttribute("aid",lp_ofa(h[f].aid));a.appendChild(e);"undefined"!=typeof t[h[f].aid]&&(LPIFRAMEVARS.g_do_40fieldicon?(a=LPpop.gen_image_frag(b,LPpop.lookup_bigicon(h[f].aid)),a.width="88px",a.height="22px",a.style.width="88px",a.style.height="22px"):a=LPpop.gen_image_frag(b,LPpop.lookup_favicon(h[f].aid)),a&&e.appendChild(a));if(LPIFRAMEVARS.g_do_40fieldicon){var k=b.createElement(c+"div");k.style.position="absolute";k.style.display="inline-block";k.style.left="104px"}a=b.createElement(c+
"span");if(!a)return null;a.setAttribute("id","spanpopuprow"+lp_ofa(f));a.className="popcell shortenstr";LPIFRAMEVARS.g_do_40fieldicon&&(a.style.fontSize="11px",a.style.fontWeight="bold");"undefined"!=typeof g_isedge&&g_isedge&&a.setAttribute("x-ms-format-detection","none");LP_elt_set_text(a,n);LPIFRAMEVARS.g_do_40fieldicon?(k.appendChild(a),e.appendChild(k)):e.appendChild(a);LPCFG.popup_show_menu_expand_visual_cue&&(a=LPpop.visual_cue_frag(b,"expand",f))&&(LPIFRAMEVARS.g_do_40fieldicon?k.appendChild(a):
e.appendChild(a));if(LPCFG.popup_show_sitename_suffix&&(a=LPpop.subscript_name_frag(b,h[f].name)))LPIFRAMEVARS.g_do_40fieldicon?(a.style.paddingLeft=0,k.appendChild(a)):e.appendChild(a);e=r(b,s,null,"font-size: 14px;font-family: Helvetica,Arial,sans-serif;font-weight:bold;");e.width+20+l>q&&(q=e.width+20+l)}if("undefined"==typeof d.formfills)r=0;else{g=LPJSON.parse(d.formfills);r=j(g);for(h=0;1>=h;h++)for(f in g)if(g.hasOwnProperty(f)&&null!=g[f]&&null!=g[f].decprofilename&&null!=g[f].profiletype&&
parseInt(g[f].profiletype)===h){a=b.createElement(c+"tr");if(!a)return null;a.setAttribute("id","trpopupffrow"+lp_ofa(f));a.setAttribute("ffid",g[f].ffid);a.setAttribute("profilename",g[f].decprofilename);a.setAttribute("formtype",h);""!=g[f].ccnum&&0==g[f].profiletype&&a.setAttribute("hascc","1");a.className="popuprow";tbodyff.appendChild(a);e=b.createElement(c+"td");if(!e)return null;e.setAttribute("id","tdpopupffrow"+lp_ofa(f));e.setAttribute("ffid",g[f].ffid);a.appendChild(e);"undefined"!=typeof t[g[f].ffid]&&
(LPIFRAMEVARS.g_do_40fieldicon?(a=LPpop.gen_image_frag(b,LPpop.lookup_bigicon(g[f].ffid)),a.width="88px",a.height="22px",a.style.width="88px",a.style.height="22px",a.style.backgroundColor="#666666"):a=LPpop.gen_image_frag(b,LPpop.lookup_favicon(g[f].ffid)),a&&e.appendChild(a));LPIFRAMEVARS.g_do_40fieldicon&&(k=b.createElement(c+"div"),k.style.position="absolute",k.style.display="inline-block",k.style.left="104px");s=g[f].decprofilename;a=b.createElement(c+"span");a.className="popcell shortenstr";
a.setAttribute("id","spanpopupffrow"+lp_ofa(f));LPIFRAMEVARS.g_do_40fieldicon&&(a.style.fontSize="11px",a.style.fontWeight="bold");LP_elt_set_text(a,lp_of(g[f].decprofilename,b));LPIFRAMEVARS.g_do_40fieldicon?(k.appendChild(a),e.appendChild(k)):e.appendChild(a);LPCFG.g_creditcard_profile_annotate&&1==h&&(n=b.createElement(c+"span"),n.className="cc",LP_elt_set_text(n,"("+lpgs("Credit Card")+")"),a.appendChild(n),s+=lpgs("Credit Card"));LPCFG.popup_show_menu_expand_visual_cue&&(a=LPpop.visual_cue_frag(b,
"expandff",f))&&(LPIFRAMEVARS.g_do_40fieldicon?k.appendChild(a):e.appendChild(a));e=measureText(b,s,null,"font-size: 14px;font-family: Helvetica,Arial,sans-serif;font-weight:bold;");e.width+20+l>q&&(q=e.width+20+l)}}if(LPCFG.do_popup_actions){if(0<r){a=b.createElement(c+"tr");if(!a)return null;a.className="tablerow_sep";tbodyff.appendChild(a);e=b.createElement(c+"td");if(!e)return null;a.appendChild(e);l=b.createElement(c+"hr");if(!l)return null;e.appendChild(l)}}else if(0>=m&&0>=r)return null;300<
q&&(q=300);g_popupfill_widest=q;return p}},visual_cue_frag:function(b,d,j){var c=null,a="undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"";if(!d||!b)return null;if(LPCFG.popup_show_menu_expand_visual_cue){c=b.createElement(a+"span");if(!c)return null;c.setAttribute("id",d+lp_ofa(j));c.setAttribute("expander","true");c.className="expander";LPCFG.g_visual_cue_on_hover&&(c.style.display="none");LPIFRAMEVARS.g_do_40fieldicon&&(c.style.paddingRight="16px");if(b=LPpop.gen_image_frag(b,"arrow.png"))b.setAttribute("id",
d+"img"+lp_ofa(j)),b.setAttribute("alt","+"),c.appendChild(b)}return c},subscript_name_frag:function(b,d){var j=null;if(!b)return null;var c="undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"";d&&0<d.length&&(j=b.createElement(c+"p"),j.className="subtext",LP_elt_set_text(j,d),LPIFRAMEVARS.g_do_40fieldicon&&(j.className+=" shortenstr"));return j},gen_image_frag:function(b,d){if(!b)return null;var j="undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"",c=null;if(g_isfirefox){c=b.createElement("image");
if(!c)return null;c.setAttribute("src",d);c.style.padding="2px"}else{c=b.createElement(j+"img");if(!c)return null;c.setAttribute("src",d);c.style.padding="2px";c.setAttribute("alt","")}return c},set_icon_hint_from_data:function(b,d){function j(b){var a=0,c;for(c in b)a++;return a}if(LPCFG.g_do_icon_number_hint){var c,a;"undefined"==typeof d.sites?c=0:(c=LPpop.getAutoFillArray(b,LPJSON.parse(d.sites),!0),c=j(c));"undefined"==typeof d.formfills?a=0:(a=LPJSON.parse(d.formfills),a=j(a));g_icon_numbers.sites=
c;g_icon_numbers.formfills=a}},getAutoFillArray:function(b,d,j){var c=[];b=punycode.URLToASCII(b.location.href);lpcanonizeUrl(b);for(var a in d)if(!d[a].genpw||j)c[a]=d[a];return c},lookup_username:function(b){var d;if(LPIFRAMEVARS&&LPIFRAMEVARS.g_sites&&null!==b)for(d in LPIFRAMEVARS.g_sites)if(LPIFRAMEVARS.g_sites[d]&&LPIFRAMEVARS.g_sites[d].aid==b){b=LPIFRAMEVARS.g_sites[d];if(b.useusername)return b.useusername;if(b.unencryptedUsername)return b.unencryptedUsername;break}return""},lookup_sitename:function(b){var d;
if(LPIFRAMEVARS&&LPIFRAMEVARS.g_sites&&null!==b)for(d in LPIFRAMEVARS.g_sites)if(LPIFRAMEVARS.g_sites[d]&&LPIFRAMEVARS.g_sites[d].aid==b){b=LPIFRAMEVARS.g_sites[d];if(b.sitename)return b.sitename;if(b.name)return b.name;break}return""},lookup_profile:function(b){var d;if(LPIFRAMEVARS&&LPIFRAMEVARS.g_formfills&&null!==b)for(d in LPIFRAMEVARS.g_formfills)if(LPIFRAMEVARS.g_formfills[d]&&LPIFRAMEVARS.g_formfills[d].ffid==b){b=LPIFRAMEVARS.g_formfills[d];if(b.decprofilename)return b.decprofilename;if(b.decprofilename)return b.profilename;
break}return""},lookup_favicon:function(b){if(LPIFRAMEVARS&&LPIFRAMEVARS.g_favicons&&null!==b)return(b=LPIFRAMEVARS.g_favicons[b])?b:null},lookup_bigicon:function(b){if(LPIFRAMEVARS&&LPIFRAMEVARS.g_bigicons&&null!==b)return(b=LPIFRAMEVARS.g_bigicons[b])?b:null},__FINAL__:0};
